// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToAccountBalance = `-- name: AddToAccountBalance :exec
UPDATE accounts SET balance = balance + $1::bigint WHERE id = $2
`

type AddToAccountBalanceParams struct {
	Column1 int64       `json:"column_1"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) AddToAccountBalance(ctx context.Context, arg *AddToAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, addToAccountBalance, arg.Column1, arg.ID)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name, account_number, account_type, parent_id, balance, is_system)
VALUES (gen_random_uuid(), $1, $2, $3, $4, 0, false)
RETURNING id, name, balance, account_number, account_type, parent_id, is_system
`

type CreateAccountParams struct {
	Name          string      `json:"name"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	AccountType   string      `json:"account_type"`
	ParentID      pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.AccountNumber,
		arg.AccountType,
		arg.ParentID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.AccountNumber,
		&i.AccountType,
		&i.ParentID,
		&i.IsSystem,
	)
	return &i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, balance, account_number, account_type, parent_id, is_system
FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.AccountNumber,
		&i.AccountType,
		&i.ParentID,
		&i.IsSystem,
	)
	return &i, err
}

const getSystemAccountByNumber = `-- name: GetSystemAccountByNumber :one
SELECT id, name, balance FROM accounts WHERE account_number = $1 AND is_system = true LIMIT 1
`

type GetSystemAccountByNumberRow struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Balance int64       `json:"balance"`
}

func (q *Queries) GetSystemAccountByNumber(ctx context.Context, accountNumber pgtype.Int4) (*GetSystemAccountByNumberRow, error) {
	row := q.db.QueryRow(ctx, getSystemAccountByNumber, accountNumber)
	var i GetSystemAccountByNumberRow
	err := row.Scan(&i.ID, &i.Name, &i.Balance)
	return &i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, balance, account_number, account_type, parent_id, is_system
FROM accounts
ORDER BY account_number NULLS LAST, name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]*Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.AccountNumber,
			&i.AccountType,
			&i.ParentID,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1, account_number = $2, account_type = $3, parent_id = $4
WHERE id = $5
RETURNING id, name, balance, account_number, account_type, parent_id, is_system
`

type UpdateAccountParams struct {
	Name          string      `json:"name"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	AccountType   string      `json:"account_type"`
	ParentID      pgtype.UUID `json:"parent_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg *UpdateAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.AccountNumber,
		arg.AccountType,
		arg.ParentID,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.AccountNumber,
		&i.AccountType,
		&i.ParentID,
		&i.IsSystem,
	)
	return &i, err
}
