// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLog = `-- name: CountActivityLog :one
SELECT COUNT(*) FROM activity_log
WHERE ($1 = '' OR entity_type = $1)
  AND ($2 = '' OR action = $2)
  AND ($3 = '' OR username ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR created_at::date >= $4)
  AND ($5::date IS NULL OR created_at::date <= $5)
`

type CountActivityLogParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 pgtype.Date `json:"column_4"`
	Column5 pgtype.Date `json:"column_5"`
}

func (q *Queries) CountActivityLog(ctx context.Context, arg *CountActivityLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLog,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldActivityLog = `-- name: DeleteOldActivityLog :exec
DELETE FROM activity_log WHERE created_at < $1
`

func (q *Queries) DeleteOldActivityLog(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldActivityLog, createdAt)
	return result.RowsAffected(), err
}

const insertActivityLog = `-- name: InsertActivityLog :exec
INSERT INTO activity_log (id, user_id, username, action, entity_type, entity_id, description)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6)
`

type InsertActivityLogParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Username    string      `json:"username"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Description string      `json:"description"`
}

func (q *Queries) InsertActivityLog(ctx context.Context, arg *InsertActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertActivityLog,
		arg.UserID,
		arg.Username,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Description,
	)
	return err
}

const listActivityLog = `-- name: ListActivityLog :many
SELECT
    al.id, al.user_id, al.username, al.action, al.entity_type,
    al.entity_id, al.description, al.created_at
FROM activity_log al
WHERE ($1 = '' OR al.entity_type = $1)
  AND ($2 = '' OR al.action = $2)
  AND ($3 = '' OR al.username ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR al.created_at::date >= $4)
  AND ($5::date IS NULL OR al.created_at::date <= $5)
ORDER BY al.created_at DESC
LIMIT $6 OFFSET $7
`

type ListActivityLogParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 pgtype.Date `json:"column_4"`
	Column5 pgtype.Date `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListActivityLog(ctx context.Context, arg *ListActivityLogParams) ([]*ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLog,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogForExport = `-- name: ListActivityLogForExport :many
SELECT id, username, action, entity_type, entity_id, description, created_at
FROM activity_log
WHERE ($1::date IS NULL OR created_at::date >= $1)
  AND ($2::date IS NULL OR created_at::date <= $2)
ORDER BY created_at DESC
`

type ListActivityLogForExportParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListActivityLogForExportRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActivityLogForExport(ctx context.Context, arg *ListActivityLogForExportParams) ([]*ListActivityLogForExportRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogForExport, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActivityLogForExportRow
	for rows.Next() {
		var i ListActivityLogForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
