// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM token_blocklist WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return &i, err
}

const insertTokenBlocklist = `-- name: InsertTokenBlocklist :exec
INSERT INTO token_blocklist (jti, expires_at)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertTokenBlocklistParams struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertTokenBlocklist(ctx context.Context, arg *InsertTokenBlocklistParams) error {
	_, err := q.db.Exec(ctx, insertTokenBlocklist, arg.Jti, arg.ExpiresAt)
	return err
}

const isTokenBlocked = `-- name: IsTokenBlocked :one
SELECT EXISTS(
  SELECT 1 FROM token_blocklist WHERE jti = $1
) AS blocked
`

func (q *Queries) IsTokenBlocked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenBlocked, jti)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}
