// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDivisionsByBranch = `-- name: CountDivisionsByBranch :one
SELECT COUNT(*) FROM divisions WHERE branch_id = $1
`

func (q *Queries) CountDivisionsByBranch(ctx context.Context, branchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDivisionsByBranch, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountForBranch = `-- name: CreateAccountForBranch :one
INSERT INTO accounts (id, name, account_number, account_type, balance, is_system)
VALUES (gen_random_uuid(), $1, $2, $3, 0, false)
RETURNING id
`

type CreateAccountForBranchParams struct {
	Name          string      `json:"name"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	AccountType   string      `json:"account_type"`
}

func (q *Queries) CreateAccountForBranch(ctx context.Context, arg *CreateAccountForBranchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccountForBranch, arg.Name, arg.AccountNumber, arg.AccountType)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (id, name, revenue_account_id, expense_account_id)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, name, revenue_account_id, expense_account_id, created_at
`

type CreateBranchParams struct {
	Name             string      `json:"name"`
	RevenueAccountID pgtype.UUID `json:"revenue_account_id"`
	ExpenseAccountID pgtype.UUID `json:"expense_account_id"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg *CreateBranchParams) (*Branch, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.Name, arg.RevenueAccountID, arg.ExpenseAccountID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RevenueAccountID,
		&i.ExpenseAccountID,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches WHERE id = $1
`

func (q *Queries) DeleteBranch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT
    b.id, b.name, b.created_at,
    b.revenue_account_id, ra.name AS revenue_account_name,
    b.expense_account_id, ea.name AS expense_account_name
FROM branches b
LEFT JOIN accounts ra ON ra.id = b.revenue_account_id
LEFT JOIN accounts ea ON ea.id = b.expense_account_id
WHERE b.id = $1
`

type GetBranchByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RevenueAccountID   pgtype.UUID        `json:"revenue_account_id"`
	RevenueAccountName pgtype.Text        `json:"revenue_account_name"`
	ExpenseAccountID   pgtype.UUID        `json:"expense_account_id"`
	ExpenseAccountName pgtype.Text        `json:"expense_account_name"`
}

func (q *Queries) GetBranchByID(ctx context.Context, id pgtype.UUID) (*GetBranchByIDRow, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i GetBranchByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.RevenueAccountID,
		&i.RevenueAccountName,
		&i.ExpenseAccountID,
		&i.ExpenseAccountName,
	)
	return &i, err
}

const getBranchExpenseAccountID = `-- name: GetBranchExpenseAccountID :one
SELECT expense_account_id FROM branches WHERE id = $1
`

func (q *Queries) GetBranchExpenseAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBranchExpenseAccountID, id)
	var expense_account_id pgtype.UUID
	err := row.Scan(&expense_account_id)
	return expense_account_id, err
}

const getBranchRevenueAccountID = `-- name: GetBranchRevenueAccountID :one
SELECT revenue_account_id FROM branches WHERE id = $1
`

func (q *Queries) GetBranchRevenueAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBranchRevenueAccountID, id)
	var revenue_account_id pgtype.UUID
	err := row.Scan(&revenue_account_id)
	return revenue_account_id, err
}

const getNextExpenseAccountNumber = `-- name: GetNextExpenseAccountNumber :one
SELECT COALESCE(MAX(account_number), 49999) + 1 AS next_number
FROM accounts WHERE account_number BETWEEN 50000 AND 59999
`

func (q *Queries) GetNextExpenseAccountNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextExpenseAccountNumber)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getNextRevenueAccountNumber = `-- name: GetNextRevenueAccountNumber :one
SELECT COALESCE(MAX(account_number), 39999) + 1 AS next_number
FROM accounts WHERE account_number BETWEEN 40000 AND 49999
`

func (q *Queries) GetNextRevenueAccountNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextRevenueAccountNumber)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const listBranches = `-- name: ListBranches :many
SELECT
    b.id, b.name, b.created_at,
    b.revenue_account_id, ra.name AS revenue_account_name,
    b.expense_account_id, ea.name AS expense_account_name
FROM branches b
LEFT JOIN accounts ra ON ra.id = b.revenue_account_id
LEFT JOIN accounts ea ON ea.id = b.expense_account_id
ORDER BY b.name
`

type ListBranchesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RevenueAccountID   pgtype.UUID        `json:"revenue_account_id"`
	RevenueAccountName pgtype.Text        `json:"revenue_account_name"`
	ExpenseAccountID   pgtype.UUID        `json:"expense_account_id"`
	ExpenseAccountName pgtype.Text        `json:"expense_account_name"`
}

func (q *Queries) ListBranches(ctx context.Context) ([]*ListBranchesRow, error) {
	rows, err := q.db.Query(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListBranchesRow
	for rows.Next() {
		var i ListBranchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.RevenueAccountID,
			&i.RevenueAccountName,
			&i.ExpenseAccountID,
			&i.ExpenseAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches SET name = $1 WHERE id = $2
RETURNING id, name, revenue_account_id, expense_account_id, created_at
`

type UpdateBranchParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg *UpdateBranchParams) (*Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch, arg.Name, arg.ID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RevenueAccountID,
		&i.ExpenseAccountID,
		&i.CreatedAt,
	)
	return &i, err
}
