// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_deposits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCashDeposit = `-- name: CancelCashDeposit :exec
UPDATE cash_deposits
SET status = 'cancelled', cancelled_by = $1, cancelled_at = now(), cancel_reason = $2
WHERE id = $3
`

type CancelCashDepositParams struct {
	CancelledBy  pgtype.UUID `json:"cancelled_by"`
	CancelReason string      `json:"cancel_reason"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) CancelCashDeposit(ctx context.Context, arg *CancelCashDepositParams) error {
	_, err := q.db.Exec(ctx, cancelCashDeposit, arg.CancelledBy, arg.CancelReason, arg.ID)
	return err
}

const createCashDeposit = `-- name: CreateCashDeposit :one
INSERT INTO cash_deposits (
    id, number, date, branch_id, movement_type, from_account_id, to_account_id,
    amount, reference, handed_to, notes, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, number, date, branch_id, movement_type, from_account_id, to_account_id,
          amount, reference, handed_to, notes, photo_path, status,
          created_by, created_at, cancelled_by, cancelled_at, cancel_reason
`

type CreateCashDepositParams struct {
	Number        string      `json:"number"`
	Date          pgtype.Date `json:"date"`
	BranchID      pgtype.UUID `json:"branch_id"`
	MovementType  string      `json:"movement_type"`
	FromAccountID pgtype.UUID `json:"from_account_id"`
	ToAccountID   pgtype.UUID `json:"to_account_id"`
	Amount        int64       `json:"amount"`
	Reference     string      `json:"reference"`
	HandedTo      string      `json:"handed_to"`
	Notes         string      `json:"notes"`
	CreatedBy     pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCashDeposit(ctx context.Context, arg *CreateCashDepositParams) (*CashDeposit, error) {
	row := q.db.QueryRow(ctx, createCashDeposit,
		arg.Number,
		arg.Date,
		arg.BranchID,
		arg.MovementType,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Reference,
		arg.HandedTo,
		arg.Notes,
		arg.CreatedBy,
	)
	var i CashDeposit
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Date,
		&i.BranchID,
		&i.MovementType,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Reference,
		&i.HandedTo,
		&i.Notes,
		&i.PhotoPath,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return &i, err
}

const getCashDepositRow = `-- name: GetCashDepositRow :one
SELECT id, number, date, branch_id, movement_type, from_account_id, to_account_id,
       amount, reference, handed_to, notes, photo_path, status,
       created_by, created_at, cancelled_by, cancelled_at, cancel_reason
FROM cash_deposits WHERE id = $1
`

func (q *Queries) GetCashDepositRow(ctx context.Context, id pgtype.UUID) (*CashDeposit, error) {
	row := q.db.QueryRow(ctx, getCashDepositRow, id)
	var i CashDeposit
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Date,
		&i.BranchID,
		&i.MovementType,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Reference,
		&i.HandedTo,
		&i.Notes,
		&i.PhotoPath,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return &i, err
}

const listCashDeposits = `-- name: ListCashDeposits :many
SELECT
    cd.id, cd.number, cd.date, cd.movement_type, cd.amount, cd.reference,
    cd.handed_to, cd.notes, cd.photo_path, cd.status,
    cd.branch_id, b.name AS branch_name,
    cd.from_account_id, fa.name AS from_account_name,
    cd.to_account_id, ta.name AS to_account_name,
    cd.created_at, u.username AS created_by_name,
    cd.cancelled_at, cd.cancel_reason
FROM cash_deposits cd
LEFT JOIN branches b ON b.id = cd.branch_id
JOIN accounts fa     ON fa.id = cd.from_account_id
JOIN accounts ta     ON ta.id = cd.to_account_id
LEFT JOIN users u    ON u.id = cd.created_by
WHERE ($1::uuid IS NULL OR cd.branch_id = $1)
  AND ($2::date IS NULL OR cd.date >= $2)
  AND ($3::date IS NULL OR cd.date <= $3)
  AND ($4::text IS NULL OR cd.movement_type = $4)
  AND ($5::text IS NULL OR cd.status = $5)
ORDER BY cd.date DESC, cd.created_at DESC
`

type ListCashDepositsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Column4 pgtype.Text `json:"column_4"`
	Column5 pgtype.Text `json:"column_5"`
}

type ListCashDepositsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Number          string             `json:"number"`
	Date            pgtype.Date        `json:"date"`
	MovementType    string             `json:"movement_type"`
	Amount          int64              `json:"amount"`
	Reference       string             `json:"reference"`
	HandedTo        string             `json:"handed_to"`
	Notes           string             `json:"notes"`
	PhotoPath       pgtype.Text        `json:"photo_path"`
	Status          string             `json:"status"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	BranchName      pgtype.Text        `json:"branch_name"`
	FromAccountID   pgtype.UUID        `json:"from_account_id"`
	FromAccountName string             `json:"from_account_name"`
	ToAccountID     pgtype.UUID        `json:"to_account_id"`
	ToAccountName   string             `json:"to_account_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedByName   pgtype.Text        `json:"created_by_name"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason    string             `json:"cancel_reason"`
}

func (q *Queries) ListCashDeposits(ctx context.Context, arg *ListCashDepositsParams) ([]*ListCashDepositsRow, error) {
	rows, err := q.db.Query(ctx, listCashDeposits,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCashDepositsRow
	for rows.Next() {
		var i ListCashDepositsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Date,
			&i.MovementType,
			&i.Amount,
			&i.Reference,
			&i.HandedTo,
			&i.Notes,
			&i.PhotoPath,
			&i.Status,
			&i.BranchID,
			&i.BranchName,
			&i.FromAccountID,
			&i.FromAccountName,
			&i.ToAccountID,
			&i.ToAccountName,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.CancelledAt,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCashDepositNumber = `-- name: NextCashDepositNumber :one
SELECT 'ST-' || LPAD(nextval('cash_deposit_number_seq')::text, 6, '0') AS number
`

func (q *Queries) NextCashDepositNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextCashDepositNumber)
	var number string
	err := row.Scan(&number)
	return number, err
}

const setCashDepositPhoto = `-- name: SetCashDepositPhoto :exec
UPDATE cash_deposits SET photo_path = $1 WHERE id = $2
`

type SetCashDepositPhotoParams struct {
	PhotoPath pgtype.Text `json:"photo_path"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetCashDepositPhoto(ctx context.Context, arg *SetCashDepositPhotoParams) error {
	_, err := q.db.Exec(ctx, setCashDepositPhoto, arg.PhotoPath, arg.ID)
	return err
}

const sumCashDepositsForAccountDay = `-- name: SumCashDepositsForAccountDay :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE to_account_id = $1), 0)::bigint   AS cash_in,
    COALESCE(SUM(amount) FILTER (WHERE from_account_id = $1), 0)::bigint AS cash_out
FROM cash_deposits
WHERE date = $2 AND status = 'posted'
  AND (to_account_id = $1 OR from_account_id = $1)
`

type SumCashDepositsForAccountDayParams struct {
	ToAccountID pgtype.UUID `json:"to_account_id"`
	Date        pgtype.Date `json:"date"`
}

type SumCashDepositsForAccountDayRow struct {
	CashIn  int64 `json:"cash_in"`
	CashOut int64 `json:"cash_out"`
}

func (q *Queries) SumCashDepositsForAccountDay(ctx context.Context, arg *SumCashDepositsForAccountDayParams) (*SumCashDepositsForAccountDayRow, error) {
	row := q.db.QueryRow(ctx, sumCashDepositsForAccountDay, arg.ToAccountID, arg.Date)
	var i SumCashDepositsForAccountDayRow
	err := row.Scan(&i.CashIn, &i.CashOut)
	return &i, err
}
