// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_tracking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCashDayCount = `-- name: GetCashDayCount :one
SELECT id, branch_id, count_date, opening_amount, opening_by, opening_at,
       closing_amount, closing_by, closing_at, expected_closing, variance,
       variance_note, cash_sales, cash_in, cash_out, cash_expenses, created_at
FROM cash_day_counts
WHERE branch_id = $1 AND count_date = $2
`

type GetCashDayCountParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	CountDate pgtype.Date `json:"count_date"`
}

func (q *Queries) GetCashDayCount(ctx context.Context, arg *GetCashDayCountParams) (*CashDayCount, error) {
	row := q.db.QueryRow(ctx, getCashDayCount, arg.BranchID, arg.CountDate)
	var i CashDayCount
	err := row.Scan(
		&i.ID, &i.BranchID, &i.CountDate,
		&i.OpeningAmount, &i.OpeningBy, &i.OpeningAt,
		&i.ClosingAmount, &i.ClosingBy, &i.ClosingAt,
		&i.ExpectedClosing, &i.Variance, &i.VarianceNote,
		&i.CashSales, &i.CashIn, &i.CashOut, &i.CashExpenses, &i.CreatedAt,
	)
	return &i, err
}

const getPOSSettlementForDay = `-- name: GetPOSSettlementForDay :many
SELECT branch_id, account_id, account_name, is_cash_drawer, amount
FROM pos_settlement_by_branch
WHERE date = $1
ORDER BY is_cash_drawer DESC, account_name
`

type GetPOSSettlementForDayRow struct {
	BranchID     pgtype.UUID `json:"branch_id"`
	AccountID    pgtype.UUID `json:"account_id"`
	AccountName  string      `json:"account_name"`
	IsCashDrawer bool        `json:"is_cash_drawer"`
	Amount       int64       `json:"amount"`
}

func (q *Queries) GetPOSSettlementForDay(ctx context.Context, date pgtype.Date) ([]*GetPOSSettlementForDayRow, error) {
	rows, err := q.db.Query(ctx, getPOSSettlementForDay, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPOSSettlementForDayRow
	for rows.Next() {
		var i GetPOSSettlementForDayRow
		if err := rows.Scan(&i.BranchID, &i.AccountID, &i.AccountName, &i.IsCashDrawer, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPOSSettlementRange = `-- name: GetPOSSettlementRange :many
SELECT branch_id, date, account_id, account_name, is_cash_drawer, amount
FROM pos_settlement_by_branch
WHERE date BETWEEN $1 AND $2
  AND ($3::uuid IS NULL OR branch_id = $3)
ORDER BY date DESC, is_cash_drawer DESC, account_name
`

type GetPOSSettlementRangeParams struct {
	Date    pgtype.Date `json:"date"`
	Date_2  pgtype.Date `json:"date_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

type GetPOSSettlementRangeRow struct {
	BranchID     pgtype.UUID `json:"branch_id"`
	Date         pgtype.Date `json:"date"`
	AccountID    pgtype.UUID `json:"account_id"`
	AccountName  string      `json:"account_name"`
	IsCashDrawer bool        `json:"is_cash_drawer"`
	Amount       int64       `json:"amount"`
}

func (q *Queries) GetPOSSettlementRange(ctx context.Context, arg *GetPOSSettlementRangeParams) ([]*GetPOSSettlementRangeRow, error) {
	rows, err := q.db.Query(ctx, getPOSSettlementRange, arg.Date, arg.Date_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPOSSettlementRangeRow
	for rows.Next() {
		var i GetPOSSettlementRangeRow
		if err := rows.Scan(&i.BranchID, &i.Date, &i.AccountID, &i.AccountName, &i.IsCashDrawer, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreviousCashDayClosing = `-- name: GetPreviousCashDayClosing :one
SELECT count_date, closing_amount
FROM cash_day_counts
WHERE branch_id = $1 AND count_date < $2 AND closing_amount IS NOT NULL
ORDER BY count_date DESC
LIMIT 1
`

type GetPreviousCashDayClosingParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	CountDate pgtype.Date `json:"count_date"`
}

type GetPreviousCashDayClosingRow struct {
	CountDate     pgtype.Date `json:"count_date"`
	ClosingAmount pgtype.Int8 `json:"closing_amount"`
}

func (q *Queries) GetPreviousCashDayClosing(ctx context.Context, arg *GetPreviousCashDayClosingParams) (*GetPreviousCashDayClosingRow, error) {
	row := q.db.QueryRow(ctx, getPreviousCashDayClosing, arg.BranchID, arg.CountDate)
	var i GetPreviousCashDayClosingRow
	err := row.Scan(&i.CountDate, &i.ClosingAmount)
	return &i, err
}

const listCashDayCounts = `-- name: ListCashDayCounts :many
SELECT
    c.id, c.branch_id, b.name AS branch_name, c.count_date,
    c.opening_amount, c.closing_amount, c.expected_closing, c.variance, c.variance_note,
    c.cash_sales, c.cash_in, c.cash_out, c.cash_expenses,
    ou.username AS opening_by_name, cu.username AS closing_by_name
FROM cash_day_counts c
JOIN branches b    ON b.id = c.branch_id
LEFT JOIN users ou ON ou.id = c.opening_by
LEFT JOIN users cu ON cu.id = c.closing_by
WHERE ($1::uuid IS NULL OR c.branch_id = $1)
  AND ($2::date IS NULL OR c.count_date >= $2)
  AND ($3::date IS NULL OR c.count_date <= $3)
ORDER BY c.count_date DESC, b.name
`

type ListCashDayCountsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

type ListCashDayCountsRow struct {
	ID              pgtype.UUID `json:"id"`
	BranchID        pgtype.UUID `json:"branch_id"`
	BranchName      string      `json:"branch_name"`
	CountDate       pgtype.Date `json:"count_date"`
	OpeningAmount   int64       `json:"opening_amount"`
	ClosingAmount   pgtype.Int8 `json:"closing_amount"`
	ExpectedClosing pgtype.Int8 `json:"expected_closing"`
	Variance        pgtype.Int8 `json:"variance"`
	VarianceNote    string      `json:"variance_note"`
	CashSales       int64       `json:"cash_sales"`
	CashIn          int64       `json:"cash_in"`
	CashOut         int64       `json:"cash_out"`
	CashExpenses    int64       `json:"cash_expenses"`
	OpeningByName   pgtype.Text `json:"opening_by_name"`
	ClosingByName   pgtype.Text `json:"closing_by_name"`
}

func (q *Queries) ListCashDayCounts(ctx context.Context, arg *ListCashDayCountsParams) ([]*ListCashDayCountsRow, error) {
	rows, err := q.db.Query(ctx, listCashDayCounts, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCashDayCountsRow
	for rows.Next() {
		var i ListCashDayCountsRow
		if err := rows.Scan(
			&i.ID, &i.BranchID, &i.BranchName, &i.CountDate,
			&i.OpeningAmount, &i.ClosingAmount, &i.ExpectedClosing, &i.Variance, &i.VarianceNote,
			&i.CashSales, &i.CashIn, &i.CashOut, &i.CashExpenses,
			&i.OpeningByName, &i.ClosingByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashDayStatus = `-- name: ListCashDayStatus :many
SELECT
    b.id AS branch_id, b.name AS branch_name,
    c.opening_amount, c.closing_amount, c.expected_closing, c.variance, c.variance_note
FROM branches b
LEFT JOIN cash_day_counts c ON c.branch_id = b.id AND c.count_date = $1
ORDER BY b.name
`

type ListCashDayStatusRow struct {
	BranchID        pgtype.UUID `json:"branch_id"`
	BranchName      string      `json:"branch_name"`
	OpeningAmount   pgtype.Int8 `json:"opening_amount"`
	ClosingAmount   pgtype.Int8 `json:"closing_amount"`
	ExpectedClosing pgtype.Int8 `json:"expected_closing"`
	Variance        pgtype.Int8 `json:"variance"`
	VarianceNote    pgtype.Text `json:"variance_note"`
}

func (q *Queries) ListCashDayStatus(ctx context.Context, countDate pgtype.Date) ([]*ListCashDayStatusRow, error) {
	rows, err := q.db.Query(ctx, listCashDayStatus, countDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCashDayStatusRow
	for rows.Next() {
		var i ListCashDayStatusRow
		if err := rows.Scan(
			&i.BranchID, &i.BranchName,
			&i.OpeningAmount, &i.ClosingAmount, &i.ExpectedClosing, &i.Variance, &i.VarianceNote,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashDrawerAccounts = `-- name: ListCashDrawerAccounts :many
SELECT id, name, account_number, balance
FROM accounts
WHERE is_cash_drawer
ORDER BY account_number NULLS LAST, name
`

type ListCashDrawerAccountsRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	Balance       int64       `json:"balance"`
}

func (q *Queries) ListCashDrawerAccounts(ctx context.Context) ([]*ListCashDrawerAccountsRow, error) {
	rows, err := q.db.Query(ctx, listCashDrawerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCashDrawerAccountsRow
	for rows.Next() {
		var i ListCashDrawerAccountsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AccountNumber, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountCashDrawer = `-- name: SetAccountCashDrawer :exec
UPDATE accounts SET is_cash_drawer = $1 WHERE id = $2
`

type SetAccountCashDrawerParams struct {
	IsCashDrawer bool        `json:"is_cash_drawer"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetAccountCashDrawer(ctx context.Context, arg *SetAccountCashDrawerParams) error {
	_, err := q.db.Exec(ctx, setAccountCashDrawer, arg.IsCashDrawer, arg.ID)
	return err
}

const setCashDayClosing = `-- name: SetCashDayClosing :one
UPDATE cash_day_counts
SET closing_amount = $1, closing_by = $2, closing_at = now(),
    expected_closing = $3, variance = $4, variance_note = $5,
    cash_sales = $6, cash_in = $7, cash_out = $8, cash_expenses = $9
WHERE branch_id = $10 AND count_date = $11
RETURNING id, branch_id, count_date, opening_amount, opening_by, opening_at,
          closing_amount, closing_by, closing_at, expected_closing, variance,
          variance_note, cash_sales, cash_in, cash_out, cash_expenses, created_at
`

type SetCashDayClosingParams struct {
	ClosingAmount   pgtype.Int8 `json:"closing_amount"`
	ClosingBy       pgtype.UUID `json:"closing_by"`
	ExpectedClosing pgtype.Int8 `json:"expected_closing"`
	Variance        pgtype.Int8 `json:"variance"`
	VarianceNote    string      `json:"variance_note"`
	CashSales       int64       `json:"cash_sales"`
	CashIn          int64       `json:"cash_in"`
	CashOut         int64       `json:"cash_out"`
	CashExpenses    int64       `json:"cash_expenses"`
	BranchID        pgtype.UUID `json:"branch_id"`
	CountDate       pgtype.Date `json:"count_date"`
}

func (q *Queries) SetCashDayClosing(ctx context.Context, arg *SetCashDayClosingParams) (*CashDayCount, error) {
	row := q.db.QueryRow(ctx, setCashDayClosing,
		arg.ClosingAmount,
		arg.ClosingBy,
		arg.ExpectedClosing,
		arg.Variance,
		arg.VarianceNote,
		arg.CashSales,
		arg.CashIn,
		arg.CashOut,
		arg.CashExpenses,
		arg.BranchID,
		arg.CountDate,
	)
	var i CashDayCount
	err := row.Scan(
		&i.ID, &i.BranchID, &i.CountDate,
		&i.OpeningAmount, &i.OpeningBy, &i.OpeningAt,
		&i.ClosingAmount, &i.ClosingBy, &i.ClosingAt,
		&i.ExpectedClosing, &i.Variance, &i.VarianceNote,
		&i.CashSales, &i.CashIn, &i.CashOut, &i.CashExpenses, &i.CreatedAt,
	)
	return &i, err
}

const sumCashDrawerMovementsForDay = `-- name: SumCashDrawerMovementsForDay :one
SELECT
    COALESCE(SUM(cd.amount) FILTER (WHERE ta.is_cash_drawer), 0)::bigint AS cash_in,
    COALESCE(SUM(cd.amount) FILTER (WHERE fa.is_cash_drawer), 0)::bigint AS cash_out
FROM cash_deposits cd
LEFT JOIN accounts fa ON fa.id = cd.from_account_id
LEFT JOIN accounts ta ON ta.id = cd.to_account_id
WHERE cd.date = $2 AND cd.status = 'posted'
  AND cd.branch_id = $1
  AND (fa.is_cash_drawer OR ta.is_cash_drawer)
`

type SumCashDrawerMovementsForDayParams struct {
	BranchID pgtype.UUID `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
}

type SumCashDrawerMovementsForDayRow struct {
	CashIn  int64 `json:"cash_in"`
	CashOut int64 `json:"cash_out"`
}

func (q *Queries) SumCashDrawerMovementsForDay(ctx context.Context, arg *SumCashDrawerMovementsForDayParams) (*SumCashDrawerMovementsForDayRow, error) {
	row := q.db.QueryRow(ctx, sumCashDrawerMovementsForDay, arg.BranchID, arg.Date)
	var i SumCashDrawerMovementsForDayRow
	err := row.Scan(&i.CashIn, &i.CashOut)
	return &i, err
}

const sumCashInvoicesForBranchDay = `-- name: SumCashInvoicesForBranchDay :one
SELECT COALESCE(SUM(i.amount_paid), 0)::bigint AS total
FROM invoices i
JOIN accounts a ON a.id = i.account_id
WHERE a.is_cash_drawer
  AND i.branch_id = $1
  AND COALESCE(i.payment_date, i.date) = $2
  AND i.payment_status IN ('paid', 'partial')
`

type SumCashInvoicesForBranchDayParams struct {
	BranchID pgtype.UUID `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) SumCashInvoicesForBranchDay(ctx context.Context, arg *SumCashInvoicesForBranchDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumCashInvoicesForBranchDay, arg.BranchID, arg.Date)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertCashDayOpening = `-- name: UpsertCashDayOpening :one
INSERT INTO cash_day_counts (id, branch_id, count_date, opening_amount, opening_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (branch_id, count_date) DO UPDATE
SET opening_amount = EXCLUDED.opening_amount,
    opening_by     = EXCLUDED.opening_by,
    opening_at     = now(),
    closing_amount = NULL,
    closing_by     = NULL,
    closing_at     = NULL,
    expected_closing = NULL,
    variance         = NULL,
    variance_note    = ''
RETURNING id, branch_id, count_date, opening_amount, opening_by, opening_at,
          closing_amount, closing_by, closing_at, expected_closing, variance,
          variance_note, cash_sales, cash_in, cash_out, cash_expenses, created_at
`

type UpsertCashDayOpeningParams struct {
	BranchID      pgtype.UUID `json:"branch_id"`
	CountDate     pgtype.Date `json:"count_date"`
	OpeningAmount int64       `json:"opening_amount"`
	OpeningBy     pgtype.UUID `json:"opening_by"`
}

func (q *Queries) UpsertCashDayOpening(ctx context.Context, arg *UpsertCashDayOpeningParams) (*CashDayCount, error) {
	row := q.db.QueryRow(ctx, upsertCashDayOpening,
		arg.BranchID,
		arg.CountDate,
		arg.OpeningAmount,
		arg.OpeningBy,
	)
	var i CashDayCount
	err := row.Scan(
		&i.ID, &i.BranchID, &i.CountDate,
		&i.OpeningAmount, &i.OpeningBy, &i.OpeningAt,
		&i.ClosingAmount, &i.ClosingBy, &i.ClosingAt,
		&i.ExpectedClosing, &i.Variance, &i.VarianceNote,
		&i.CashSales, &i.CashIn, &i.CashOut, &i.CashExpenses, &i.CreatedAt,
	)
	return &i, err
}
