// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_purchase_templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDailyPurchaseTemplate = `-- name: CreateDailyPurchaseTemplate :one
INSERT INTO daily_purchase_templates (
    id, name, branch_id, division_id, warehouse_id, vendor_id,
    expense_category_id, notes, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, branch_id, division_id, warehouse_id, vendor_id,
          expense_category_id, notes, created_by, created_at
`

type CreateDailyPurchaseTemplateParams struct {
	Name              string      `json:"name"`
	BranchID          pgtype.UUID `json:"branch_id"`
	DivisionID        pgtype.UUID `json:"division_id"`
	WarehouseID       pgtype.UUID `json:"warehouse_id"`
	VendorID          pgtype.UUID `json:"vendor_id"`
	ExpenseCategoryID pgtype.UUID `json:"expense_category_id"`
	Notes             string      `json:"notes"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDailyPurchaseTemplate(ctx context.Context, arg *CreateDailyPurchaseTemplateParams) (*DailyPurchaseTemplate, error) {
	row := q.db.QueryRow(ctx, createDailyPurchaseTemplate,
		arg.Name,
		arg.BranchID,
		arg.DivisionID,
		arg.WarehouseID,
		arg.VendorID,
		arg.ExpenseCategoryID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i DailyPurchaseTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.DivisionID,
		&i.WarehouseID,
		&i.VendorID,
		&i.ExpenseCategoryID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createDailyPurchaseTemplateItem = `-- name: CreateDailyPurchaseTemplateItem :exec
INSERT INTO daily_purchase_template_items (id, template_id, item_id, description, unit_index, sort_order)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
`

type CreateDailyPurchaseTemplateItemParams struct {
	TemplateID  pgtype.UUID `json:"template_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Description string      `json:"description"`
	UnitIndex   int32       `json:"unit_index"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) CreateDailyPurchaseTemplateItem(ctx context.Context, arg *CreateDailyPurchaseTemplateItemParams) error {
	_, err := q.db.Exec(ctx, createDailyPurchaseTemplateItem,
		arg.TemplateID,
		arg.ItemID,
		arg.Description,
		arg.UnitIndex,
		arg.SortOrder,
	)
	return err
}

const deleteDailyPurchaseTemplate = `-- name: DeleteDailyPurchaseTemplate :exec
DELETE FROM daily_purchase_templates WHERE id = $1
`

func (q *Queries) DeleteDailyPurchaseTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDailyPurchaseTemplate, id)
	return err
}

const deleteDailyPurchaseTemplateItems = `-- name: DeleteDailyPurchaseTemplateItems :exec
DELETE FROM daily_purchase_template_items WHERE template_id = $1
`

func (q *Queries) DeleteDailyPurchaseTemplateItems(ctx context.Context, templateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDailyPurchaseTemplateItems, templateID)
	return err
}

const getDailyPurchaseTemplateItems = `-- name: GetDailyPurchaseTemplateItems :many
SELECT
    ti.id, ti.template_id, ti.item_id, ti.description, ti.unit_index, ti.sort_order,
    i.name AS item_name, i.code AS item_code, i.units AS item_units, i.is_stock
FROM daily_purchase_template_items ti
LEFT JOIN items i ON i.id = ti.item_id
WHERE ti.template_id = $1
ORDER BY ti.sort_order
`

type GetDailyPurchaseTemplateItemsRow struct {
	ID          pgtype.UUID `json:"id"`
	TemplateID  pgtype.UUID `json:"template_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Description string      `json:"description"`
	UnitIndex   int32       `json:"unit_index"`
	SortOrder   int32       `json:"sort_order"`
	ItemName    pgtype.Text `json:"item_name"`
	ItemCode    pgtype.Text `json:"item_code"`
	ItemUnits   []byte      `json:"item_units"`
	IsStock     pgtype.Bool `json:"is_stock"`
}

func (q *Queries) GetDailyPurchaseTemplateItems(ctx context.Context, templateID pgtype.UUID) ([]*GetDailyPurchaseTemplateItemsRow, error) {
	rows, err := q.db.Query(ctx, getDailyPurchaseTemplateItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetDailyPurchaseTemplateItemsRow
	for rows.Next() {
		var i GetDailyPurchaseTemplateItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ItemID,
			&i.Description,
			&i.UnitIndex,
			&i.SortOrder,
			&i.ItemName,
			&i.ItemCode,
			&i.ItemUnits,
			&i.IsStock,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyPurchaseTemplates = `-- name: ListDailyPurchaseTemplates :many
SELECT
    t.id, t.name, t.branch_id, t.division_id, t.warehouse_id, t.vendor_id,
    t.expense_category_id, t.notes, t.created_at,
    b.name AS branch_name, d.name AS division_name,
    w.name AS warehouse_name, v.name AS vendor_name,
    (SELECT COUNT(*) FROM daily_purchase_template_items ti WHERE ti.template_id = t.id)::int AS line_count
FROM daily_purchase_templates t
LEFT JOIN branches b   ON b.id = t.branch_id
LEFT JOIN divisions d  ON d.id = t.division_id
LEFT JOIN warehouses w ON w.id = t.warehouse_id
LEFT JOIN vendors v    ON v.id = t.vendor_id
ORDER BY t.name
`

type ListDailyPurchaseTemplatesRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	DivisionID        pgtype.UUID        `json:"division_id"`
	WarehouseID       pgtype.UUID        `json:"warehouse_id"`
	VendorID          pgtype.UUID        `json:"vendor_id"`
	ExpenseCategoryID pgtype.UUID        `json:"expense_category_id"`
	Notes             string             `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	BranchName        pgtype.Text        `json:"branch_name"`
	DivisionName      pgtype.Text        `json:"division_name"`
	WarehouseName     pgtype.Text        `json:"warehouse_name"`
	VendorName        pgtype.Text        `json:"vendor_name"`
	LineCount         int32              `json:"line_count"`
}

func (q *Queries) ListDailyPurchaseTemplates(ctx context.Context) ([]*ListDailyPurchaseTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listDailyPurchaseTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDailyPurchaseTemplatesRow
	for rows.Next() {
		var i ListDailyPurchaseTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BranchID,
			&i.DivisionID,
			&i.WarehouseID,
			&i.VendorID,
			&i.ExpenseCategoryID,
			&i.Notes,
			&i.CreatedAt,
			&i.BranchName,
			&i.DivisionName,
			&i.WarehouseName,
			&i.VendorName,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyPurchaseTemplate = `-- name: UpdateDailyPurchaseTemplate :one
UPDATE daily_purchase_templates
SET name = $1, branch_id = $2, division_id = $3, warehouse_id = $4,
    vendor_id = $5, expense_category_id = $6, notes = $7
WHERE id = $8
RETURNING id, name, branch_id, division_id, warehouse_id, vendor_id,
          expense_category_id, notes, created_by, created_at
`

type UpdateDailyPurchaseTemplateParams struct {
	Name              string      `json:"name"`
	BranchID          pgtype.UUID `json:"branch_id"`
	DivisionID        pgtype.UUID `json:"division_id"`
	WarehouseID       pgtype.UUID `json:"warehouse_id"`
	VendorID          pgtype.UUID `json:"vendor_id"`
	ExpenseCategoryID pgtype.UUID `json:"expense_category_id"`
	Notes             string      `json:"notes"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDailyPurchaseTemplate(ctx context.Context, arg *UpdateDailyPurchaseTemplateParams) (*DailyPurchaseTemplate, error) {
	row := q.db.QueryRow(ctx, updateDailyPurchaseTemplate,
		arg.Name,
		arg.BranchID,
		arg.DivisionID,
		arg.WarehouseID,
		arg.VendorID,
		arg.ExpenseCategoryID,
		arg.Notes,
		arg.ID,
	)
	var i DailyPurchaseTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.DivisionID,
		&i.WarehouseID,
		&i.VendorID,
		&i.ExpenseCategoryID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}
