// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_purchases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDailyPurchase = `-- name: CancelDailyPurchase :exec
UPDATE daily_purchases
SET status = 'cancelled', cancelled_by = $1, cancelled_at = now(), cancel_reason = $2
WHERE id = $3
`

type CancelDailyPurchaseParams struct {
	CancelledBy  pgtype.UUID `json:"cancelled_by"`
	CancelReason string      `json:"cancel_reason"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) CancelDailyPurchase(ctx context.Context, arg *CancelDailyPurchaseParams) error {
	_, err := q.db.Exec(ctx, cancelDailyPurchase, arg.CancelledBy, arg.CancelReason, arg.ID)
	return err
}

const createDailyPurchase = `-- name: CreateDailyPurchase :one
INSERT INTO daily_purchases (
    id, number, date, branch_id, division_id, warehouse_id, expense_category_id,
    petty_cash_account_id, vendor_id, notes, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, number, date, branch_id, division_id, warehouse_id, expense_category_id,
          petty_cash_account_id, vendor_id, total_amount, notes, photo_path, status,
          created_by, created_at, cancelled_by, cancelled_at, cancel_reason
`

type CreateDailyPurchaseParams struct {
	Number             string      `json:"number"`
	Date               pgtype.Date `json:"date"`
	BranchID           pgtype.UUID `json:"branch_id"`
	DivisionID         pgtype.UUID `json:"division_id"`
	WarehouseID        pgtype.UUID `json:"warehouse_id"`
	ExpenseCategoryID  pgtype.UUID `json:"expense_category_id"`
	PettyCashAccountID pgtype.UUID `json:"petty_cash_account_id"`
	VendorID           pgtype.UUID `json:"vendor_id"`
	Notes              string      `json:"notes"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDailyPurchase(ctx context.Context, arg *CreateDailyPurchaseParams) (*DailyPurchase, error) {
	row := q.db.QueryRow(ctx, createDailyPurchase,
		arg.Number,
		arg.Date,
		arg.BranchID,
		arg.DivisionID,
		arg.WarehouseID,
		arg.ExpenseCategoryID,
		arg.PettyCashAccountID,
		arg.VendorID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i DailyPurchase
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Date,
		&i.BranchID,
		&i.DivisionID,
		&i.WarehouseID,
		&i.ExpenseCategoryID,
		&i.PettyCashAccountID,
		&i.VendorID,
		&i.TotalAmount,
		&i.Notes,
		&i.PhotoPath,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return &i, err
}

const createDailyPurchaseItem = `-- name: CreateDailyPurchaseItem :exec
INSERT INTO daily_purchase_items (
    id, purchase_id, item_id, description, quantity, unit_index, price, conversion_factor
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
`

type CreateDailyPurchaseItemParams struct {
	PurchaseID       pgtype.UUID    `json:"purchase_id"`
	ItemID           pgtype.UUID    `json:"item_id"`
	Description      string         `json:"description"`
	Quantity         pgtype.Numeric `json:"quantity"`
	UnitIndex        pgtype.Int4    `json:"unit_index"`
	Price            int64          `json:"price"`
	ConversionFactor pgtype.Numeric `json:"conversion_factor"`
}

func (q *Queries) CreateDailyPurchaseItem(ctx context.Context, arg *CreateDailyPurchaseItemParams) error {
	_, err := q.db.Exec(ctx, createDailyPurchaseItem,
		arg.PurchaseID,
		arg.ItemID,
		arg.Description,
		arg.Quantity,
		arg.UnitIndex,
		arg.Price,
		arg.ConversionFactor,
	)
	return err
}

const getDailyPurchaseByID = `-- name: GetDailyPurchaseByID :one
SELECT
    dp.id, dp.number, dp.date, dp.total_amount, dp.status, dp.notes, dp.photo_path,
    dp.branch_id, b.name AS branch_name,
    dp.division_id, d.name AS division_name,
    dp.warehouse_id, w.name AS warehouse_name,
    dp.expense_category_id, ec.name AS expense_category_name,
    dp.vendor_id, v.name AS vendor_name,
    dp.petty_cash_account_id, pa.name AS petty_cash_account_name,
    dp.created_at, u.username AS created_by_name,
    dp.cancelled_at, cu.username AS cancelled_by_name, dp.cancel_reason
FROM daily_purchases dp
JOIN branches b                 ON b.id = dp.branch_id
LEFT JOIN divisions d           ON d.id = dp.division_id
LEFT JOIN warehouses w          ON w.id = dp.warehouse_id
LEFT JOIN expense_categories ec ON ec.id = dp.expense_category_id
LEFT JOIN vendors v             ON v.id = dp.vendor_id
LEFT JOIN accounts pa           ON pa.id = dp.petty_cash_account_id
LEFT JOIN users u               ON u.id = dp.created_by
LEFT JOIN users cu              ON cu.id = dp.cancelled_by
WHERE dp.id = $1
`

type GetDailyPurchaseByIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Number               string             `json:"number"`
	Date                 pgtype.Date        `json:"date"`
	TotalAmount          int64              `json:"total_amount"`
	Status               string             `json:"status"`
	Notes                string             `json:"notes"`
	PhotoPath            pgtype.Text        `json:"photo_path"`
	BranchID             pgtype.UUID        `json:"branch_id"`
	BranchName           string             `json:"branch_name"`
	DivisionID           pgtype.UUID        `json:"division_id"`
	DivisionName         pgtype.Text        `json:"division_name"`
	WarehouseID          pgtype.UUID        `json:"warehouse_id"`
	WarehouseName        pgtype.Text        `json:"warehouse_name"`
	ExpenseCategoryID    pgtype.UUID        `json:"expense_category_id"`
	ExpenseCategoryName  pgtype.Text        `json:"expense_category_name"`
	VendorID             pgtype.UUID        `json:"vendor_id"`
	VendorName           pgtype.Text        `json:"vendor_name"`
	PettyCashAccountID   pgtype.UUID        `json:"petty_cash_account_id"`
	PettyCashAccountName pgtype.Text        `json:"petty_cash_account_name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedByName        pgtype.Text        `json:"created_by_name"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
	CancelledByName      pgtype.Text        `json:"cancelled_by_name"`
	CancelReason         string             `json:"cancel_reason"`
}

func (q *Queries) GetDailyPurchaseByID(ctx context.Context, id pgtype.UUID) (*GetDailyPurchaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getDailyPurchaseByID, id)
	var i GetDailyPurchaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Date,
		&i.TotalAmount,
		&i.Status,
		&i.Notes,
		&i.PhotoPath,
		&i.BranchID,
		&i.BranchName,
		&i.DivisionID,
		&i.DivisionName,
		&i.WarehouseID,
		&i.WarehouseName,
		&i.ExpenseCategoryID,
		&i.ExpenseCategoryName,
		&i.VendorID,
		&i.VendorName,
		&i.PettyCashAccountID,
		&i.PettyCashAccountName,
		&i.CreatedAt,
		&i.CreatedByName,
		&i.CancelledAt,
		&i.CancelledByName,
		&i.CancelReason,
	)
	return &i, err
}

const getDailyPurchaseItems = `-- name: GetDailyPurchaseItems :many
SELECT
    i.id, i.purchase_id, i.item_id, i.description, i.quantity, i.unit_index,
    i.price, i.conversion_factor,
    it.name AS item_name, it.code AS item_code, it.is_stock, it.units AS item_units
FROM daily_purchase_items i
LEFT JOIN items it ON it.id = i.item_id
WHERE i.purchase_id = $1
ORDER BY i.id
`

type GetDailyPurchaseItemsRow struct {
	ID               pgtype.UUID    `json:"id"`
	PurchaseID       pgtype.UUID    `json:"purchase_id"`
	ItemID           pgtype.UUID    `json:"item_id"`
	Description      string         `json:"description"`
	Quantity         pgtype.Numeric `json:"quantity"`
	UnitIndex        pgtype.Int4    `json:"unit_index"`
	Price            int64          `json:"price"`
	ConversionFactor pgtype.Numeric `json:"conversion_factor"`
	ItemName         pgtype.Text    `json:"item_name"`
	ItemCode         pgtype.Text    `json:"item_code"`
	IsStock          pgtype.Bool    `json:"is_stock"`
	ItemUnits        []byte         `json:"item_units"`
}

func (q *Queries) GetDailyPurchaseItems(ctx context.Context, purchaseID pgtype.UUID) ([]*GetDailyPurchaseItemsRow, error) {
	rows, err := q.db.Query(ctx, getDailyPurchaseItems, purchaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetDailyPurchaseItemsRow
	for rows.Next() {
		var i GetDailyPurchaseItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseID,
			&i.ItemID,
			&i.Description,
			&i.Quantity,
			&i.UnitIndex,
			&i.Price,
			&i.ConversionFactor,
			&i.ItemName,
			&i.ItemCode,
			&i.IsStock,
			&i.ItemUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyPurchaseRow = `-- name: GetDailyPurchaseRow :one
SELECT id, number, date, branch_id, division_id, warehouse_id, expense_category_id,
       petty_cash_account_id, vendor_id, total_amount, notes, photo_path, status,
       created_by, created_at, cancelled_by, cancelled_at, cancel_reason
FROM daily_purchases WHERE id = $1
`

func (q *Queries) GetDailyPurchaseRow(ctx context.Context, id pgtype.UUID) (*DailyPurchase, error) {
	row := q.db.QueryRow(ctx, getDailyPurchaseRow, id)
	var i DailyPurchase
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Date,
		&i.BranchID,
		&i.DivisionID,
		&i.WarehouseID,
		&i.ExpenseCategoryID,
		&i.PettyCashAccountID,
		&i.VendorID,
		&i.TotalAmount,
		&i.Notes,
		&i.PhotoPath,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return &i, err
}

const listDailyPurchases = `-- name: ListDailyPurchases :many
SELECT
    dp.id, dp.number, dp.date, dp.total_amount, dp.status, dp.notes, dp.photo_path,
    dp.branch_id, b.name AS branch_name,
    dp.division_id, d.name AS division_name,
    dp.warehouse_id, w.name AS warehouse_name,
    dp.vendor_id, v.name AS vendor_name,
    dp.petty_cash_account_id, pa.name AS petty_cash_account_name,
    dp.created_at, u.username AS created_by_name,
    (SELECT COUNT(*) FROM daily_purchase_items i WHERE i.purchase_id = dp.id)::int AS line_count
FROM daily_purchases dp
JOIN branches b            ON b.id = dp.branch_id
LEFT JOIN divisions d      ON d.id = dp.division_id
LEFT JOIN warehouses w     ON w.id = dp.warehouse_id
LEFT JOIN vendors v        ON v.id = dp.vendor_id
LEFT JOIN accounts pa      ON pa.id = dp.petty_cash_account_id
LEFT JOIN users u          ON u.id = dp.created_by
WHERE ($1::uuid IS NULL OR dp.branch_id = $1)
  AND ($2::date IS NULL OR dp.date >= $2)
  AND ($3::date IS NULL OR dp.date <= $3)
  AND ($4::text IS NULL OR dp.status = $4)
ORDER BY dp.date DESC, dp.created_at DESC
`

type ListDailyPurchasesParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Column4 pgtype.Text `json:"column_4"`
}

type ListDailyPurchasesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Number               string             `json:"number"`
	Date                 pgtype.Date        `json:"date"`
	TotalAmount          int64              `json:"total_amount"`
	Status               string             `json:"status"`
	Notes                string             `json:"notes"`
	PhotoPath            pgtype.Text        `json:"photo_path"`
	BranchID             pgtype.UUID        `json:"branch_id"`
	BranchName           string             `json:"branch_name"`
	DivisionID           pgtype.UUID        `json:"division_id"`
	DivisionName         pgtype.Text        `json:"division_name"`
	WarehouseID          pgtype.UUID        `json:"warehouse_id"`
	WarehouseName        pgtype.Text        `json:"warehouse_name"`
	VendorID             pgtype.UUID        `json:"vendor_id"`
	VendorName           pgtype.Text        `json:"vendor_name"`
	PettyCashAccountID   pgtype.UUID        `json:"petty_cash_account_id"`
	PettyCashAccountName pgtype.Text        `json:"petty_cash_account_name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedByName        pgtype.Text        `json:"created_by_name"`
	LineCount            int32              `json:"line_count"`
}

func (q *Queries) ListDailyPurchases(ctx context.Context, arg *ListDailyPurchasesParams) ([]*ListDailyPurchasesRow, error) {
	rows, err := q.db.Query(ctx, listDailyPurchases,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDailyPurchasesRow
	for rows.Next() {
		var i ListDailyPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Date,
			&i.TotalAmount,
			&i.Status,
			&i.Notes,
			&i.PhotoPath,
			&i.BranchID,
			&i.BranchName,
			&i.DivisionID,
			&i.DivisionName,
			&i.WarehouseID,
			&i.WarehouseName,
			&i.VendorID,
			&i.VendorName,
			&i.PettyCashAccountID,
			&i.PettyCashAccountName,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyPurchasesForDay = `-- name: ListDailyPurchasesForDay :many
SELECT id, number, total_amount, notes, status
FROM daily_purchases
WHERE branch_id = $1 AND date = $2
ORDER BY created_at
`

type ListDailyPurchasesForDayParams struct {
	BranchID pgtype.UUID `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
}

type ListDailyPurchasesForDayRow struct {
	ID          pgtype.UUID `json:"id"`
	Number      string      `json:"number"`
	TotalAmount int64       `json:"total_amount"`
	Notes       string      `json:"notes"`
	Status      string      `json:"status"`
}

func (q *Queries) ListDailyPurchasesForDay(ctx context.Context, arg *ListDailyPurchasesForDayParams) ([]*ListDailyPurchasesForDayRow, error) {
	rows, err := q.db.Query(ctx, listDailyPurchasesForDay, arg.BranchID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDailyPurchasesForDayRow
	for rows.Next() {
		var i ListDailyPurchasesForDayRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.TotalAmount,
			&i.Notes,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDailyPurchaseNumber = `-- name: NextDailyPurchaseNumber :one
SELECT 'PH-' || LPAD(nextval('daily_purchase_number_seq')::text, 6, '0') AS number
`

func (q *Queries) NextDailyPurchaseNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextDailyPurchaseNumber)
	var number string
	err := row.Scan(&number)
	return number, err
}

const setDailyPurchasePhoto = `-- name: SetDailyPurchasePhoto :exec
UPDATE daily_purchases SET photo_path = $1 WHERE id = $2
`

type SetDailyPurchasePhotoParams struct {
	PhotoPath pgtype.Text `json:"photo_path"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetDailyPurchasePhoto(ctx context.Context, arg *SetDailyPurchasePhotoParams) error {
	_, err := q.db.Exec(ctx, setDailyPurchasePhoto, arg.PhotoPath, arg.ID)
	return err
}

const setDailyPurchaseTotal = `-- name: SetDailyPurchaseTotal :exec
UPDATE daily_purchases SET total_amount = $1 WHERE id = $2
`

type SetDailyPurchaseTotalParams struct {
	TotalAmount int64       `json:"total_amount"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) SetDailyPurchaseTotal(ctx context.Context, arg *SetDailyPurchaseTotalParams) error {
	_, err := q.db.Exec(ctx, setDailyPurchaseTotal, arg.TotalAmount, arg.ID)
	return err
}

const sumDailyPurchasesForDay = `-- name: SumDailyPurchasesForDay :one
SELECT COALESCE(SUM(total_amount), 0)::bigint AS total,
       COUNT(*)::int AS count
FROM daily_purchases
WHERE branch_id = $1 AND date = $2 AND status = 'posted'
`

type SumDailyPurchasesForDayParams struct {
	BranchID pgtype.UUID `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
}

type SumDailyPurchasesForDayRow struct {
	Total int64 `json:"total"`
	Count int32 `json:"count"`
}

func (q *Queries) SumDailyPurchasesForDay(ctx context.Context, arg *SumDailyPurchasesForDayParams) (*SumDailyPurchasesForDayRow, error) {
	row := q.db.QueryRow(ctx, sumDailyPurchasesForDay, arg.BranchID, arg.Date)
	var i SumDailyPurchasesForDayRow
	err := row.Scan(&i.Total, &i.Count)
	return &i, err
}
