// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDispatchByID = `-- name: GetDispatchByID :one
SELECT
    d.id, d.branch_id, d.division_id, d.warehouse_id,
    d.notes, d.dispatched_at,
    b.name AS branch_name,
    dv.name AS division_name,
    w.name AS warehouse_name,
    u.username AS dispatched_by_name
FROM dispatches d
JOIN branches b ON b.id = d.branch_id
LEFT JOIN divisions dv ON dv.id = d.division_id
JOIN warehouses w ON w.id = d.warehouse_id
LEFT JOIN users u ON u.id = d.dispatched_by
WHERE d.id = $1
`

type GetDispatchByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	DivisionID       pgtype.UUID        `json:"division_id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	Notes            pgtype.Text        `json:"notes"`
	DispatchedAt     pgtype.Timestamptz `json:"dispatched_at"`
	BranchName       string             `json:"branch_name"`
	DivisionName     pgtype.Text        `json:"division_name"`
	WarehouseName    string             `json:"warehouse_name"`
	DispatchedByName pgtype.Text        `json:"dispatched_by_name"`
}

func (q *Queries) GetDispatchByID(ctx context.Context, id pgtype.UUID) (*GetDispatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getDispatchByID, id)
	var i GetDispatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DivisionID,
		&i.WarehouseID,
		&i.Notes,
		&i.DispatchedAt,
		&i.BranchName,
		&i.DivisionName,
		&i.WarehouseName,
		&i.DispatchedByName,
	)
	return &i, err
}

const getDispatchItems = `-- name: GetDispatchItems :many
SELECT
    di.id, di.dispatch_id, di.item_id, di.quantity, di.unit_index, di.unit_name,
    i.name AS item_name, i.code AS item_code, i.units AS item_units
FROM dispatch_items di
JOIN items i ON i.id = di.item_id
WHERE di.dispatch_id = $1
ORDER BY i.name
`

type GetDispatchItemsRow struct {
	ID         pgtype.UUID    `json:"id"`
	DispatchID pgtype.UUID    `json:"dispatch_id"`
	ItemID     pgtype.UUID    `json:"item_id"`
	Quantity   pgtype.Numeric `json:"quantity"`
	UnitIndex  int32          `json:"unit_index"`
	UnitName   string         `json:"unit_name"`
	ItemName   string         `json:"item_name"`
	ItemCode   pgtype.Text    `json:"item_code"`
	ItemUnits  []byte         `json:"item_units"`
}

func (q *Queries) GetDispatchItems(ctx context.Context, dispatchID pgtype.UUID) ([]*GetDispatchItemsRow, error) {
	rows, err := q.db.Query(ctx, getDispatchItems, dispatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetDispatchItemsRow
	for rows.Next() {
		var i GetDispatchItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DispatchID,
			&i.ItemID,
			&i.Quantity,
			&i.UnitIndex,
			&i.UnitName,
			&i.ItemName,
			&i.ItemCode,
			&i.ItemUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDispatch = `-- name: InsertDispatch :one
INSERT INTO dispatches (id, branch_id, division_id, warehouse_id, notes, dispatched_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, dispatched_at
`

type InsertDispatchParams struct {
	BranchID     pgtype.UUID `json:"branch_id"`
	DivisionID   pgtype.UUID `json:"division_id"`
	WarehouseID  pgtype.UUID `json:"warehouse_id"`
	Notes        pgtype.Text `json:"notes"`
	DispatchedBy pgtype.UUID `json:"dispatched_by"`
}

type InsertDispatchRow struct {
	ID           pgtype.UUID        `json:"id"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

func (q *Queries) InsertDispatch(ctx context.Context, arg *InsertDispatchParams) (*InsertDispatchRow, error) {
	row := q.db.QueryRow(ctx, insertDispatch,
		arg.BranchID,
		arg.DivisionID,
		arg.WarehouseID,
		arg.Notes,
		arg.DispatchedBy,
	)
	var i InsertDispatchRow
	err := row.Scan(&i.ID, &i.DispatchedAt)
	return &i, err
}

const insertDispatchItem = `-- name: InsertDispatchItem :exec
INSERT INTO dispatch_items (id, dispatch_id, item_id, quantity, unit_index, unit_name)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
`

type InsertDispatchItemParams struct {
	DispatchID pgtype.UUID    `json:"dispatch_id"`
	ItemID     pgtype.UUID    `json:"item_id"`
	Quantity   pgtype.Numeric `json:"quantity"`
	UnitIndex  int32          `json:"unit_index"`
	UnitName   string         `json:"unit_name"`
}

func (q *Queries) InsertDispatchItem(ctx context.Context, arg *InsertDispatchItemParams) error {
	_, err := q.db.Exec(ctx, insertDispatchItem,
		arg.DispatchID,
		arg.ItemID,
		arg.Quantity,
		arg.UnitIndex,
		arg.UnitName,
	)
	return err
}

const listDispatches = `-- name: ListDispatches :many
SELECT
    d.id, d.branch_id, d.division_id, d.warehouse_id,
    d.notes, d.dispatched_at,
    b.name AS branch_name,
    dv.name AS division_name,
    w.name AS warehouse_name,
    u.username AS dispatched_by_name
FROM dispatches d
JOIN branches b ON b.id = d.branch_id
LEFT JOIN divisions dv ON dv.id = d.division_id
JOIN warehouses w ON w.id = d.warehouse_id
LEFT JOIN users u ON u.id = d.dispatched_by
WHERE ($1::date IS NULL OR d.dispatched_at::date >= $1)
  AND ($2::date IS NULL OR d.dispatched_at::date <= $2)
ORDER BY d.dispatched_at DESC
`

type ListDispatchesParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListDispatchesRow struct {
	ID               pgtype.UUID        `json:"id"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	DivisionID       pgtype.UUID        `json:"division_id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	Notes            pgtype.Text        `json:"notes"`
	DispatchedAt     pgtype.Timestamptz `json:"dispatched_at"`
	BranchName       string             `json:"branch_name"`
	DivisionName     pgtype.Text        `json:"division_name"`
	WarehouseName    string             `json:"warehouse_name"`
	DispatchedByName pgtype.Text        `json:"dispatched_by_name"`
}

func (q *Queries) ListDispatches(ctx context.Context, arg *ListDispatchesParams) ([]*ListDispatchesRow, error) {
	rows, err := q.db.Query(ctx, listDispatches, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDispatchesRow
	for rows.Next() {
		var i ListDispatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.DivisionID,
			&i.WarehouseID,
			&i.Notes,
			&i.DispatchedAt,
			&i.BranchName,
			&i.DivisionName,
			&i.WarehouseName,
			&i.DispatchedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
