// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: divisions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDivision = `-- name: CreateDivision :one
INSERT INTO divisions (id, branch_id, name, revenue_account_id, expense_account_id, discount_account_id)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, branch_id, name, revenue_account_id, expense_account_id, discount_account_id, created_at
`

type CreateDivisionParams struct {
	BranchID          pgtype.UUID `json:"branch_id"`
	Name              string      `json:"name"`
	RevenueAccountID  pgtype.UUID `json:"revenue_account_id"`
	ExpenseAccountID  pgtype.UUID `json:"expense_account_id"`
	DiscountAccountID pgtype.UUID `json:"discount_account_id"`
}

func (q *Queries) CreateDivision(ctx context.Context, arg *CreateDivisionParams) (*Division, error) {
	row := q.db.QueryRow(ctx, createDivision,
		arg.BranchID,
		arg.Name,
		arg.RevenueAccountID,
		arg.ExpenseAccountID,
		arg.DiscountAccountID,
	)
	var i Division
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.RevenueAccountID,
		&i.ExpenseAccountID,
		&i.DiscountAccountID,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteDivision = `-- name: DeleteDivision :exec
DELETE FROM divisions WHERE id = $1
`

func (q *Queries) DeleteDivision(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDivision, id)
	return err
}

const getDivisionByID = `-- name: GetDivisionByID :one
SELECT
    d.id, d.name, d.branch_id, d.created_at,
    b.name AS branch_name,
    d.revenue_account_id, ra.name AS revenue_account_name,
    d.expense_account_id, ea.name AS expense_account_name,
    d.discount_account_id, da.name AS discount_account_name
FROM divisions d
JOIN branches b ON b.id = d.branch_id
LEFT JOIN accounts ra ON ra.id = d.revenue_account_id
LEFT JOIN accounts ea ON ea.id = d.expense_account_id
LEFT JOIN accounts da ON da.id = d.discount_account_id
WHERE d.id = $1
`

type GetDivisionByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	BranchID            pgtype.UUID        `json:"branch_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	BranchName          string             `json:"branch_name"`
	RevenueAccountID    pgtype.UUID        `json:"revenue_account_id"`
	RevenueAccountName  pgtype.Text        `json:"revenue_account_name"`
	ExpenseAccountID    pgtype.UUID        `json:"expense_account_id"`
	ExpenseAccountName  pgtype.Text        `json:"expense_account_name"`
	DiscountAccountID   pgtype.UUID        `json:"discount_account_id"`
	DiscountAccountName pgtype.Text        `json:"discount_account_name"`
}

func (q *Queries) GetDivisionByID(ctx context.Context, id pgtype.UUID) (*GetDivisionByIDRow, error) {
	row := q.db.QueryRow(ctx, getDivisionByID, id)
	var i GetDivisionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.CreatedAt,
		&i.BranchName,
		&i.RevenueAccountID,
		&i.RevenueAccountName,
		&i.ExpenseAccountID,
		&i.ExpenseAccountName,
		&i.DiscountAccountID,
		&i.DiscountAccountName,
	)
	return &i, err
}

const getDivisionExpenseAccountID = `-- name: GetDivisionExpenseAccountID :one
SELECT expense_account_id FROM divisions WHERE id = $1
`

func (q *Queries) GetDivisionExpenseAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDivisionExpenseAccountID, id)
	var expense_account_id pgtype.UUID
	err := row.Scan(&expense_account_id)
	return expense_account_id, err
}

const getDivisionRevenueAccountID = `-- name: GetDivisionRevenueAccountID :one
SELECT revenue_account_id FROM divisions WHERE id = $1
`

func (q *Queries) GetDivisionRevenueAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDivisionRevenueAccountID, id)
	var revenue_account_id pgtype.UUID
	err := row.Scan(&revenue_account_id)
	return revenue_account_id, err
}

const listDivisions = `-- name: ListDivisions :many
SELECT
    d.id, d.name, d.branch_id, d.created_at,
    b.name AS branch_name,
    d.revenue_account_id, ra.name AS revenue_account_name,
    d.expense_account_id, ea.name AS expense_account_name,
    d.discount_account_id, da.name AS discount_account_name
FROM divisions d
JOIN branches b ON b.id = d.branch_id
LEFT JOIN accounts ra ON ra.id = d.revenue_account_id
LEFT JOIN accounts ea ON ea.id = d.expense_account_id
LEFT JOIN accounts da ON da.id = d.discount_account_id
WHERE ($1::uuid IS NULL OR d.branch_id = $1)
ORDER BY b.name, d.name
`

type ListDivisionsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	BranchID            pgtype.UUID        `json:"branch_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	BranchName          string             `json:"branch_name"`
	RevenueAccountID    pgtype.UUID        `json:"revenue_account_id"`
	RevenueAccountName  pgtype.Text        `json:"revenue_account_name"`
	ExpenseAccountID    pgtype.UUID        `json:"expense_account_id"`
	ExpenseAccountName  pgtype.Text        `json:"expense_account_name"`
	DiscountAccountID   pgtype.UUID        `json:"discount_account_id"`
	DiscountAccountName pgtype.Text        `json:"discount_account_name"`
}

func (q *Queries) ListDivisions(ctx context.Context, dollar_1 pgtype.UUID) ([]*ListDivisionsRow, error) {
	rows, err := q.db.Query(ctx, listDivisions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDivisionsRow
	for rows.Next() {
		var i ListDivisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BranchID,
			&i.CreatedAt,
			&i.BranchName,
			&i.RevenueAccountID,
			&i.RevenueAccountName,
			&i.ExpenseAccountID,
			&i.ExpenseAccountName,
			&i.DiscountAccountID,
			&i.DiscountAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDivision = `-- name: UpdateDivision :one
UPDATE divisions SET name = $1 WHERE id = $2
RETURNING id, branch_id, name, revenue_account_id, expense_account_id, discount_account_id, created_at
`

type UpdateDivisionParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDivision(ctx context.Context, arg *UpdateDivisionParams) (*Division, error) {
	row := q.db.QueryRow(ctx, updateDivision, arg.Name, arg.ID)
	var i Division
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.RevenueAccountID,
		&i.ExpenseAccountID,
		&i.DiscountAccountID,
		&i.CreatedAt,
	)
	return &i, err
}
