// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enumerations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnumeration = `-- name: DeleteEnumeration :exec
DELETE FROM enumerations WHERE id = $1
`

func (q *Queries) DeleteEnumeration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnumeration, id)
	return err
}

const getEnumerationByID = `-- name: GetEnumerationByID :one
SELECT
    e.id, e.warehouse_id, e.source_item_id, e.output_item_id,
    e.source_qty, e.source_unit_idx, e.output_qty, e.output_unit_idx,
    e.transferred_value, e.date, e.notes, e.created_at,
    w.name AS warehouse_name,
    si.name AS source_item_name, si.units AS source_item_units,
    oi.name AS output_item_name, oi.units AS output_item_units
FROM enumerations e
JOIN warehouses w ON w.id = e.warehouse_id
JOIN items si ON si.id = e.source_item_id
JOIN items oi ON oi.id = e.output_item_id
WHERE e.id = $1
`

type GetEnumerationByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	SourceItemID     pgtype.UUID        `json:"source_item_id"`
	OutputItemID     pgtype.UUID        `json:"output_item_id"`
	SourceQty        pgtype.Numeric     `json:"source_qty"`
	SourceUnitIdx    int32              `json:"source_unit_idx"`
	OutputQty        pgtype.Numeric     `json:"output_qty"`
	OutputUnitIdx    int32              `json:"output_unit_idx"`
	TransferredValue int64              `json:"transferred_value"`
	Date             pgtype.Date        `json:"date"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	WarehouseName    string             `json:"warehouse_name"`
	SourceItemName   string             `json:"source_item_name"`
	SourceItemUnits  []byte             `json:"source_item_units"`
	OutputItemName   string             `json:"output_item_name"`
	OutputItemUnits  []byte             `json:"output_item_units"`
}

func (q *Queries) GetEnumerationByID(ctx context.Context, id pgtype.UUID) (*GetEnumerationByIDRow, error) {
	row := q.db.QueryRow(ctx, getEnumerationByID, id)
	var i GetEnumerationByIDRow
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.SourceItemID,
		&i.OutputItemID,
		&i.SourceQty,
		&i.SourceUnitIdx,
		&i.OutputQty,
		&i.OutputUnitIdx,
		&i.TransferredValue,
		&i.Date,
		&i.Notes,
		&i.CreatedAt,
		&i.WarehouseName,
		&i.SourceItemName,
		&i.SourceItemUnits,
		&i.OutputItemName,
		&i.OutputItemUnits,
	)
	return &i, err
}

const insertEnumeration = `-- name: InsertEnumeration :one
INSERT INTO enumerations (
    id, warehouse_id, source_item_id, output_item_id,
    source_qty, source_unit_idx, output_qty, output_unit_idx,
    transferred_value, date, notes, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at
`

type InsertEnumerationParams struct {
	WarehouseID      pgtype.UUID    `json:"warehouse_id"`
	SourceItemID     pgtype.UUID    `json:"source_item_id"`
	OutputItemID     pgtype.UUID    `json:"output_item_id"`
	SourceQty        pgtype.Numeric `json:"source_qty"`
	SourceUnitIdx    int32          `json:"source_unit_idx"`
	OutputQty        pgtype.Numeric `json:"output_qty"`
	OutputUnitIdx    int32          `json:"output_unit_idx"`
	TransferredValue int64          `json:"transferred_value"`
	Date             pgtype.Date    `json:"date"`
	Notes            pgtype.Text    `json:"notes"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

type InsertEnumerationRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertEnumeration(ctx context.Context, arg *InsertEnumerationParams) (*InsertEnumerationRow, error) {
	row := q.db.QueryRow(ctx, insertEnumeration,
		arg.WarehouseID,
		arg.SourceItemID,
		arg.OutputItemID,
		arg.SourceQty,
		arg.SourceUnitIdx,
		arg.OutputQty,
		arg.OutputUnitIdx,
		arg.TransferredValue,
		arg.Date,
		arg.Notes,
		arg.CreatedBy,
	)
	var i InsertEnumerationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const listEnumerations = `-- name: ListEnumerations :many
SELECT
    e.id, e.warehouse_id, e.source_item_id, e.output_item_id,
    e.source_qty, e.source_unit_idx, e.output_qty, e.output_unit_idx,
    e.transferred_value, e.date, e.notes, e.created_at,
    w.name AS warehouse_name,
    si.name AS source_item_name,
    oi.name AS output_item_name,
    u.username AS created_by_name
FROM enumerations e
JOIN warehouses w ON w.id = e.warehouse_id
JOIN items si ON si.id = e.source_item_id
JOIN items oi ON oi.id = e.output_item_id
LEFT JOIN users u ON u.id = e.created_by
WHERE ($1::uuid IS NULL OR e.warehouse_id = $1)
  AND ($2::date IS NULL OR e.date >= $2)
  AND ($3::date IS NULL OR e.date <= $3)
ORDER BY e.date DESC, e.created_at DESC
`

type ListEnumerationsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

type ListEnumerationsRow struct {
	ID               pgtype.UUID        `json:"id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	SourceItemID     pgtype.UUID        `json:"source_item_id"`
	OutputItemID     pgtype.UUID        `json:"output_item_id"`
	SourceQty        pgtype.Numeric     `json:"source_qty"`
	SourceUnitIdx    int32              `json:"source_unit_idx"`
	OutputQty        pgtype.Numeric     `json:"output_qty"`
	OutputUnitIdx    int32              `json:"output_unit_idx"`
	TransferredValue int64              `json:"transferred_value"`
	Date             pgtype.Date        `json:"date"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	WarehouseName    string             `json:"warehouse_name"`
	SourceItemName   string             `json:"source_item_name"`
	OutputItemName   string             `json:"output_item_name"`
	CreatedByName    pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListEnumerations(ctx context.Context, arg *ListEnumerationsParams) ([]*ListEnumerationsRow, error) {
	rows, err := q.db.Query(ctx, listEnumerations, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListEnumerationsRow
	for rows.Next() {
		var i ListEnumerationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.SourceItemID,
			&i.OutputItemID,
			&i.SourceQty,
			&i.SourceUnitIdx,
			&i.OutputQty,
			&i.OutputUnitIdx,
			&i.TransferredValue,
			&i.Date,
			&i.Notes,
			&i.CreatedAt,
			&i.WarehouseName,
			&i.SourceItemName,
			&i.OutputItemName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
