// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJournalLinesForAccount = `-- name: CountJournalLinesForAccount :one
SELECT COUNT(*) FROM journal_lines WHERE account_id = $1
`

func (q *Queries) CountJournalLinesForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalLinesForAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (id, division_id, name, account_id)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, division_id, name, account_id, created_at
`

type CreateExpenseCategoryParams struct {
	DivisionID pgtype.UUID `json:"division_id"`
	Name       string      `json:"name"`
	AccountID  pgtype.UUID `json:"account_id"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg *CreateExpenseCategoryParams) (*ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.DivisionID, arg.Name, arg.AccountID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.DivisionID,
		&i.Name,
		&i.AccountID,
		&i.CreatedAt,
	)
	return &i, err
}

const createExpenseCategoryAccount = `-- name: CreateExpenseCategoryAccount :one
INSERT INTO accounts (id, name, account_number, account_type, parent_id, balance, is_system)
VALUES (gen_random_uuid(), $1, $2, 'expense', $3, 0, false)
RETURNING id
`

type CreateExpenseCategoryAccountParams struct {
	Name          string      `json:"name"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	ParentID      pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateExpenseCategoryAccount(ctx context.Context, arg *CreateExpenseCategoryAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createExpenseCategoryAccount, arg.Name, arg.AccountNumber, arg.ParentID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories WHERE id = $1
`

func (q *Queries) DeleteExpenseCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, id)
	return err
}

const getDivisionExpenseParent = `-- name: GetDivisionExpenseParent :one
SELECT d.expense_account_id, d.name AS division_name, b.name AS branch_name
FROM divisions d
JOIN branches b ON b.id = d.branch_id
WHERE d.id = $1
`

type GetDivisionExpenseParentRow struct {
	ExpenseAccountID pgtype.UUID `json:"expense_account_id"`
	DivisionName     string      `json:"division_name"`
	BranchName       string      `json:"branch_name"`
}

func (q *Queries) GetDivisionExpenseParent(ctx context.Context, id pgtype.UUID) (*GetDivisionExpenseParentRow, error) {
	row := q.db.QueryRow(ctx, getDivisionExpenseParent, id)
	var i GetDivisionExpenseParentRow
	err := row.Scan(&i.ExpenseAccountID, &i.DivisionName, &i.BranchName)
	return &i, err
}

const getExpenseCategoryByID = `-- name: GetExpenseCategoryByID :one
SELECT
    ec.id, ec.division_id, ec.name, ec.account_id, ec.created_at,
    a.account_number, a.balance AS account_balance,
    d.name AS division_name,
    b.name AS branch_name
FROM expense_categories ec
JOIN accounts a ON a.id = ec.account_id
JOIN divisions d ON d.id = ec.division_id
JOIN branches b ON b.id = d.branch_id
WHERE ec.id = $1
`

type ExpenseCategoryRow struct {
	ID             pgtype.UUID        `json:"id"`
	DivisionID     pgtype.UUID        `json:"division_id"`
	Name           string             `json:"name"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AccountNumber  pgtype.Int4        `json:"account_number"`
	AccountBalance int64              `json:"account_balance"`
	DivisionName   string             `json:"division_name"`
	BranchName     string             `json:"branch_name"`
}

func (q *Queries) GetExpenseCategoryByID(ctx context.Context, id pgtype.UUID) (*ExpenseCategoryRow, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByID, id)
	var i ExpenseCategoryRow
	err := row.Scan(
		&i.ID,
		&i.DivisionID,
		&i.Name,
		&i.AccountID,
		&i.CreatedAt,
		&i.AccountNumber,
		&i.AccountBalance,
		&i.DivisionName,
		&i.BranchName,
	)
	return &i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT
    ec.id, ec.division_id, ec.name, ec.account_id, ec.created_at,
    a.account_number, a.balance AS account_balance,
    d.name AS division_name,
    b.name AS branch_name
FROM expense_categories ec
JOIN accounts a ON a.id = ec.account_id
JOIN divisions d ON d.id = ec.division_id
JOIN branches b ON b.id = d.branch_id
WHERE ($1::uuid IS NULL OR ec.division_id = $1)
ORDER BY b.name, d.name, ec.name
`

func (q *Queries) ListExpenseCategories(ctx context.Context, divisionID pgtype.UUID) ([]*ExpenseCategoryRow, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, divisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ExpenseCategoryRow
	for rows.Next() {
		var i ExpenseCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.DivisionID,
			&i.Name,
			&i.AccountID,
			&i.CreatedAt,
			&i.AccountNumber,
			&i.AccountBalance,
			&i.DivisionName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
