// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendanceDevice = `-- name: CreateAttendanceDevice :one
INSERT INTO attendance_devices (id, name, branch_id, api_key_hash, is_active)
VALUES (gen_random_uuid(), $1, $2, $3, true)
RETURNING id, name, branch_id, api_key_hash, is_active, created_at
`

type CreateAttendanceDeviceParams struct {
	Name       string      `json:"name"`
	BranchID   pgtype.UUID `json:"branch_id"`
	ApiKeyHash string      `json:"api_key_hash"`
}

func (q *Queries) CreateAttendanceDevice(ctx context.Context, arg *CreateAttendanceDeviceParams) (*AttendanceDevice, error) {
	row := q.db.QueryRow(ctx, createAttendanceDevice, arg.Name, arg.BranchID, arg.ApiKeyHash)
	var i AttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.ApiKeyHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const createFingerprintImport = `-- name: CreateFingerprintImport :one

INSERT INTO fingerprint_imports (id, filename, imported_by, row_count, matched_count)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, filename, imported_by, row_count, matched_count, created_at
`

type CreateFingerprintImportParams struct {
	Filename     pgtype.Text `json:"filename"`
	ImportedBy   pgtype.UUID `json:"imported_by"`
	RowCount     pgtype.Int4 `json:"row_count"`
	MatchedCount pgtype.Int4 `json:"matched_count"`
}

// ── Fingerprint imports ─────────────────────────────────────────────────────
func (q *Queries) CreateFingerprintImport(ctx context.Context, arg *CreateFingerprintImportParams) (*FingerprintImport, error) {
	row := q.db.QueryRow(ctx, createFingerprintImport,
		arg.Filename,
		arg.ImportedBy,
		arg.RowCount,
		arg.MatchedCount,
	)
	var i FingerprintImport
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ImportedBy,
		&i.RowCount,
		&i.MatchedCount,
		&i.CreatedAt,
	)
	return &i, err
}

const createPublicHoliday = `-- name: CreatePublicHoliday :one
INSERT INTO public_holidays (id, date, name)
VALUES (gen_random_uuid(), $1, $2)
RETURNING id, date, name
`

type CreatePublicHolidayParams struct {
	Date pgtype.Date `json:"date"`
	Name string      `json:"name"`
}

func (q *Queries) CreatePublicHoliday(ctx context.Context, arg *CreatePublicHolidayParams) (*PublicHoliday, error) {
	row := q.db.QueryRow(ctx, createPublicHoliday, arg.Date, arg.Name)
	var i PublicHoliday
	err := row.Scan(&i.ID, &i.Date, &i.Name)
	return &i, err
}

const deleteAttendanceDevice = `-- name: DeleteAttendanceDevice :exec
DELETE FROM attendance_devices WHERE id = $1
`

func (q *Queries) DeleteAttendanceDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttendanceDevice, id)
	return err
}

const deletePublicHoliday = `-- name: DeletePublicHoliday :exec
DELETE FROM public_holidays WHERE id = $1
`

func (q *Queries) DeletePublicHoliday(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePublicHoliday, id)
	return err
}

const deleteWorkSchedule = `-- name: DeleteWorkSchedule :exec
DELETE FROM work_schedules WHERE id = $1
`

func (q *Queries) DeleteWorkSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkSchedule, id)
	return err
}

const getActiveDeviceByKeyHash = `-- name: GetActiveDeviceByKeyHash :one
SELECT id, name, branch_id, api_key_hash, is_active, created_at
FROM attendance_devices
WHERE api_key_hash = $1 AND is_active = true
`

func (q *Queries) GetActiveDeviceByKeyHash(ctx context.Context, apiKeyHash string) (*AttendanceDevice, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceByKeyHash, apiKeyHash)
	var i AttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.ApiKeyHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const getAttendanceRecordByEmployeeDate = `-- name: GetAttendanceRecordByEmployeeDate :one

SELECT id, employee_id, date, check_in, check_out, check_in_source, check_out_source,
       check_in_photo_path, device_id, status, is_late, late_minutes,
       is_early_leave, early_leave_minutes, is_missing_checkout, note
FROM attendance_records
WHERE employee_id = $1 AND date = $2
`

type GetAttendanceRecordByEmployeeDateParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

// ── Attendance records ──────────────────────────────────────────────────────
func (q *Queries) GetAttendanceRecordByEmployeeDate(ctx context.Context, arg *GetAttendanceRecordByEmployeeDateParams) (*AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, getAttendanceRecordByEmployeeDate, arg.EmployeeID, arg.Date)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.CheckInSource,
		&i.CheckOutSource,
		&i.CheckInPhotoPath,
		&i.DeviceID,
		&i.Status,
		&i.IsLate,
		&i.LateMinutes,
		&i.IsEarlyLeave,
		&i.EarlyLeaveMinutes,
		&i.IsMissingCheckout,
		&i.Note,
	)
	return &i, err
}

const getAttendanceRecordByID = `-- name: GetAttendanceRecordByID :one
SELECT id, employee_id, date, check_in, check_out, check_in_source, check_out_source,
       check_in_photo_path, device_id, status, is_late, late_minutes,
       is_early_leave, early_leave_minutes, is_missing_checkout, note,
       is_half_day, half_day_lost_minutes
FROM attendance_records
WHERE id = $1
`

func (q *Queries) GetAttendanceRecordByID(ctx context.Context, id pgtype.UUID) (*AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, getAttendanceRecordByID, id)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.CheckInSource,
		&i.CheckOutSource,
		&i.CheckInPhotoPath,
		&i.DeviceID,
		&i.Status,
		&i.IsLate,
		&i.LateMinutes,
		&i.IsEarlyLeave,
		&i.EarlyLeaveMinutes,
		&i.IsMissingCheckout,
		&i.Note,
		&i.IsHalfDay,
		&i.HalfDayLostMinutes,
	)
	return &i, err
}

const getEmployeeByCode = `-- name: GetEmployeeByCode :one

SELECT id, employee_code, full_name, branch_id, status, photo_path
FROM employees
WHERE employee_code = $1
`

type GetEmployeeByCodeRow struct {
	ID           pgtype.UUID `json:"id"`
	EmployeeCode string      `json:"employee_code"`
	FullName     string      `json:"full_name"`
	BranchID     pgtype.UUID `json:"branch_id"`
	Status       string      `json:"status"`
	PhotoPath    pgtype.Text `json:"photo_path"`
}

// ── Employees lookup (device + reconcile) ───────────────────────────────────
func (q *Queries) GetEmployeeByCode(ctx context.Context, employeeCode string) (*GetEmployeeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByCode, employeeCode)
	var i GetEmployeeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.FullName,
		&i.BranchID,
		&i.Status,
		&i.PhotoPath,
	)
	return &i, err
}

const getWorkScheduleByBranch = `-- name: GetWorkScheduleByBranch :one
SELECT id, branch_id, work_start, work_end, grace_minutes, early_leave_minutes, work_days
FROM work_schedules
WHERE branch_id = $1
`

func (q *Queries) GetWorkScheduleByBranch(ctx context.Context, branchID pgtype.UUID) (*WorkSchedule, error) {
	row := q.db.QueryRow(ctx, getWorkScheduleByBranch, branchID)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.WorkStart,
		&i.WorkEnd,
		&i.GraceMinutes,
		&i.EarlyLeaveMinutes,
		&i.WorkDays,
	)
	return &i, err
}

const insertAbsentRecord = `-- name: InsertAbsentRecord :exec
INSERT INTO attendance_records (id, employee_id, date, status)
VALUES (gen_random_uuid(), $1, $2, 'absent')
ON CONFLICT (employee_id, date) DO NOTHING
`

type InsertAbsentRecordParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) InsertAbsentRecord(ctx context.Context, arg *InsertAbsentRecordParams) error {
	_, err := q.db.Exec(ctx, insertAbsentRecord, arg.EmployeeID, arg.Date)
	return err
}

const insertAttendanceRecord = `-- name: InsertAttendanceRecord :one
INSERT INTO attendance_records (
    id, employee_id, date, check_in, check_out, check_in_source, check_out_source,
    check_in_photo_path, device_id, status, is_late, late_minutes,
    is_early_leave, early_leave_minutes, is_missing_checkout, note
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id, employee_id, date, check_in, check_out, check_in_source, check_out_source,
          check_in_photo_path, device_id, status, is_late, late_minutes,
          is_early_leave, early_leave_minutes, is_missing_checkout, note
`

type InsertAttendanceRecordParams struct {
	EmployeeID        pgtype.UUID        `json:"employee_id"`
	Date              pgtype.Date        `json:"date"`
	CheckIn           pgtype.Timestamptz `json:"check_in"`
	CheckOut          pgtype.Timestamptz `json:"check_out"`
	CheckInSource     pgtype.Text        `json:"check_in_source"`
	CheckOutSource    pgtype.Text        `json:"check_out_source"`
	CheckInPhotoPath  pgtype.Text        `json:"check_in_photo_path"`
	DeviceID          pgtype.UUID        `json:"device_id"`
	Status            string             `json:"status"`
	IsLate            bool               `json:"is_late"`
	LateMinutes       int32              `json:"late_minutes"`
	IsEarlyLeave      bool               `json:"is_early_leave"`
	EarlyLeaveMinutes int32              `json:"early_leave_minutes"`
	IsMissingCheckout bool               `json:"is_missing_checkout"`
	Note              pgtype.Text        `json:"note"`
}

func (q *Queries) InsertAttendanceRecord(ctx context.Context, arg *InsertAttendanceRecordParams) (*AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, insertAttendanceRecord,
		arg.EmployeeID,
		arg.Date,
		arg.CheckIn,
		arg.CheckOut,
		arg.CheckInSource,
		arg.CheckOutSource,
		arg.CheckInPhotoPath,
		arg.DeviceID,
		arg.Status,
		arg.IsLate,
		arg.LateMinutes,
		arg.IsEarlyLeave,
		arg.EarlyLeaveMinutes,
		arg.IsMissingCheckout,
		arg.Note,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.CheckInSource,
		&i.CheckOutSource,
		&i.CheckInPhotoPath,
		&i.DeviceID,
		&i.Status,
		&i.IsLate,
		&i.LateMinutes,
		&i.IsEarlyLeave,
		&i.EarlyLeaveMinutes,
		&i.IsMissingCheckout,
		&i.Note,
	)
	return &i, err
}

const isPublicHoliday = `-- name: IsPublicHoliday :one
SELECT EXISTS (SELECT 1 FROM public_holidays WHERE date = $1) AS exists
`

func (q *Queries) IsPublicHoliday(ctx context.Context, date pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, isPublicHoliday, date)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveEmployeesForReconcile = `-- name: ListActiveEmployeesForReconcile :many
SELECT id, employee_code, full_name, branch_id
FROM employees
WHERE status = 'active'
`

type ListActiveEmployeesForReconcileRow struct {
	ID           pgtype.UUID `json:"id"`
	EmployeeCode string      `json:"employee_code"`
	FullName     string      `json:"full_name"`
	BranchID     pgtype.UUID `json:"branch_id"`
}

func (q *Queries) ListActiveEmployeesForReconcile(ctx context.Context) ([]*ListActiveEmployeesForReconcileRow, error) {
	rows, err := q.db.Query(ctx, listActiveEmployeesForReconcile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActiveEmployeesForReconcileRow
	for rows.Next() {
		var i ListActiveEmployeesForReconcileRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.FullName,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceDevices = `-- name: ListAttendanceDevices :many

SELECT d.id, d.name, d.branch_id, d.api_key_hash, d.is_active, d.created_at,
       b.name AS branch_name
FROM attendance_devices d
LEFT JOIN branches b ON b.id = d.branch_id
ORDER BY d.created_at DESC
`

type ListAttendanceDevicesRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	BranchID   pgtype.UUID        `json:"branch_id"`
	ApiKeyHash string             `json:"api_key_hash"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	BranchName pgtype.Text        `json:"branch_name"`
}

// ── Attendance devices ──────────────────────────────────────────────────────
func (q *Queries) ListAttendanceDevices(ctx context.Context) ([]*ListAttendanceDevicesRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAttendanceDevicesRow
	for rows.Next() {
		var i ListAttendanceDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BranchID,
			&i.ApiKeyHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceRosterByBranch = `-- name: ListDeviceRosterByBranch :many
SELECT employee_code, full_name, photo_path
FROM employees
WHERE branch_id = $1 AND status = 'active'
ORDER BY full_name
`

type ListDeviceRosterByBranchRow struct {
	EmployeeCode string      `json:"employee_code"`
	FullName     string      `json:"full_name"`
	PhotoPath    pgtype.Text `json:"photo_path"`
}

func (q *Queries) ListDeviceRosterByBranch(ctx context.Context, branchID pgtype.UUID) ([]*ListDeviceRosterByBranchRow, error) {
	rows, err := q.db.Query(ctx, listDeviceRosterByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDeviceRosterByBranchRow
	for rows.Next() {
		var i ListDeviceRosterByBranchRow
		if err := rows.Scan(&i.EmployeeCode, &i.FullName, &i.PhotoPath); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentAttendanceForEmployeeRange = `-- name: ListPresentAttendanceForEmployeeRange :many
SELECT employee_id, date, check_in, check_out
FROM attendance_records
WHERE employee_id = $1 AND date >= $2 AND date <= $3 AND status = 'present'
`

type ListPresentAttendanceForEmployeeRangeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

type ListPresentAttendanceForEmployeeRangeRow struct {
	EmployeeID pgtype.UUID        `json:"employee_id"`
	Date       pgtype.Date        `json:"date"`
	CheckIn    pgtype.Timestamptz `json:"check_in"`
	CheckOut   pgtype.Timestamptz `json:"check_out"`
}

// Present-day check-outs for an employee within a date range, used to derive
// automatic overtime hours at payroll generation (checkout time vs schedule
// work_end, computed in Go via service.ComputeOvertimeMinutes).
func (q *Queries) ListPresentAttendanceForEmployeeRange(ctx context.Context, arg *ListPresentAttendanceForEmployeeRangeParams) ([]*ListPresentAttendanceForEmployeeRangeRow, error) {
	rows, err := q.db.Query(ctx, listPresentAttendanceForEmployeeRange, arg.EmployeeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPresentAttendanceForEmployeeRangeRow
	for rows.Next() {
		var i ListPresentAttendanceForEmployeeRangeRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Date,
			&i.CheckIn,
			&i.CheckOut,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicHolidays = `-- name: ListPublicHolidays :many

SELECT id, date, name
FROM public_holidays
ORDER BY date DESC
`

// ── Public holidays ─────────────────────────────────────────────────────────
func (q *Queries) ListPublicHolidays(ctx context.Context) ([]*PublicHoliday, error) {
	rows, err := q.db.Query(ctx, listPublicHolidays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PublicHoliday
	for rows.Next() {
		var i PublicHoliday
		if err := rows.Scan(&i.ID, &i.Date, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkSchedules = `-- name: ListWorkSchedules :many

SELECT id, branch_id, work_start, work_end, grace_minutes, early_leave_minutes, work_days
FROM work_schedules
ORDER BY branch_id
`

// ── Work schedules ──────────────────────────────────────────────────────────
func (q *Queries) ListWorkSchedules(ctx context.Context) ([]*WorkSchedule, error) {
	rows, err := q.db.Query(ctx, listWorkSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkSchedule
	for rows.Next() {
		var i WorkSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.WorkStart,
			&i.WorkEnd,
			&i.GraceMinutes,
			&i.EarlyLeaveMinutes,
			&i.WorkDays,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAttendanceDeviceActive = `-- name: SetAttendanceDeviceActive :one
UPDATE attendance_devices
SET is_active = $1
WHERE id = $2
RETURNING id, name, branch_id, api_key_hash, is_active, created_at
`

type SetAttendanceDeviceActiveParams struct {
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetAttendanceDeviceActive(ctx context.Context, arg *SetAttendanceDeviceActiveParams) (*AttendanceDevice, error) {
	row := q.db.QueryRow(ctx, setAttendanceDeviceActive, arg.IsActive, arg.ID)
	var i AttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.ApiKeyHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const updateAttendanceRecord = `-- name: UpdateAttendanceRecord :one
UPDATE attendance_records SET
    check_in = $1,
    check_out = $2,
    check_in_source = $3,
    check_out_source = $4,
    check_in_photo_path = $5,
    device_id = $6,
    status = $7,
    is_late = $8,
    late_minutes = $9,
    is_early_leave = $10,
    early_leave_minutes = $11,
    is_missing_checkout = $12,
    note = $13,
    is_half_day = $14,
    half_day_lost_minutes = $15
WHERE id = $16
RETURNING id, employee_id, date, check_in, check_out, check_in_source, check_out_source,
          check_in_photo_path, device_id, status, is_late, late_minutes,
          is_early_leave, early_leave_minutes, is_missing_checkout, note,
          is_half_day, half_day_lost_minutes
`

type UpdateAttendanceRecordParams struct {
	CheckIn            pgtype.Timestamptz `json:"check_in"`
	CheckOut           pgtype.Timestamptz `json:"check_out"`
	CheckInSource      pgtype.Text        `json:"check_in_source"`
	CheckOutSource     pgtype.Text        `json:"check_out_source"`
	CheckInPhotoPath   pgtype.Text        `json:"check_in_photo_path"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	Status             string             `json:"status"`
	IsLate             bool               `json:"is_late"`
	LateMinutes        int32              `json:"late_minutes"`
	IsEarlyLeave       bool               `json:"is_early_leave"`
	EarlyLeaveMinutes  int32              `json:"early_leave_minutes"`
	IsMissingCheckout  bool               `json:"is_missing_checkout"`
	Note               pgtype.Text        `json:"note"`
	IsHalfDay          bool               `json:"is_half_day"`
	HalfDayLostMinutes int32              `json:"half_day_lost_minutes"`
	ID                 pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateAttendanceRecord(ctx context.Context, arg *UpdateAttendanceRecordParams) (*AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, updateAttendanceRecord,
		arg.CheckIn,
		arg.CheckOut,
		arg.CheckInSource,
		arg.CheckOutSource,
		arg.CheckInPhotoPath,
		arg.DeviceID,
		arg.Status,
		arg.IsLate,
		arg.LateMinutes,
		arg.IsEarlyLeave,
		arg.EarlyLeaveMinutes,
		arg.IsMissingCheckout,
		arg.Note,
		arg.IsHalfDay,
		arg.HalfDayLostMinutes,
		arg.ID,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.CheckInSource,
		&i.CheckOutSource,
		&i.CheckInPhotoPath,
		&i.DeviceID,
		&i.Status,
		&i.IsLate,
		&i.LateMinutes,
		&i.IsEarlyLeave,
		&i.EarlyLeaveMinutes,
		&i.IsMissingCheckout,
		&i.Note,
		&i.IsHalfDay,
		&i.HalfDayLostMinutes,
	)
	return &i, err
}

const upsertWorkSchedule = `-- name: UpsertWorkSchedule :one
INSERT INTO work_schedules (id, branch_id, work_start, work_end, grace_minutes, early_leave_minutes, work_days)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6)
ON CONFLICT (branch_id) DO UPDATE SET
    work_start = EXCLUDED.work_start,
    work_end = EXCLUDED.work_end,
    grace_minutes = EXCLUDED.grace_minutes,
    early_leave_minutes = EXCLUDED.early_leave_minutes,
    work_days = EXCLUDED.work_days
RETURNING id, branch_id, work_start, work_end, grace_minutes, early_leave_minutes, work_days
`

type UpsertWorkScheduleParams struct {
	BranchID          pgtype.UUID `json:"branch_id"`
	WorkStart         pgtype.Time `json:"work_start"`
	WorkEnd           pgtype.Time `json:"work_end"`
	GraceMinutes      int32       `json:"grace_minutes"`
	EarlyLeaveMinutes int32       `json:"early_leave_minutes"`
	WorkDays          []int32     `json:"work_days"`
}

func (q *Queries) UpsertWorkSchedule(ctx context.Context, arg *UpsertWorkScheduleParams) (*WorkSchedule, error) {
	row := q.db.QueryRow(ctx, upsertWorkSchedule,
		arg.BranchID,
		arg.WorkStart,
		arg.WorkEnd,
		arg.GraceMinutes,
		arg.EarlyLeaveMinutes,
		arg.WorkDays,
	)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.WorkStart,
		&i.WorkEnd,
		&i.GraceMinutes,
		&i.EarlyLeaveMinutes,
		&i.WorkDays,
	)
	return &i, err
}
