// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployeesByPosition = `-- name: CountEmployeesByPosition :one
SELECT COUNT(*) FROM employees WHERE position_id = $1
`

func (q *Queries) CountEmployeesByPosition(ctx context.Context, positionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByPosition, positionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    id, employee_code, full_name, dob, join_date,
    position_id, branch_id, phone, email, address, national_id,
    bank_name, bank_account_number, bank_account_holder,
    user_id, status
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15
)
RETURNING id
`

type CreateEmployeeParams struct {
	EmployeeCode      string      `json:"employee_code"`
	FullName          string      `json:"full_name"`
	Dob               pgtype.Date `json:"dob"`
	JoinDate          pgtype.Date `json:"join_date"`
	PositionID        pgtype.UUID `json:"position_id"`
	BranchID          pgtype.UUID `json:"branch_id"`
	Phone             pgtype.Text `json:"phone"`
	Email             pgtype.Text `json:"email"`
	Address           pgtype.Text `json:"address"`
	NationalID        pgtype.Text `json:"national_id"`
	BankName          pgtype.Text `json:"bank_name"`
	BankAccountNumber pgtype.Text `json:"bank_account_number"`
	BankAccountHolder pgtype.Text `json:"bank_account_holder"`
	UserID            pgtype.UUID `json:"user_id"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg *CreateEmployeeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.EmployeeCode,
		arg.FullName,
		arg.Dob,
		arg.JoinDate,
		arg.PositionID,
		arg.BranchID,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.NationalID,
		arg.BankName,
		arg.BankAccountNumber,
		arg.BankAccountHolder,
		arg.UserID,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (id, name, is_active)
VALUES (gen_random_uuid(), $1, $2)
RETURNING id, name, is_active, created_at
`

type CreatePositionParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg *CreatePositionParams) (*Position, error) {
	row := q.db.QueryRow(ctx, createPosition, arg.Name, arg.IsActive)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE id = $1
`

func (q *Queries) DeletePosition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePosition, id)
	return err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT
    e.id, e.employee_code, e.full_name, e.dob, e.join_date,
    e.position_id, p.name AS position_name,
    e.branch_id, b.name AS branch_name,
    e.phone, e.email, e.address, e.national_id,
    e.bank_name, e.bank_account_number, e.bank_account_holder,
    e.photo_path, e.user_id, e.status,
    e.created_at, e.updated_at
FROM employees e
JOIN positions p ON p.id = e.position_id
JOIN branches  b ON b.id = e.branch_id
WHERE e.id = $1
`

type GetEmployeeByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	EmployeeCode      string             `json:"employee_code"`
	FullName          string             `json:"full_name"`
	Dob               pgtype.Date        `json:"dob"`
	JoinDate          pgtype.Date        `json:"join_date"`
	PositionID        pgtype.UUID        `json:"position_id"`
	PositionName      string             `json:"position_name"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	BranchName        string             `json:"branch_name"`
	Phone             pgtype.Text        `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	Address           pgtype.Text        `json:"address"`
	NationalID        pgtype.Text        `json:"national_id"`
	BankName          pgtype.Text        `json:"bank_name"`
	BankAccountNumber pgtype.Text        `json:"bank_account_number"`
	BankAccountHolder pgtype.Text        `json:"bank_account_holder"`
	PhotoPath         pgtype.Text        `json:"photo_path"`
	UserID            pgtype.UUID        `json:"user_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, id pgtype.UUID) (*GetEmployeeByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.FullName,
		&i.Dob,
		&i.JoinDate,
		&i.PositionID,
		&i.PositionName,
		&i.BranchID,
		&i.BranchName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NationalID,
		&i.BankName,
		&i.BankAccountNumber,
		&i.BankAccountHolder,
		&i.PhotoPath,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getEmployeePhotoPath = `-- name: GetEmployeePhotoPath :one
SELECT photo_path FROM employees WHERE id = $1
`

func (q *Queries) GetEmployeePhotoPath(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getEmployeePhotoPath, id)
	var photo_path pgtype.Text
	err := row.Scan(&photo_path)
	return photo_path, err
}

const getMaxEmployeeCodeSeq = `-- name: GetMaxEmployeeCodeSeq :one
SELECT COALESCE(MAX(CAST(SUBSTRING(employee_code FROM 5) AS INTEGER)), 0)::int AS max_seq
FROM employees
WHERE employee_code ~ '^EMP-[0-9]+$'
`

func (q *Queries) GetMaxEmployeeCodeSeq(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxEmployeeCodeSeq)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, name, is_active, created_at
FROM positions
WHERE id = $1
`

func (q *Queries) GetPositionByID(ctx context.Context, id pgtype.UUID) (*Position, error) {
	row := q.db.QueryRow(ctx, getPositionByID, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const listPositions = `-- name: ListPositions :many
SELECT id, name, is_active, created_at
FROM positions
ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context) ([]*Position, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees SET
    employee_code = $1,
    full_name = $2,
    dob = $3,
    join_date = $4,
    position_id = $5,
    branch_id = $6,
    phone = $7,
    email = $8,
    address = $9,
    national_id = $10,
    bank_name = $11,
    bank_account_number = $12,
    bank_account_holder = $13,
    user_id = $14,
    status = $15,
    updated_at = now()
WHERE id = $16
RETURNING id
`

type UpdateEmployeeParams struct {
	EmployeeCode      string      `json:"employee_code"`
	FullName          string      `json:"full_name"`
	Dob               pgtype.Date `json:"dob"`
	JoinDate          pgtype.Date `json:"join_date"`
	PositionID        pgtype.UUID `json:"position_id"`
	BranchID          pgtype.UUID `json:"branch_id"`
	Phone             pgtype.Text `json:"phone"`
	Email             pgtype.Text `json:"email"`
	Address           pgtype.Text `json:"address"`
	NationalID        pgtype.Text `json:"national_id"`
	BankName          pgtype.Text `json:"bank_name"`
	BankAccountNumber pgtype.Text `json:"bank_account_number"`
	BankAccountHolder pgtype.Text `json:"bank_account_holder"`
	UserID            pgtype.UUID `json:"user_id"`
	Status            string      `json:"status"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg *UpdateEmployeeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.EmployeeCode,
		arg.FullName,
		arg.Dob,
		arg.JoinDate,
		arg.PositionID,
		arg.BranchID,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.NationalID,
		arg.BankName,
		arg.BankAccountNumber,
		arg.BankAccountHolder,
		arg.UserID,
		arg.Status,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateEmployeePhotoPath = `-- name: UpdateEmployeePhotoPath :exec
UPDATE employees SET photo_path = $1, updated_at = now() WHERE id = $2
`

type UpdateEmployeePhotoPathParams struct {
	PhotoPath pgtype.Text `json:"photo_path"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateEmployeePhotoPath(ctx context.Context, arg *UpdateEmployeePhotoPathParams) error {
	_, err := q.db.Exec(ctx, updateEmployeePhotoPath, arg.PhotoPath, arg.ID)
	return err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET name = $1, is_active = $2
WHERE id = $3
RETURNING id, name, is_active, created_at
`

type UpdatePositionParams struct {
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg *UpdatePositionParams) (*Position, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.Name, arg.IsActive, arg.ID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}
