// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_kasbon.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveKasbon = `-- name: ApproveKasbon :one
UPDATE kasbons
SET status = 'approved', approved_by = $1, approved_at = now(), approval_note = $2
WHERE id = $3
RETURNING id, kasbon_number, employee_id, amount, details, sending_method,
          fund_source_account_id, request_date, resolution_month, status,
          approved_by, approved_at, approval_note, processed_by, processed_at,
          evidence_photo_path, created_by, created_at
`

type ApproveKasbonParams struct {
	ApprovedBy   pgtype.UUID `json:"approved_by"`
	ApprovalNote pgtype.Text `json:"approval_note"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) ApproveKasbon(ctx context.Context, arg *ApproveKasbonParams) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, approveKasbon, arg.ApprovedBy, arg.ApprovalNote, arg.ID)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const countInstallments = `-- name: CountInstallments :one
SELECT COUNT(*) FROM kasbon_installments
WHERE kasbon_id = $1
`

func (q *Queries) CountInstallments(ctx context.Context, kasbonID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInstallments, kasbonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingInstallments = `-- name: CountPendingInstallments :one
SELECT COUNT(*) FROM kasbon_installments
WHERE kasbon_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingInstallments(ctx context.Context, kasbonID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInstallments, kasbonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKasbon = `-- name: CreateKasbon :one
INSERT INTO kasbons (
    id, kasbon_number, employee_id, amount, details, sending_method,
    fund_source_account_id, request_date, resolution_month, status, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9)
RETURNING id, kasbon_number, employee_id, amount, details, sending_method,
          fund_source_account_id, request_date, resolution_month, status,
          approved_by, approved_at, approval_note, processed_by, processed_at,
          evidence_photo_path, created_by, created_at
`

type CreateKasbonParams struct {
	KasbonNumber        string      `json:"kasbon_number"`
	EmployeeID          pgtype.UUID `json:"employee_id"`
	Amount              int64       `json:"amount"`
	Details             string      `json:"details"`
	SendingMethod       string      `json:"sending_method"`
	FundSourceAccountID pgtype.UUID `json:"fund_source_account_id"`
	RequestDate         pgtype.Date `json:"request_date"`
	ResolutionMonth     pgtype.Date `json:"resolution_month"`
	CreatedBy           pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateKasbon(ctx context.Context, arg *CreateKasbonParams) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, createKasbon,
		arg.KasbonNumber,
		arg.EmployeeID,
		arg.Amount,
		arg.Details,
		arg.SendingMethod,
		arg.FundSourceAccountID,
		arg.RequestDate,
		arg.ResolutionMonth,
		arg.CreatedBy,
	)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createKasbonInstallment = `-- name: CreateKasbonInstallment :one
INSERT INTO kasbon_installments (id, kasbon_id, due_month, amount, status)
VALUES (gen_random_uuid(), $1, $2, $3, 'pending')
RETURNING id, kasbon_id, due_month, amount, payroll_line_id, status
`

type CreateKasbonInstallmentParams struct {
	KasbonID pgtype.UUID `json:"kasbon_id"`
	DueMonth pgtype.Date `json:"due_month"`
	Amount   int64       `json:"amount"`
}

func (q *Queries) CreateKasbonInstallment(ctx context.Context, arg *CreateKasbonInstallmentParams) (*KasbonInstallment, error) {
	row := q.db.QueryRow(ctx, createKasbonInstallment, arg.KasbonID, arg.DueMonth, arg.Amount)
	var i KasbonInstallment
	err := row.Scan(
		&i.ID,
		&i.KasbonID,
		&i.DueMonth,
		&i.Amount,
		&i.PayrollLineID,
		&i.Status,
	)
	return &i, err
}

const deleteKasbonInstallments = `-- name: DeleteKasbonInstallments :exec
DELETE FROM kasbon_installments WHERE kasbon_id = $1
`

func (q *Queries) DeleteKasbonInstallments(ctx context.Context, kasbonID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKasbonInstallments, kasbonID)
	return err
}

const getKasbonByID = `-- name: GetKasbonByID :one
SELECT id, kasbon_number, employee_id, amount, details, sending_method,
       fund_source_account_id, request_date, resolution_month, status,
       approved_by, approved_at, approval_note, processed_by, processed_at,
       evidence_photo_path, created_by, created_at
FROM kasbons
WHERE id = $1
`

func (q *Queries) GetKasbonByID(ctx context.Context, id pgtype.UUID) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, getKasbonByID, id)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getLastResolvedKasbon = `-- name: GetLastResolvedKasbon :one
SELECT id, kasbon_number, amount, request_date, resolution_month, processed_at
FROM kasbons
WHERE employee_id = $1 AND status = 'resolved'
ORDER BY COALESCE(processed_at, created_at) DESC
LIMIT 1
`

type GetLastResolvedKasbonRow struct {
	ID              pgtype.UUID        `json:"id"`
	KasbonNumber    string             `json:"kasbon_number"`
	Amount          int64              `json:"amount"`
	RequestDate     pgtype.Date        `json:"request_date"`
	ResolutionMonth pgtype.Date        `json:"resolution_month"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) GetLastResolvedKasbon(ctx context.Context, employeeID pgtype.UUID) (*GetLastResolvedKasbonRow, error) {
	row := q.db.QueryRow(ctx, getLastResolvedKasbon, employeeID)
	var i GetLastResolvedKasbonRow
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.Amount,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.ProcessedAt,
	)
	return &i, err
}

const getMaxKasbonSeqForYear = `-- name: GetMaxKasbonSeqForYear :one
SELECT COALESCE(MAX(CAST(SUBSTRING(kasbon_number FROM 10) AS INTEGER)), 0)::int AS max_seq
FROM kasbons
WHERE kasbon_number ~ ('^KSB-' || $1::text || '-[0-9]+$')
`

func (q *Queries) GetMaxKasbonSeqForYear(ctx context.Context, dollar_1 string) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxKasbonSeqForYear, dollar_1)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const listKasbonInstallments = `-- name: ListKasbonInstallments :many
SELECT id, kasbon_id, due_month, amount, payroll_line_id, status
FROM kasbon_installments
WHERE kasbon_id = $1
ORDER BY due_month
`

func (q *Queries) ListKasbonInstallments(ctx context.Context, kasbonID pgtype.UUID) ([]*KasbonInstallment, error) {
	rows, err := q.db.Query(ctx, listKasbonInstallments, kasbonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*KasbonInstallment
	for rows.Next() {
		var i KasbonInstallment
		if err := rows.Scan(
			&i.ID,
			&i.KasbonID,
			&i.DueMonth,
			&i.Amount,
			&i.PayrollLineID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKasbons = `-- name: ListKasbons :many
SELECT k.id, k.kasbon_number, k.employee_id, k.amount, k.details, k.sending_method,
       k.fund_source_account_id, k.request_date, k.resolution_month, k.status,
       k.approved_by, k.approved_at, k.approval_note, k.processed_by, k.processed_at,
       k.evidence_photo_path, k.created_by, k.created_at,
       e.full_name AS employee_name, e.employee_code,
       a.name AS fund_source_name
FROM kasbons k
JOIN employees e ON e.id = k.employee_id
JOIN accounts a ON a.id = k.fund_source_account_id
WHERE ($1::text = '' OR k.status = $1)
  AND ($2::uuid IS NULL OR k.employee_id = $2)
  AND ($3::text = '' OR lower(e.full_name) LIKE '%' || lower($3) || '%'
       OR lower(e.employee_code) LIKE '%' || lower($3) || '%'
       OR lower(k.kasbon_number) LIKE '%' || lower($3) || '%')
ORDER BY k.created_at DESC
`

type ListKasbonsParams struct {
	Status     string      `json:"status"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Q          string      `json:"q"`
}

type ListKasbonsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	KasbonNumber        string             `json:"kasbon_number"`
	EmployeeID          pgtype.UUID        `json:"employee_id"`
	Amount              int64              `json:"amount"`
	Details             string             `json:"details"`
	SendingMethod       string             `json:"sending_method"`
	FundSourceAccountID pgtype.UUID        `json:"fund_source_account_id"`
	RequestDate         pgtype.Date        `json:"request_date"`
	ResolutionMonth     pgtype.Date        `json:"resolution_month"`
	Status              string             `json:"status"`
	ApprovedBy          pgtype.UUID        `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	ApprovalNote        pgtype.Text        `json:"approval_note"`
	ProcessedBy         pgtype.UUID        `json:"processed_by"`
	ProcessedAt         pgtype.Timestamptz `json:"processed_at"`
	EvidencePhotoPath   pgtype.Text        `json:"evidence_photo_path"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	EmployeeName        string             `json:"employee_name"`
	EmployeeCode        string             `json:"employee_code"`
	FundSourceName      string             `json:"fund_source_name"`
}

func (q *Queries) ListKasbons(ctx context.Context, arg *ListKasbonsParams) ([]*ListKasbonsRow, error) {
	rows, err := q.db.Query(ctx, listKasbons, arg.Status, arg.EmployeeID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListKasbonsRow
	for rows.Next() {
		var i ListKasbonsRow
		if err := rows.Scan(
			&i.ID,
			&i.KasbonNumber,
			&i.EmployeeID,
			&i.Amount,
			&i.Details,
			&i.SendingMethod,
			&i.FundSourceAccountID,
			&i.RequestDate,
			&i.ResolutionMonth,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApprovalNote,
			&i.ProcessedBy,
			&i.ProcessedAt,
			&i.EvidencePhotoPath,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EmployeeName,
			&i.EmployeeCode,
			&i.FundSourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInstallmentsForEmployee = `-- name: ListPendingInstallmentsForEmployee :many
SELECT ki.id, ki.kasbon_id, ki.due_month, ki.amount, ki.payroll_line_id, ki.status
FROM kasbon_installments ki
JOIN kasbons k ON k.id = ki.kasbon_id
WHERE k.employee_id = $1
  AND k.status = 'processed'
  AND ki.status = 'pending'
  AND ki.due_month <= $2
ORDER BY ki.due_month
`

type ListPendingInstallmentsForEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	DueMonth   pgtype.Date `json:"due_month"`
}

func (q *Queries) ListPendingInstallmentsForEmployee(ctx context.Context, arg *ListPendingInstallmentsForEmployeeParams) ([]*KasbonInstallment, error) {
	rows, err := q.db.Query(ctx, listPendingInstallmentsForEmployee, arg.EmployeeID, arg.DueMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*KasbonInstallment
	for rows.Next() {
		var i KasbonInstallment
		if err := rows.Scan(
			&i.ID,
			&i.KasbonID,
			&i.DueMonth,
			&i.Amount,
			&i.PayrollLineID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKasbonInstallmentDeducted = `-- name: MarkKasbonInstallmentDeducted :exec
UPDATE kasbon_installments
SET status = 'deducted', payroll_line_id = $1
WHERE id = $2
`

type MarkKasbonInstallmentDeductedParams struct {
	PayrollLineID pgtype.UUID `json:"payroll_line_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) MarkKasbonInstallmentDeducted(ctx context.Context, arg *MarkKasbonInstallmentDeductedParams) error {
	_, err := q.db.Exec(ctx, markKasbonInstallmentDeducted, arg.PayrollLineID, arg.ID)
	return err
}

const rejectKasbon = `-- name: RejectKasbon :one
UPDATE kasbons
SET status = 'rejected', approved_by = $1, approved_at = now(), approval_note = $2
WHERE id = $3
RETURNING id, kasbon_number, employee_id, amount, details, sending_method,
          fund_source_account_id, request_date, resolution_month, status,
          approved_by, approved_at, approval_note, processed_by, processed_at,
          evidence_photo_path, created_by, created_at
`

type RejectKasbonParams struct {
	ApprovedBy   pgtype.UUID `json:"approved_by"`
	ApprovalNote pgtype.Text `json:"approval_note"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) RejectKasbon(ctx context.Context, arg *RejectKasbonParams) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, rejectKasbon, arg.ApprovedBy, arg.ApprovalNote, arg.ID)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const setKasbonCancelled = `-- name: SetKasbonCancelled :one
UPDATE kasbons
SET status = 'cancelled'
WHERE id = $1
RETURNING id, kasbon_number, employee_id, amount, details, sending_method,
          fund_source_account_id, request_date, resolution_month, status,
          approved_by, approved_at, approval_note, processed_by, processed_at,
          evidence_photo_path, created_by, created_at
`

func (q *Queries) SetKasbonCancelled(ctx context.Context, id pgtype.UUID) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, setKasbonCancelled, id)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const setKasbonProcessed = `-- name: SetKasbonProcessed :one
UPDATE kasbons
SET status = 'processed', processed_by = $1, processed_at = now(),
    evidence_photo_path = $2
WHERE id = $3
RETURNING id, kasbon_number, employee_id, amount, details, sending_method,
          fund_source_account_id, request_date, resolution_month, status,
          approved_by, approved_at, approval_note, processed_by, processed_at,
          evidence_photo_path, created_by, created_at
`

type SetKasbonProcessedParams struct {
	ProcessedBy       pgtype.UUID `json:"processed_by"`
	EvidencePhotoPath pgtype.Text `json:"evidence_photo_path"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) SetKasbonProcessed(ctx context.Context, arg *SetKasbonProcessedParams) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, setKasbonProcessed, arg.ProcessedBy, arg.EvidencePhotoPath, arg.ID)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const setKasbonResolved = `-- name: SetKasbonResolved :exec
UPDATE kasbons
SET status = 'resolved'
WHERE id = $1
`

func (q *Queries) SetKasbonResolved(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setKasbonResolved, id)
	return err
}

const updateKasbon = `-- name: UpdateKasbon :one
UPDATE kasbons
SET amount = $1, details = $2, sending_method = $3, fund_source_account_id = $4,
    resolution_month = $5
WHERE id = $6
RETURNING id, kasbon_number, employee_id, amount, details, sending_method,
          fund_source_account_id, request_date, resolution_month, status,
          approved_by, approved_at, approval_note, processed_by, processed_at,
          evidence_photo_path, created_by, created_at
`

type UpdateKasbonParams struct {
	Amount              int64       `json:"amount"`
	Details             string      `json:"details"`
	SendingMethod       string      `json:"sending_method"`
	FundSourceAccountID pgtype.UUID `json:"fund_source_account_id"`
	ResolutionMonth     pgtype.Date `json:"resolution_month"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateKasbon(ctx context.Context, arg *UpdateKasbonParams) (*Kasbon, error) {
	row := q.db.QueryRow(ctx, updateKasbon,
		arg.Amount,
		arg.Details,
		arg.SendingMethod,
		arg.FundSourceAccountID,
		arg.ResolutionMonth,
		arg.ID,
	)
	var i Kasbon
	err := row.Scan(
		&i.ID,
		&i.KasbonNumber,
		&i.EmployeeID,
		&i.Amount,
		&i.Details,
		&i.SendingMethod,
		&i.FundSourceAccountID,
		&i.RequestDate,
		&i.ResolutionMonth,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalNote,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.EvidencePhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}
