// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_leave.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLeaveTypeReferences = `-- name: CountLeaveTypeReferences :one
SELECT COUNT(*) FROM leave_requests WHERE leave_type_id = $1
`

func (q *Queries) CountLeaveTypeReferences(ctx context.Context, leaveTypeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaveTypeReferences, leaveTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLeaveBalance = `-- name: CreateLeaveBalance :one
INSERT INTO leave_balances (id, employee_id, year, quota_days, used_days)
VALUES (gen_random_uuid(), $1, $2, $3, 0)
RETURNING id, employee_id, year, quota_days, used_days
`

type CreateLeaveBalanceParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Year       int32       `json:"year"`
	QuotaDays  int32       `json:"quota_days"`
}

func (q *Queries) CreateLeaveBalance(ctx context.Context, arg *CreateLeaveBalanceParams) (*LeaveBalance, error) {
	row := q.db.QueryRow(ctx, createLeaveBalance, arg.EmployeeID, arg.Year, arg.QuotaDays)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.QuotaDays,
		&i.UsedDays,
	)
	return &i, err
}

const createLeaveRequest = `-- name: CreateLeaveRequest :one
INSERT INTO leave_requests (
    id, employee_id, leave_type_id, start_date, end_date, day_count, reason,
    status, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, 'pending', $7)
RETURNING id, employee_id, leave_type_id, start_date, end_date, day_count, reason,
          status, decided_by, decided_at, decision_note, created_by, created_at
`

type CreateLeaveRequestParams struct {
	EmployeeID  pgtype.UUID `json:"employee_id"`
	LeaveTypeID pgtype.UUID `json:"leave_type_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	DayCount    int32       `json:"day_count"`
	Reason      pgtype.Text `json:"reason"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg *CreateLeaveRequestParams) (*LeaveRequest, error) {
	row := q.db.QueryRow(ctx, createLeaveRequest,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.DayCount,
		arg.Reason,
		arg.CreatedBy,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DayCount,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createLeaveType = `-- name: CreateLeaveType :one
INSERT INTO leave_types (id, name, is_paid, uses_quota, is_active)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, name, is_paid, uses_quota, is_active
`

type CreateLeaveTypeParams struct {
	Name      string `json:"name"`
	IsPaid    bool   `json:"is_paid"`
	UsesQuota bool   `json:"uses_quota"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreateLeaveType(ctx context.Context, arg *CreateLeaveTypeParams) (*LeaveType, error) {
	row := q.db.QueryRow(ctx, createLeaveType,
		arg.Name,
		arg.IsPaid,
		arg.UsesQuota,
		arg.IsActive,
	)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPaid,
		&i.UsesQuota,
		&i.IsActive,
	)
	return &i, err
}

const deleteLeaveAttendanceWithoutCheckIn = `-- name: DeleteLeaveAttendanceWithoutCheckIn :exec
DELETE FROM attendance_records
WHERE employee_id = $1 AND date = $2 AND status = 'leave' AND check_in IS NULL
`

type DeleteLeaveAttendanceWithoutCheckInParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) DeleteLeaveAttendanceWithoutCheckIn(ctx context.Context, arg *DeleteLeaveAttendanceWithoutCheckInParams) error {
	_, err := q.db.Exec(ctx, deleteLeaveAttendanceWithoutCheckIn, arg.EmployeeID, arg.Date)
	return err
}

const deleteLeaveType = `-- name: DeleteLeaveType :exec
DELETE FROM leave_types WHERE id = $1
`

func (q *Queries) DeleteLeaveType(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLeaveType, id)
	return err
}

const getLeaveBalance = `-- name: GetLeaveBalance :one
SELECT id, employee_id, year, quota_days, used_days
FROM leave_balances
WHERE employee_id = $1 AND year = $2
`

type GetLeaveBalanceParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Year       int32       `json:"year"`
}

func (q *Queries) GetLeaveBalance(ctx context.Context, arg *GetLeaveBalanceParams) (*LeaveBalance, error) {
	row := q.db.QueryRow(ctx, getLeaveBalance, arg.EmployeeID, arg.Year)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.QuotaDays,
		&i.UsedDays,
	)
	return &i, err
}

const getLeaveRequestByID = `-- name: GetLeaveRequestByID :one
SELECT id, employee_id, leave_type_id, start_date, end_date, day_count, reason,
       status, decided_by, decided_at, decision_note, created_by, created_at
FROM leave_requests
WHERE id = $1
`

func (q *Queries) GetLeaveRequestByID(ctx context.Context, id pgtype.UUID) (*LeaveRequest, error) {
	row := q.db.QueryRow(ctx, getLeaveRequestByID, id)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DayCount,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getLeaveTypeByID = `-- name: GetLeaveTypeByID :one
SELECT id, name, is_paid, uses_quota, is_active
FROM leave_types
WHERE id = $1
`

func (q *Queries) GetLeaveTypeByID(ctx context.Context, id pgtype.UUID) (*LeaveType, error) {
	row := q.db.QueryRow(ctx, getLeaveTypeByID, id)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPaid,
		&i.UsesQuota,
		&i.IsActive,
	)
	return &i, err
}

const hasCheckInOnDate = `-- name: HasCheckInOnDate :one
SELECT EXISTS (
    SELECT 1 FROM attendance_records
    WHERE employee_id = $1 AND date = $2 AND check_in IS NOT NULL
) AS exists
`

type HasCheckInOnDateParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) HasCheckInOnDate(ctx context.Context, arg *HasCheckInOnDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCheckInOnDate, arg.EmployeeID, arg.Date)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementLeaveBalanceUsed = `-- name: IncrementLeaveBalanceUsed :one
UPDATE leave_balances
SET used_days = used_days + $1
WHERE employee_id = $2 AND year = $3
RETURNING id, employee_id, year, quota_days, used_days
`

type IncrementLeaveBalanceUsedParams struct {
	UsedDays   int32       `json:"used_days"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Year       int32       `json:"year"`
}

func (q *Queries) IncrementLeaveBalanceUsed(ctx context.Context, arg *IncrementLeaveBalanceUsedParams) (*LeaveBalance, error) {
	row := q.db.QueryRow(ctx, incrementLeaveBalanceUsed, arg.UsedDays, arg.EmployeeID, arg.Year)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.QuotaDays,
		&i.UsedDays,
	)
	return &i, err
}

const listActiveLeaveTypes = `-- name: ListActiveLeaveTypes :many
SELECT id, name, is_paid, uses_quota, is_active
FROM leave_types
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveLeaveTypes(ctx context.Context) ([]*LeaveType, error) {
	rows, err := q.db.Query(ctx, listActiveLeaveTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*LeaveType
	for rows.Next() {
		var i LeaveType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPaid,
			&i.UsesQuota,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedUnpaidLeaveOverlapping = `-- name: ListApprovedUnpaidLeaveOverlapping :many
SELECT lr.id, lr.employee_id, lr.start_date, lr.end_date
FROM leave_requests lr
JOIN leave_types lt ON lt.id = lr.leave_type_id
WHERE lr.employee_id = $1
  AND lr.status = 'approved'
  AND lt.is_paid = false
  AND lr.start_date <= $3
  AND lr.end_date >= $2
`

type ListApprovedUnpaidLeaveOverlappingParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type ListApprovedUnpaidLeaveOverlappingRow struct {
	ID         pgtype.UUID `json:"id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) ListApprovedUnpaidLeaveOverlapping(ctx context.Context, arg *ListApprovedUnpaidLeaveOverlappingParams) ([]*ListApprovedUnpaidLeaveOverlappingRow, error) {
	rows, err := q.db.Query(ctx, listApprovedUnpaidLeaveOverlapping, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListApprovedUnpaidLeaveOverlappingRow
	for rows.Next() {
		var i ListApprovedUnpaidLeaveOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidaysInRange = `-- name: ListHolidaysInRange :many
SELECT date
FROM public_holidays
WHERE date >= $1 AND date <= $2
`

type ListHolidaysInRangeParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) ListHolidaysInRange(ctx context.Context, arg *ListHolidaysInRangeParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listHolidaysInRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var date pgtype.Date
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveRequests = `-- name: ListLeaveRequests :many
SELECT lr.id, lr.employee_id, lr.leave_type_id, lr.start_date, lr.end_date,
       lr.day_count, lr.reason, lr.status, lr.decided_by, lr.decided_at,
       lr.decision_note, lr.created_by, lr.created_at,
       e.full_name AS employee_name, e.employee_code, e.branch_id,
       lt.name AS leave_type_name, lt.is_paid, lt.uses_quota
FROM leave_requests lr
JOIN employees e ON e.id = lr.employee_id
JOIN leave_types lt ON lt.id = lr.leave_type_id
WHERE ($1::text = '' OR lr.status = $1)
  AND ($2::uuid IS NULL OR e.branch_id = $2)
  AND ($3::uuid IS NULL OR lr.employee_id = $3)
  AND ($4::int = 0 OR EXTRACT(YEAR FROM lr.start_date) = $4)
ORDER BY lr.created_at DESC
`

type ListLeaveRequestsParams struct {
	Status     string      `json:"status"`
	BranchID   pgtype.UUID `json:"branch_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Year       int32       `json:"year"`
}

type ListLeaveRequestsRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmployeeID    pgtype.UUID        `json:"employee_id"`
	LeaveTypeID   pgtype.UUID        `json:"leave_type_id"`
	StartDate     pgtype.Date        `json:"start_date"`
	EndDate       pgtype.Date        `json:"end_date"`
	DayCount      int32              `json:"day_count"`
	Reason        pgtype.Text        `json:"reason"`
	Status        string             `json:"status"`
	DecidedBy     pgtype.UUID        `json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	DecisionNote  pgtype.Text        `json:"decision_note"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EmployeeName  string             `json:"employee_name"`
	EmployeeCode  string             `json:"employee_code"`
	BranchID      pgtype.UUID        `json:"branch_id"`
	LeaveTypeName string             `json:"leave_type_name"`
	IsPaid        bool               `json:"is_paid"`
	UsesQuota     bool               `json:"uses_quota"`
}

func (q *Queries) ListLeaveRequests(ctx context.Context, arg *ListLeaveRequestsParams) ([]*ListLeaveRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLeaveRequests,
		arg.Status,
		arg.BranchID,
		arg.EmployeeID,
		arg.Year,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListLeaveRequestsRow
	for rows.Next() {
		var i ListLeaveRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.DayCount,
			&i.Reason,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EmployeeName,
			&i.EmployeeCode,
			&i.BranchID,
			&i.LeaveTypeName,
			&i.IsPaid,
			&i.UsesQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveRequestsByEmployee = `-- name: ListLeaveRequestsByEmployee :many
SELECT lr.id, lr.employee_id, lr.leave_type_id, lr.start_date, lr.end_date,
       lr.day_count, lr.reason, lr.status, lr.decided_by, lr.decided_at,
       lr.decision_note, lr.created_by, lr.created_at,
       lt.name AS leave_type_name, lt.is_paid, lt.uses_quota
FROM leave_requests lr
JOIN leave_types lt ON lt.id = lr.leave_type_id
WHERE lr.employee_id = $1
ORDER BY lr.start_date DESC
`

type ListLeaveRequestsByEmployeeRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmployeeID    pgtype.UUID        `json:"employee_id"`
	LeaveTypeID   pgtype.UUID        `json:"leave_type_id"`
	StartDate     pgtype.Date        `json:"start_date"`
	EndDate       pgtype.Date        `json:"end_date"`
	DayCount      int32              `json:"day_count"`
	Reason        pgtype.Text        `json:"reason"`
	Status        string             `json:"status"`
	DecidedBy     pgtype.UUID        `json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	DecisionNote  pgtype.Text        `json:"decision_note"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LeaveTypeName string             `json:"leave_type_name"`
	IsPaid        bool               `json:"is_paid"`
	UsesQuota     bool               `json:"uses_quota"`
}

func (q *Queries) ListLeaveRequestsByEmployee(ctx context.Context, employeeID pgtype.UUID) ([]*ListLeaveRequestsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listLeaveRequestsByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListLeaveRequestsByEmployeeRow
	for rows.Next() {
		var i ListLeaveRequestsByEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.DayCount,
			&i.Reason,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LeaveTypeName,
			&i.IsPaid,
			&i.UsesQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveTypes = `-- name: ListLeaveTypes :many
SELECT id, name, is_paid, uses_quota, is_active
FROM leave_types
ORDER BY name
`

func (q *Queries) ListLeaveTypes(ctx context.Context) ([]*LeaveType, error) {
	rows, err := q.db.Query(ctx, listLeaveTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*LeaveType
	for rows.Next() {
		var i LeaveType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPaid,
			&i.UsesQuota,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverlappingRequests = `-- name: ListOverlappingRequests :many
SELECT id, employee_id, leave_type_id, start_date, end_date, day_count, reason,
       status, decided_by, decided_at, decision_note, created_by, created_at
FROM leave_requests
WHERE employee_id = $1
  AND status IN ('pending', 'approved')
  AND start_date <= $3
  AND end_date >= $2
`

type ListOverlappingRequestsParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) ListOverlappingRequests(ctx context.Context, arg *ListOverlappingRequestsParams) ([]*LeaveRequest, error) {
	rows, err := q.db.Query(ctx, listOverlappingRequests, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.DayCount,
			&i.Reason,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLeaveBalanceQuota = `-- name: SetLeaveBalanceQuota :one
UPDATE leave_balances
SET quota_days = $1
WHERE employee_id = $2 AND year = $3
RETURNING id, employee_id, year, quota_days, used_days
`

type SetLeaveBalanceQuotaParams struct {
	QuotaDays  int32       `json:"quota_days"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Year       int32       `json:"year"`
}

func (q *Queries) SetLeaveBalanceQuota(ctx context.Context, arg *SetLeaveBalanceQuotaParams) (*LeaveBalance, error) {
	row := q.db.QueryRow(ctx, setLeaveBalanceQuota, arg.QuotaDays, arg.EmployeeID, arg.Year)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.QuotaDays,
		&i.UsedDays,
	)
	return &i, err
}

const setLeaveRequestStatus = `-- name: SetLeaveRequestStatus :one
UPDATE leave_requests
SET status = $1, decided_by = $2, decided_at = now(), decision_note = $3
WHERE id = $4
RETURNING id, employee_id, leave_type_id, start_date, end_date, day_count, reason,
          status, decided_by, decided_at, decision_note, created_by, created_at
`

type SetLeaveRequestStatusParams struct {
	Status       string      `json:"status"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
	DecisionNote pgtype.Text `json:"decision_note"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetLeaveRequestStatus(ctx context.Context, arg *SetLeaveRequestStatusParams) (*LeaveRequest, error) {
	row := q.db.QueryRow(ctx, setLeaveRequestStatus,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionNote,
		arg.ID,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DayCount,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const setLeaveTypeActive = `-- name: SetLeaveTypeActive :one
UPDATE leave_types
SET is_active = $1
WHERE id = $2
RETURNING id, name, is_paid, uses_quota, is_active
`

type SetLeaveTypeActiveParams struct {
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetLeaveTypeActive(ctx context.Context, arg *SetLeaveTypeActiveParams) (*LeaveType, error) {
	row := q.db.QueryRow(ctx, setLeaveTypeActive, arg.IsActive, arg.ID)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPaid,
		&i.UsesQuota,
		&i.IsActive,
	)
	return &i, err
}

const updateLeaveType = `-- name: UpdateLeaveType :one
UPDATE leave_types
SET name = $1, is_paid = $2, uses_quota = $3, is_active = $4
WHERE id = $5
RETURNING id, name, is_paid, uses_quota, is_active
`

type UpdateLeaveTypeParams struct {
	Name      string      `json:"name"`
	IsPaid    bool        `json:"is_paid"`
	UsesQuota bool        `json:"uses_quota"`
	IsActive  bool        `json:"is_active"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateLeaveType(ctx context.Context, arg *UpdateLeaveTypeParams) (*LeaveType, error) {
	row := q.db.QueryRow(ctx, updateLeaveType,
		arg.Name,
		arg.IsPaid,
		arg.UsesQuota,
		arg.IsActive,
		arg.ID,
	)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPaid,
		&i.UsesQuota,
		&i.IsActive,
	)
	return &i, err
}

const upsertLeaveAttendance = `-- name: UpsertLeaveAttendance :exec
INSERT INTO attendance_records (id, employee_id, date, status)
VALUES (gen_random_uuid(), $1, $2, 'leave')
ON CONFLICT (employee_id, date)
DO UPDATE SET status = 'leave'
WHERE attendance_records.check_in IS NULL
`

type UpsertLeaveAttendanceParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) UpsertLeaveAttendance(ctx context.Context, arg *UpsertLeaveAttendanceParams) error {
	_, err := q.db.Exec(ctx, upsertLeaveAttendance, arg.EmployeeID, arg.Date)
	return err
}
