// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_overtime.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveOvertimeRequest = `-- name: ApproveOvertimeRequest :one
UPDATE overtime_requests
SET status = 'approved', decided_by = $2, decided_at = now(), decision_note = $3
WHERE id = $1 AND status = 'pending'
RETURNING id, employee_id, date, hours, reason, status, decided_by, decided_at, decision_note, created_by, created_at
`

type ApproveOvertimeRequestParams struct {
	ID           pgtype.UUID `json:"id"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
	DecisionNote pgtype.Text `json:"decision_note"`
}

type ApproveOvertimeRequestRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Date         pgtype.Date        `json:"date"`
	Hours        pgtype.Numeric     `json:"hours"`
	Reason       pgtype.Text        `json:"reason"`
	Status       string             `json:"status"`
	DecidedBy    pgtype.UUID        `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote pgtype.Text        `json:"decision_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ApproveOvertimeRequest(ctx context.Context, arg *ApproveOvertimeRequestParams) (*ApproveOvertimeRequestRow, error) {
	row := q.db.QueryRow(ctx, approveOvertimeRequest, arg.ID, arg.DecidedBy, arg.DecisionNote)
	var i ApproveOvertimeRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const cancelOvertimeRequest = `-- name: CancelOvertimeRequest :one
UPDATE overtime_requests
SET status = 'cancelled', decided_by = $2, decided_at = now(), decision_note = $3
WHERE id = $1 AND status IN ('pending', 'approved')
RETURNING id, employee_id, date, hours, reason, status, decided_by, decided_at, decision_note, created_by, created_at
`

type CancelOvertimeRequestParams struct {
	ID           pgtype.UUID `json:"id"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
	DecisionNote pgtype.Text `json:"decision_note"`
}

type CancelOvertimeRequestRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Date         pgtype.Date        `json:"date"`
	Hours        pgtype.Numeric     `json:"hours"`
	Reason       pgtype.Text        `json:"reason"`
	Status       string             `json:"status"`
	DecidedBy    pgtype.UUID        `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote pgtype.Text        `json:"decision_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CancelOvertimeRequest(ctx context.Context, arg *CancelOvertimeRequestParams) (*CancelOvertimeRequestRow, error) {
	row := q.db.QueryRow(ctx, cancelOvertimeRequest, arg.ID, arg.DecidedBy, arg.DecisionNote)
	var i CancelOvertimeRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createOvertimeRequest = `-- name: CreateOvertimeRequest :one

INSERT INTO overtime_requests (id, employee_id, date, hours, reason, created_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, employee_id, date, hours, reason, status, decided_by, decided_at, decision_note, created_by, created_at
`

type CreateOvertimeRequestParams struct {
	EmployeeID pgtype.UUID    `json:"employee_id"`
	Date       pgtype.Date    `json:"date"`
	Hours      pgtype.Numeric `json:"hours"`
	Reason     pgtype.Text    `json:"reason"`
	CreatedBy  pgtype.UUID    `json:"created_by"`
}

type CreateOvertimeRequestRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Date         pgtype.Date        `json:"date"`
	Hours        pgtype.Numeric     `json:"hours"`
	Reason       pgtype.Text        `json:"reason"`
	Status       string             `json:"status"`
	DecidedBy    pgtype.UUID        `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote pgtype.Text        `json:"decision_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// ── Overtime Requests ────────────────────────────────────────────────────────
func (q *Queries) CreateOvertimeRequest(ctx context.Context, arg *CreateOvertimeRequestParams) (*CreateOvertimeRequestRow, error) {
	row := q.db.QueryRow(ctx, createOvertimeRequest,
		arg.EmployeeID,
		arg.Date,
		arg.Hours,
		arg.Reason,
		arg.CreatedBy,
	)
	var i CreateOvertimeRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteOvertimeRequest = `-- name: DeleteOvertimeRequest :exec
DELETE FROM overtime_requests WHERE id = $1
`

func (q *Queries) DeleteOvertimeRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOvertimeRequest, id)
	return err
}

const getOvertimeRequestByID = `-- name: GetOvertimeRequestByID :one
SELECT id, employee_id, date, hours, reason, status, decided_by, decided_at, decision_note, created_by, created_at
FROM overtime_requests
WHERE id = $1
`

type GetOvertimeRequestByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Date         pgtype.Date        `json:"date"`
	Hours        pgtype.Numeric     `json:"hours"`
	Reason       pgtype.Text        `json:"reason"`
	Status       string             `json:"status"`
	DecidedBy    pgtype.UUID        `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote pgtype.Text        `json:"decision_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOvertimeRequestByID(ctx context.Context, id pgtype.UUID) (*GetOvertimeRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getOvertimeRequestByID, id)
	var i GetOvertimeRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const listOvertimeRequestsForEmployee = `-- name: ListOvertimeRequestsForEmployee :many
SELECT id, employee_id, date, hours, reason, created_by, created_at
FROM overtime_requests
WHERE employee_id = $1
  AND date >= $2 AND date <= $3
ORDER BY date
`

type ListOvertimeRequestsForEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

type ListOvertimeRequestsForEmployeeRow struct {
	ID         pgtype.UUID        `json:"id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	Date       pgtype.Date        `json:"date"`
	Hours      pgtype.Numeric     `json:"hours"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOvertimeRequestsForEmployee(ctx context.Context, arg *ListOvertimeRequestsForEmployeeParams) ([]*ListOvertimeRequestsForEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listOvertimeRequestsForEmployee, arg.EmployeeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOvertimeRequestsForEmployeeRow
	for rows.Next() {
		var i ListOvertimeRequestsForEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Date,
			&i.Hours,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectOvertimeRequest = `-- name: RejectOvertimeRequest :one
UPDATE overtime_requests
SET status = 'rejected', decided_by = $2, decided_at = now(), decision_note = $3
WHERE id = $1 AND status = 'pending'
RETURNING id, employee_id, date, hours, reason, status, decided_by, decided_at, decision_note, created_by, created_at
`

type RejectOvertimeRequestParams struct {
	ID           pgtype.UUID `json:"id"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
	DecisionNote pgtype.Text `json:"decision_note"`
}

type RejectOvertimeRequestRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Date         pgtype.Date        `json:"date"`
	Hours        pgtype.Numeric     `json:"hours"`
	Reason       pgtype.Text        `json:"reason"`
	Status       string             `json:"status"`
	DecidedBy    pgtype.UUID        `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote pgtype.Text        `json:"decision_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RejectOvertimeRequest(ctx context.Context, arg *RejectOvertimeRequestParams) (*RejectOvertimeRequestRow, error) {
	row := q.db.QueryRow(ctx, rejectOvertimeRequest, arg.ID, arg.DecidedBy, arg.DecisionNote)
	var i RejectOvertimeRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const sumOvertimeHoursForEmployee = `-- name: SumOvertimeHoursForEmployee :one
SELECT COALESCE(SUM(hours), 0)::float8 AS total_hours
FROM overtime_requests
WHERE employee_id = $1
  AND date >= $2 AND date <= $3
  AND status = 'approved'
`

type SumOvertimeHoursForEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

// Only APPROVED overtime feeds payroll.
func (q *Queries) SumOvertimeHoursForEmployee(ctx context.Context, arg *SumOvertimeHoursForEmployeeParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumOvertimeHoursForEmployee, arg.EmployeeID, arg.Date, arg.Date_2)
	var total_hours float64
	err := row.Scan(&total_hours)
	return total_hours, err
}
