// Code generated by sqlc. DO NOT EDIT.
// source: hr_overtime.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type OvertimeRequest struct {
	ID         pgtype.UUID        `json:"id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	Date       pgtype.Date        `json:"date"`
	Hours      pgtype.Numeric     `json:"hours"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// ── CreateOvertimeRequest ────────────────────────────────────────────────────

const createOvertimeRequest = `-- name: CreateOvertimeRequest :one
INSERT INTO overtime_requests (id, employee_id, date, hours, reason, created_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, employee_id, date, hours, reason, created_by, created_at
`

type CreateOvertimeRequestParams struct {
	EmployeeID pgtype.UUID    `json:"employee_id"`
	Date       pgtype.Date    `json:"date"`
	Hours      pgtype.Numeric `json:"hours"`
	Reason     pgtype.Text    `json:"reason"`
	CreatedBy  pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateOvertimeRequest(ctx context.Context, arg *CreateOvertimeRequestParams) (*OvertimeRequest, error) {
	row := q.db.QueryRow(ctx, createOvertimeRequest,
		arg.EmployeeID, arg.Date, arg.Hours, arg.Reason, arg.CreatedBy,
	)
	var i OvertimeRequest
	err := row.Scan(&i.ID, &i.EmployeeID, &i.Date, &i.Hours, &i.Reason, &i.CreatedBy, &i.CreatedAt)
	return &i, err
}

// ── GetOvertimeRequestByID ───────────────────────────────────────────────────

const getOvertimeRequestByID = `-- name: GetOvertimeRequestByID :one
SELECT id, employee_id, date, hours, reason, created_by, created_at
FROM overtime_requests
WHERE id = $1
`

func (q *Queries) GetOvertimeRequestByID(ctx context.Context, id pgtype.UUID) (*OvertimeRequest, error) {
	row := q.db.QueryRow(ctx, getOvertimeRequestByID, id)
	var i OvertimeRequest
	err := row.Scan(&i.ID, &i.EmployeeID, &i.Date, &i.Hours, &i.Reason, &i.CreatedBy, &i.CreatedAt)
	return &i, err
}

// ── DeleteOvertimeRequest ────────────────────────────────────────────────────

const deleteOvertimeRequest = `-- name: DeleteOvertimeRequest :exec
DELETE FROM overtime_requests WHERE id = $1
`

func (q *Queries) DeleteOvertimeRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOvertimeRequest, id)
	return err
}

// ── SumOvertimeHoursForEmployee ──────────────────────────────────────────────

const sumOvertimeHoursForEmployee = `-- name: SumOvertimeHoursForEmployee :one
SELECT COALESCE(SUM(hours), 0)::float8 AS total_hours
FROM overtime_requests
WHERE employee_id = $1
  AND date >= $2 AND date <= $3
`

type SumOvertimeHoursForEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

func (q *Queries) SumOvertimeHoursForEmployee(ctx context.Context, arg *SumOvertimeHoursForEmployeeParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumOvertimeHoursForEmployee, arg.EmployeeID, arg.Date, arg.Date_2)
	var total float64
	err := row.Scan(&total)
	return total, err
}

// ── ListOvertimeRequestsForEmployee ─────────────────────────────────────────

const listOvertimeRequestsForEmployee = `-- name: ListOvertimeRequestsForEmployee :many
SELECT id, employee_id, date, hours, reason, created_by, created_at
FROM overtime_requests
WHERE employee_id = $1
  AND date >= $2 AND date <= $3
ORDER BY date
`

type ListOvertimeRequestsForEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

func (q *Queries) ListOvertimeRequestsForEmployee(ctx context.Context, arg *ListOvertimeRequestsForEmployeeParams) ([]*OvertimeRequest, error) {
	rows, err := q.db.Query(ctx, listOvertimeRequestsForEmployee, arg.EmployeeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OvertimeRequest
	for rows.Next() {
		var i OvertimeRequest
		if err := rows.Scan(&i.ID, &i.EmployeeID, &i.Date, &i.Hours, &i.Reason, &i.CreatedBy, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
