// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_payroll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closePayrollPeriod = `-- name: ClosePayrollPeriod :one
UPDATE payroll_periods
SET status = 'closed', closed_at = now()
WHERE id = $1
RETURNING id, period_month, start_date, end_date, status, created_by, closed_at, paid_at, created_at
`

func (q *Queries) ClosePayrollPeriod(ctx context.Context, id pgtype.UUID) (*PayrollPeriod, error) {
	row := q.db.QueryRow(ctx, closePayrollPeriod, id)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodMonth,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.ClosedAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return &i, err
}

const countPresentOnHolidays = `-- name: CountPresentOnHolidays :one

SELECT COUNT(*)::int AS cnt
FROM attendance_records ar
JOIN public_holidays ph ON ph.date = ar.date
WHERE ar.employee_id = $1
  AND ar.date >= $2 AND ar.date <= $3
  AND ar.status = 'present'
`

type CountPresentOnHolidaysParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

// ── Attendance helper: present-on-holiday prefill ────────────────────────────
func (q *Queries) CountPresentOnHolidays(ctx context.Context, arg *CountPresentOnHolidaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPresentOnHolidays, arg.EmployeeID, arg.Date, arg.Date_2)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const listHolidaysWorked = `-- name: ListHolidaysWorked :many
SELECT ph.id, ph.date, ph.name
FROM attendance_records ar
JOIN public_holidays ph ON ph.date = ar.date
WHERE ar.employee_id = $1
  AND ar.date >= $2 AND ar.date <= $3
  AND ar.status = 'present'
ORDER BY ph.date
`

type ListHolidaysWorkedParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

func (q *Queries) ListHolidaysWorked(ctx context.Context, arg *ListHolidaysWorkedParams) ([]*PublicHoliday, error) {
	rows, err := q.db.Query(ctx, listHolidaysWorked, arg.EmployeeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PublicHoliday
	for rows.Next() {
		var i PublicHoliday
		if err := rows.Scan(&i.ID, &i.Date, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreviewedLines = `-- name: CountUnreviewedLines :one
SELECT COUNT(*) FROM payroll_lines
WHERE payroll_period_id = $1 AND reviewed = false
`

func (q *Queries) CountUnreviewedLines(ctx context.Context, payrollPeriodID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreviewedLines, payrollPeriodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayrollLine = `-- name: CreatePayrollLine :one

INSERT INTO payroll_lines (
    id, payroll_period_id, employee_id, wage_structure_id,
    base_salary, daily_rate, overtime_days, public_holiday_days,
    overtime_amount, public_holiday_amount, allowance_total, bonus_total,
    component_deduction_total, kasbon_deduction, unpaid_leave_days,
    unpaid_leave_deduction, gross_pay, net_pay, performance_score,
    overtime_hours, overtime_hourly_rate, overtime_hourly_amount
)
VALUES (
    gen_random_uuid(), $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21
)
RETURNING id, payroll_period_id, employee_id, wage_structure_id, base_salary, daily_rate,
          overtime_days, public_holiday_days, overtime_amount, public_holiday_amount,
          allowance_total, bonus_total, component_deduction_total, kasbon_deduction,
          unpaid_leave_days, unpaid_leave_deduction, gross_pay, net_pay,
          performance_score, reviewed, reviewed_by, reviewed_at, review_note,
          overtime_hours, overtime_hourly_rate, overtime_hourly_amount
`

type CreatePayrollLineParams struct {
	PayrollPeriodID         pgtype.UUID    `json:"payroll_period_id"`
	EmployeeID              pgtype.UUID    `json:"employee_id"`
	WageStructureID         pgtype.UUID    `json:"wage_structure_id"`
	BaseSalary              int64          `json:"base_salary"`
	DailyRate               int64          `json:"daily_rate"`
	OvertimeDays            pgtype.Numeric `json:"overtime_days"`
	PublicHolidayDays       pgtype.Numeric `json:"public_holiday_days"`
	OvertimeAmount          int64          `json:"overtime_amount"`
	PublicHolidayAmount     int64          `json:"public_holiday_amount"`
	AllowanceTotal          int64          `json:"allowance_total"`
	BonusTotal              int64          `json:"bonus_total"`
	ComponentDeductionTotal int64          `json:"component_deduction_total"`
	KasbonDeduction         int64          `json:"kasbon_deduction"`
	UnpaidLeaveDays         int32          `json:"unpaid_leave_days"`
	UnpaidLeaveDeduction    int64          `json:"unpaid_leave_deduction"`
	GrossPay                int64          `json:"gross_pay"`
	NetPay                  int64          `json:"net_pay"`
	PerformanceScore        pgtype.Int4    `json:"performance_score"`
	OvertimeHours           pgtype.Numeric `json:"overtime_hours"`
	OvertimeHourlyRate      int64          `json:"overtime_hourly_rate"`
	OvertimeHourlyAmount    int64          `json:"overtime_hourly_amount"`
}

// ── Payroll Lines ────────────────────────────────────────────────────────────
func (q *Queries) CreatePayrollLine(ctx context.Context, arg *CreatePayrollLineParams) (*PayrollLine, error) {
	row := q.db.QueryRow(ctx, createPayrollLine,
		arg.PayrollPeriodID,
		arg.EmployeeID,
		arg.WageStructureID,
		arg.BaseSalary,
		arg.DailyRate,
		arg.OvertimeDays,
		arg.PublicHolidayDays,
		arg.OvertimeAmount,
		arg.PublicHolidayAmount,
		arg.AllowanceTotal,
		arg.BonusTotal,
		arg.ComponentDeductionTotal,
		arg.KasbonDeduction,
		arg.UnpaidLeaveDays,
		arg.UnpaidLeaveDeduction,
		arg.GrossPay,
		arg.NetPay,
		arg.PerformanceScore,
		arg.OvertimeHours,
		arg.OvertimeHourlyRate,
		arg.OvertimeHourlyAmount,
	)
	var i PayrollLine
	err := row.Scan(
		&i.ID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.WageStructureID,
		&i.BaseSalary,
		&i.DailyRate,
		&i.OvertimeDays,
		&i.PublicHolidayDays,
		&i.OvertimeAmount,
		&i.PublicHolidayAmount,
		&i.AllowanceTotal,
		&i.BonusTotal,
		&i.ComponentDeductionTotal,
		&i.KasbonDeduction,
		&i.UnpaidLeaveDays,
		&i.UnpaidLeaveDeduction,
		&i.GrossPay,
		&i.NetPay,
		&i.PerformanceScore,
		&i.Reviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.OvertimeHours,
		&i.OvertimeHourlyRate,
		&i.OvertimeHourlyAmount,
	)
	return &i, err
}

const createPayrollLineComponent = `-- name: CreatePayrollLineComponent :one

INSERT INTO payroll_line_components (id, payroll_line_id, wage_component_id, name, type, amount)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, payroll_line_id, wage_component_id, name, type, amount
`

type CreatePayrollLineComponentParams struct {
	PayrollLineID   pgtype.UUID `json:"payroll_line_id"`
	WageComponentID pgtype.UUID `json:"wage_component_id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Amount          int64       `json:"amount"`
}

// ── Payroll Line Components ──────────────────────────────────────────────────
func (q *Queries) CreatePayrollLineComponent(ctx context.Context, arg *CreatePayrollLineComponentParams) (*PayrollLineComponent, error) {
	row := q.db.QueryRow(ctx, createPayrollLineComponent,
		arg.PayrollLineID,
		arg.WageComponentID,
		arg.Name,
		arg.Type,
		arg.Amount,
	)
	var i PayrollLineComponent
	err := row.Scan(
		&i.ID,
		&i.PayrollLineID,
		&i.WageComponentID,
		&i.Name,
		&i.Type,
		&i.Amount,
	)
	return &i, err
}

const createPayrollPeriod = `-- name: CreatePayrollPeriod :one

INSERT INTO payroll_periods (id, period_month, start_date, end_date, status, created_by)
VALUES (gen_random_uuid(), $1, $2, $3, 'open', $4)
RETURNING id, period_month, start_date, end_date, status, created_by, closed_at, paid_at, created_at
`

type CreatePayrollPeriodParams struct {
	PeriodMonth pgtype.Date `json:"period_month"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// ── Payroll Periods ──────────────────────────────────────────────────────────
func (q *Queries) CreatePayrollPeriod(ctx context.Context, arg *CreatePayrollPeriodParams) (*PayrollPeriod, error) {
	row := q.db.QueryRow(ctx, createPayrollPeriod,
		arg.PeriodMonth,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodMonth,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.ClosedAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deletePayrollPeriod = `-- name: DeletePayrollPeriod :exec
DELETE FROM payroll_periods WHERE id = $1
`

func (q *Queries) DeletePayrollPeriod(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePayrollPeriod, id)
	return err
}

const deletePayrollLine = `-- name: DeletePayrollLine :exec
DELETE FROM payroll_lines WHERE id = $1
`

func (q *Queries) DeletePayrollLine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePayrollLine, id)
	return err
}

const deletePayrollLineComponents = `-- name: DeletePayrollLineComponents :exec
DELETE FROM payroll_line_components WHERE payroll_line_id = $1
`

func (q *Queries) DeletePayrollLineComponents(ctx context.Context, payrollLineID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePayrollLineComponents, payrollLineID)
	return err
}

const getAttendanceSummaryForMonth = `-- name: GetAttendanceSummaryForMonth :one
SELECT
    COUNT(*) FILTER (WHERE status = 'present')::int AS hadir,
    COUNT(*) FILTER (WHERE status = 'absent')::int  AS absen,
    COUNT(*) FILTER (WHERE is_late)::int             AS terlambat,
    COUNT(*) FILTER (WHERE status = 'leave')::int    AS cuti
FROM attendance_records
WHERE employee_id = $1
  AND date >= $2 AND date <= $3
`

type GetAttendanceSummaryForMonthParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

type GetAttendanceSummaryForMonthRow struct {
	Hadir     int32 `json:"hadir"`
	Absen     int32 `json:"absen"`
	Terlambat int32 `json:"terlambat"`
	Cuti      int32 `json:"cuti"`
}

func (q *Queries) GetAttendanceSummaryForMonth(ctx context.Context, arg *GetAttendanceSummaryForMonthParams) (*GetAttendanceSummaryForMonthRow, error) {
	row := q.db.QueryRow(ctx, getAttendanceSummaryForMonth, arg.EmployeeID, arg.Date, arg.Date_2)
	var i GetAttendanceSummaryForMonthRow
	err := row.Scan(
		&i.Hadir,
		&i.Absen,
		&i.Terlambat,
		&i.Cuti,
	)
	return &i, err
}

const getPayrollLineByID = `-- name: GetPayrollLineByID :one
SELECT id, payroll_period_id, employee_id, wage_structure_id, base_salary, daily_rate,
       overtime_days, public_holiday_days, overtime_amount, public_holiday_amount,
       allowance_total, bonus_total, component_deduction_total, kasbon_deduction,
       unpaid_leave_days, unpaid_leave_deduction, gross_pay, net_pay,
       performance_score, reviewed, reviewed_by, reviewed_at, review_note,
       overtime_hours, overtime_hourly_rate, overtime_hourly_amount
FROM payroll_lines
WHERE id = $1
`

func (q *Queries) GetPayrollLineByID(ctx context.Context, id pgtype.UUID) (*PayrollLine, error) {
	row := q.db.QueryRow(ctx, getPayrollLineByID, id)
	var i PayrollLine
	err := row.Scan(
		&i.ID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.WageStructureID,
		&i.BaseSalary,
		&i.DailyRate,
		&i.OvertimeDays,
		&i.PublicHolidayDays,
		&i.OvertimeAmount,
		&i.PublicHolidayAmount,
		&i.AllowanceTotal,
		&i.BonusTotal,
		&i.ComponentDeductionTotal,
		&i.KasbonDeduction,
		&i.UnpaidLeaveDays,
		&i.UnpaidLeaveDeduction,
		&i.GrossPay,
		&i.NetPay,
		&i.PerformanceScore,
		&i.Reviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.OvertimeHours,
		&i.OvertimeHourlyRate,
		&i.OvertimeHourlyAmount,
	)
	return &i, err
}

const getPayrollLineByPeriodEmployee = `-- name: GetPayrollLineByPeriodEmployee :one
SELECT id, payroll_period_id, employee_id, wage_structure_id, base_salary, daily_rate,
       overtime_days, public_holiday_days, overtime_amount, public_holiday_amount,
       allowance_total, bonus_total, component_deduction_total, kasbon_deduction,
       unpaid_leave_days, unpaid_leave_deduction, gross_pay, net_pay,
       performance_score, reviewed, reviewed_by, reviewed_at, review_note,
       overtime_hours, overtime_hourly_rate, overtime_hourly_amount
FROM payroll_lines
WHERE payroll_period_id = $1 AND employee_id = $2
`

type GetPayrollLineByPeriodEmployeeParams struct {
	PayrollPeriodID pgtype.UUID `json:"payroll_period_id"`
	EmployeeID      pgtype.UUID `json:"employee_id"`
}

func (q *Queries) GetPayrollLineByPeriodEmployee(ctx context.Context, arg *GetPayrollLineByPeriodEmployeeParams) (*PayrollLine, error) {
	row := q.db.QueryRow(ctx, getPayrollLineByPeriodEmployee, arg.PayrollPeriodID, arg.EmployeeID)
	var i PayrollLine
	err := row.Scan(
		&i.ID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.WageStructureID,
		&i.BaseSalary,
		&i.DailyRate,
		&i.OvertimeDays,
		&i.PublicHolidayDays,
		&i.OvertimeAmount,
		&i.PublicHolidayAmount,
		&i.AllowanceTotal,
		&i.BonusTotal,
		&i.ComponentDeductionTotal,
		&i.KasbonDeduction,
		&i.UnpaidLeaveDays,
		&i.UnpaidLeaveDeduction,
		&i.GrossPay,
		&i.NetPay,
		&i.PerformanceScore,
		&i.Reviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.OvertimeHours,
		&i.OvertimeHourlyRate,
		&i.OvertimeHourlyAmount,
	)
	return &i, err
}

const getPayrollLineForPayslip = `-- name: GetPayrollLineForPayslip :one

SELECT
    l.id, l.payroll_period_id, l.employee_id,
    l.base_salary, l.daily_rate,
    l.overtime_days, l.public_holiday_days, l.overtime_amount, l.public_holiday_amount,
    l.allowance_total, l.bonus_total, l.component_deduction_total, l.kasbon_deduction,
    l.unpaid_leave_days, l.unpaid_leave_deduction, l.gross_pay, l.net_pay, l.review_note,
    l.overtime_hours, l.overtime_hourly_rate, l.overtime_hourly_amount,
    e.full_name AS employee_name, e.employee_code, e.join_date,
    pos.name AS position_name,
    b.name   AS branch_name,
    p.period_month, p.status AS period_status
FROM payroll_lines l
JOIN payroll_periods p ON p.id = l.payroll_period_id
JOIN employees e       ON e.id = l.employee_id
LEFT JOIN positions pos ON pos.id = e.position_id
LEFT JOIN branches  b   ON b.id  = e.branch_id
WHERE l.id = $1
`

type GetPayrollLineForPayslipRow struct {
	ID                      pgtype.UUID    `json:"id"`
	PayrollPeriodID         pgtype.UUID    `json:"payroll_period_id"`
	EmployeeID              pgtype.UUID    `json:"employee_id"`
	BaseSalary              int64          `json:"base_salary"`
	DailyRate               int64          `json:"daily_rate"`
	OvertimeDays            pgtype.Numeric `json:"overtime_days"`
	PublicHolidayDays       pgtype.Numeric `json:"public_holiday_days"`
	OvertimeAmount          int64          `json:"overtime_amount"`
	PublicHolidayAmount     int64          `json:"public_holiday_amount"`
	AllowanceTotal          int64          `json:"allowance_total"`
	BonusTotal              int64          `json:"bonus_total"`
	ComponentDeductionTotal int64          `json:"component_deduction_total"`
	KasbonDeduction         int64          `json:"kasbon_deduction"`
	UnpaidLeaveDays         int32          `json:"unpaid_leave_days"`
	UnpaidLeaveDeduction    int64          `json:"unpaid_leave_deduction"`
	GrossPay                int64          `json:"gross_pay"`
	NetPay                  int64          `json:"net_pay"`
	ReviewNote              pgtype.Text    `json:"review_note"`
	OvertimeHours           pgtype.Numeric `json:"overtime_hours"`
	OvertimeHourlyRate      int64          `json:"overtime_hourly_rate"`
	OvertimeHourlyAmount    int64          `json:"overtime_hourly_amount"`
	EmployeeName            string         `json:"employee_name"`
	EmployeeCode            string         `json:"employee_code"`
	JoinDate                pgtype.Date    `json:"join_date"`
	PositionName            pgtype.Text    `json:"position_name"`
	BranchName              pgtype.Text    `json:"branch_name"`
	PeriodMonth             pgtype.Date    `json:"period_month"`
	PeriodStatus            string         `json:"period_status"`
}

// ── Payslip rendering (prompt 09) ────────────────────────────────────────────
// One denormalised row with everything the PDF payslip needs: the line snapshot
// plus employee identity (name/code/join date), position name, branch name and the
// period month. Components are fetched separately via ListPayrollLineComponents.
func (q *Queries) GetPayrollLineForPayslip(ctx context.Context, id pgtype.UUID) (*GetPayrollLineForPayslipRow, error) {
	row := q.db.QueryRow(ctx, getPayrollLineForPayslip, id)
	var i GetPayrollLineForPayslipRow
	err := row.Scan(
		&i.ID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.BaseSalary,
		&i.DailyRate,
		&i.OvertimeDays,
		&i.PublicHolidayDays,
		&i.OvertimeAmount,
		&i.PublicHolidayAmount,
		&i.AllowanceTotal,
		&i.BonusTotal,
		&i.ComponentDeductionTotal,
		&i.KasbonDeduction,
		&i.UnpaidLeaveDays,
		&i.UnpaidLeaveDeduction,
		&i.GrossPay,
		&i.NetPay,
		&i.ReviewNote,
		&i.OvertimeHours,
		&i.OvertimeHourlyRate,
		&i.OvertimeHourlyAmount,
		&i.EmployeeName,
		&i.EmployeeCode,
		&i.JoinDate,
		&i.PositionName,
		&i.BranchName,
		&i.PeriodMonth,
		&i.PeriodStatus,
	)
	return &i, err
}

const getPayrollPeriodByID = `-- name: GetPayrollPeriodByID :one
SELECT id, period_month, start_date, end_date, status, created_by, closed_at, paid_at, created_at
FROM payroll_periods
WHERE id = $1
`

func (q *Queries) GetPayrollPeriodByID(ctx context.Context, id pgtype.UUID) (*PayrollPeriod, error) {
	row := q.db.QueryRow(ctx, getPayrollPeriodByID, id)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodMonth,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.ClosedAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getPayrollPeriodByMonth = `-- name: GetPayrollPeriodByMonth :one
SELECT id, period_month, start_date, end_date, status, created_by, closed_at, paid_at, created_at
FROM payroll_periods
WHERE period_month = $1
`

func (q *Queries) GetPayrollPeriodByMonth(ctx context.Context, periodMonth pgtype.Date) (*PayrollPeriod, error) {
	row := q.db.QueryRow(ctx, getPayrollPeriodByMonth, periodMonth)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodMonth,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.ClosedAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getPayrollPeriodSummary = `-- name: GetPayrollPeriodSummary :one
SELECT
    COALESCE(SUM(l.gross_pay), 0)::bigint AS total_gross,
    COALESCE(SUM(l.net_pay), 0)::bigint AS total_net,
    COALESCE(SUM(l.component_deduction_total + l.kasbon_deduction + l.unpaid_leave_deduction), 0)::bigint AS total_deductions,
    COUNT(l.id)::int AS line_count,
    COUNT(l.id) FILTER (WHERE l.reviewed)::int AS reviewed_count
FROM payroll_lines l
WHERE l.payroll_period_id = $1
`

type GetPayrollPeriodSummaryRow struct {
	TotalGross      int64 `json:"total_gross"`
	TotalNet        int64 `json:"total_net"`
	TotalDeductions int64 `json:"total_deductions"`
	LineCount       int32 `json:"line_count"`
	ReviewedCount   int32 `json:"reviewed_count"`
}

func (q *Queries) GetPayrollPeriodSummary(ctx context.Context, payrollPeriodID pgtype.UUID) (*GetPayrollPeriodSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPayrollPeriodSummary, payrollPeriodID)
	var i GetPayrollPeriodSummaryRow
	err := row.Scan(
		&i.TotalGross,
		&i.TotalNet,
		&i.TotalDeductions,
		&i.LineCount,
		&i.ReviewedCount,
	)
	return &i, err
}

const getPayrollSettings = `-- name: GetPayrollSettings :one

SELECT id, overtime_multiplier, holiday_multiplier
FROM payroll_settings
WHERE id = 1
`

// ── Payroll Settings ─────────────────────────────────────────────────────────
func (q *Queries) GetPayrollSettings(ctx context.Context) (*PayrollSetting, error) {
	row := q.db.QueryRow(ctx, getPayrollSettings)
	var i PayrollSetting
	err := row.Scan(&i.ID, &i.OvertimeMultiplier, &i.HolidayMultiplier)
	return &i, err
}

const listActiveEmployeesForPayroll = `-- name: ListActiveEmployeesForPayroll :many
SELECT id, employee_code, full_name, branch_id, position_id
FROM employees
WHERE status = 'active'
ORDER BY full_name
`

type ListActiveEmployeesForPayrollRow struct {
	ID           pgtype.UUID `json:"id"`
	EmployeeCode string      `json:"employee_code"`
	FullName     string      `json:"full_name"`
	BranchID     pgtype.UUID `json:"branch_id"`
	PositionID   pgtype.UUID `json:"position_id"`
}

func (q *Queries) ListActiveEmployeesForPayroll(ctx context.Context) ([]*ListActiveEmployeesForPayrollRow, error) {
	rows, err := q.db.Query(ctx, listActiveEmployeesForPayroll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActiveEmployeesForPayrollRow
	for rows.Next() {
		var i ListActiveEmployeesForPayrollRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.FullName,
			&i.BranchID,
			&i.PositionID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineKasbonNumbers = `-- name: ListLineKasbonNumbers :many
SELECT DISTINCT k.kasbon_number
FROM kasbon_installments ki
JOIN kasbons k ON k.id = ki.kasbon_id
WHERE ki.payroll_line_id = $1
ORDER BY k.kasbon_number
`

// Kasbon numbers whose installments were deducted on this payroll line. Populated
// only after the period is closed (installments are marked deducted at close), so a
// payslip may legitimately show none and fall back to a generic "Kasbon" label.
func (q *Queries) ListLineKasbonNumbers(ctx context.Context, payrollLineID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listLineKasbonNumbers, payrollLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var kasbon_number string
		if err := rows.Scan(&kasbon_number); err != nil {
			return nil, err
		}
		items = append(items, kasbon_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollLineBranchTotals = `-- name: ListPayrollLineBranchTotals :many
SELECT e.branch_id, COALESCE(SUM(l.gross_pay), 0)::bigint AS total_gross,
       COALESCE(SUM(l.net_pay), 0)::bigint AS total_net
FROM payroll_lines l
JOIN employees e ON e.id = l.employee_id
WHERE l.payroll_period_id = $1
GROUP BY e.branch_id
`

type ListPayrollLineBranchTotalsRow struct {
	BranchID   pgtype.UUID `json:"branch_id"`
	TotalGross int64       `json:"total_gross"`
	TotalNet   int64       `json:"total_net"`
}

func (q *Queries) ListPayrollLineBranchTotals(ctx context.Context, payrollPeriodID pgtype.UUID) ([]*ListPayrollLineBranchTotalsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollLineBranchTotals, payrollPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPayrollLineBranchTotalsRow
	for rows.Next() {
		var i ListPayrollLineBranchTotalsRow
		if err := rows.Scan(&i.BranchID, &i.TotalGross, &i.TotalNet); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollLineComponents = `-- name: ListPayrollLineComponents :many
SELECT id, payroll_line_id, wage_component_id, name, type, amount
FROM payroll_line_components
WHERE payroll_line_id = $1
ORDER BY type, name
`

func (q *Queries) ListPayrollLineComponents(ctx context.Context, payrollLineID pgtype.UUID) ([]*PayrollLineComponent, error) {
	rows, err := q.db.Query(ctx, listPayrollLineComponents, payrollLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PayrollLineComponent
	for rows.Next() {
		var i PayrollLineComponent
		if err := rows.Scan(
			&i.ID,
			&i.PayrollLineID,
			&i.WageComponentID,
			&i.Name,
			&i.Type,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollLinesForPeriod = `-- name: ListPayrollLinesForPeriod :many
SELECT
    l.id, l.payroll_period_id, l.employee_id, l.wage_structure_id, l.base_salary, l.daily_rate,
    l.overtime_days, l.public_holiday_days, l.overtime_amount, l.public_holiday_amount,
    l.allowance_total, l.bonus_total, l.component_deduction_total, l.kasbon_deduction,
    l.unpaid_leave_days, l.unpaid_leave_deduction, l.gross_pay, l.net_pay,
    l.performance_score, l.reviewed, l.reviewed_by, l.reviewed_at, l.review_note,
    l.overtime_hours, l.overtime_hourly_rate, l.overtime_hourly_amount,
    e.full_name AS employee_name, e.employee_code,
    e.position_id, pos.name AS position_name,
    e.branch_id, b.name AS branch_name
FROM payroll_lines l
JOIN employees e ON e.id = l.employee_id
LEFT JOIN positions pos ON pos.id = e.position_id
LEFT JOIN branches b ON b.id = e.branch_id
WHERE l.payroll_period_id = $1
  AND ($2::text = '' OR lower(e.full_name) LIKE '%' || lower($2) || '%'
       OR lower(e.employee_code) LIKE '%' || lower($2) || '%')
  AND ($3::uuid IS NULL OR e.position_id = $3)
  AND ($4::uuid IS NULL OR e.branch_id = $4)
ORDER BY
    CASE WHEN $5::text = 'net_pay' AND $6::text = 'asc'  THEN l.net_pay END ASC,
    CASE WHEN $5::text = 'net_pay' AND $6::text = 'desc' THEN l.net_pay END DESC,
    CASE WHEN $5::text = 'name'    AND $6::text = 'desc' THEN e.full_name END DESC,
    e.full_name ASC
`

type ListPayrollLinesForPeriodParams struct {
	PayrollPeriodID pgtype.UUID `json:"payroll_period_id"`
	Q               string      `json:"q"`
	PositionID      pgtype.UUID `json:"position_id"`
	BranchID        pgtype.UUID `json:"branch_id"`
	Sort            string      `json:"sort"`
	Order           string      `json:"order"`
}

type ListPayrollLinesForPeriodRow struct {
	ID                      pgtype.UUID        `json:"id"`
	PayrollPeriodID         pgtype.UUID        `json:"payroll_period_id"`
	EmployeeID              pgtype.UUID        `json:"employee_id"`
	WageStructureID         pgtype.UUID        `json:"wage_structure_id"`
	BaseSalary              int64              `json:"base_salary"`
	DailyRate               int64              `json:"daily_rate"`
	OvertimeDays            pgtype.Numeric     `json:"overtime_days"`
	PublicHolidayDays       pgtype.Numeric     `json:"public_holiday_days"`
	OvertimeAmount          int64              `json:"overtime_amount"`
	PublicHolidayAmount     int64              `json:"public_holiday_amount"`
	AllowanceTotal          int64              `json:"allowance_total"`
	BonusTotal              int64              `json:"bonus_total"`
	ComponentDeductionTotal int64              `json:"component_deduction_total"`
	KasbonDeduction         int64              `json:"kasbon_deduction"`
	UnpaidLeaveDays         int32              `json:"unpaid_leave_days"`
	UnpaidLeaveDeduction    int64              `json:"unpaid_leave_deduction"`
	GrossPay                int64              `json:"gross_pay"`
	NetPay                  int64              `json:"net_pay"`
	PerformanceScore        pgtype.Int4        `json:"performance_score"`
	Reviewed                bool               `json:"reviewed"`
	ReviewedBy              pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNote              pgtype.Text        `json:"review_note"`
	OvertimeHours           pgtype.Numeric     `json:"overtime_hours"`
	OvertimeHourlyRate      int64              `json:"overtime_hourly_rate"`
	OvertimeHourlyAmount    int64              `json:"overtime_hourly_amount"`
	EmployeeName            string             `json:"employee_name"`
	EmployeeCode            string             `json:"employee_code"`
	PositionID              pgtype.UUID        `json:"position_id"`
	PositionName            pgtype.Text        `json:"position_name"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchName              pgtype.Text        `json:"branch_name"`
}

func (q *Queries) ListPayrollLinesForPeriod(ctx context.Context, arg *ListPayrollLinesForPeriodParams) ([]*ListPayrollLinesForPeriodRow, error) {
	rows, err := q.db.Query(ctx, listPayrollLinesForPeriod,
		arg.PayrollPeriodID,
		arg.Q,
		arg.PositionID,
		arg.BranchID,
		arg.Sort,
		arg.Order,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPayrollLinesForPeriodRow
	for rows.Next() {
		var i ListPayrollLinesForPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.PayrollPeriodID,
			&i.EmployeeID,
			&i.WageStructureID,
			&i.BaseSalary,
			&i.DailyRate,
			&i.OvertimeDays,
			&i.PublicHolidayDays,
			&i.OvertimeAmount,
			&i.PublicHolidayAmount,
			&i.AllowanceTotal,
			&i.BonusTotal,
			&i.ComponentDeductionTotal,
			&i.KasbonDeduction,
			&i.UnpaidLeaveDays,
			&i.UnpaidLeaveDeduction,
			&i.GrossPay,
			&i.NetPay,
			&i.PerformanceScore,
			&i.Reviewed,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.OvertimeHours,
			&i.OvertimeHourlyRate,
			&i.OvertimeHourlyAmount,
			&i.EmployeeName,
			&i.EmployeeCode,
			&i.PositionID,
			&i.PositionName,
			&i.BranchID,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPeriods = `-- name: ListPayrollPeriods :many
SELECT
    p.id, p.period_month, p.start_date, p.end_date, p.status, p.created_by,
    p.closed_at, p.paid_at, p.created_at,
    COALESCE(SUM(l.net_pay), 0)::bigint        AS total_net,
    COALESCE(SUM(l.gross_pay), 0)::bigint       AS total_gross,
    COUNT(l.id)::int                            AS line_count,
    COUNT(l.id) FILTER (WHERE l.reviewed)::int  AS reviewed_count
FROM payroll_periods p
LEFT JOIN payroll_lines l ON l.payroll_period_id = p.id
GROUP BY p.id
ORDER BY p.period_month DESC
`

type ListPayrollPeriodsRow struct {
	ID            pgtype.UUID        `json:"id"`
	PeriodMonth   pgtype.Date        `json:"period_month"`
	StartDate     pgtype.Date        `json:"start_date"`
	EndDate       pgtype.Date        `json:"end_date"`
	Status        string             `json:"status"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TotalNet      int64              `json:"total_net"`
	TotalGross    int64              `json:"total_gross"`
	LineCount     int32              `json:"line_count"`
	ReviewedCount int32              `json:"reviewed_count"`
}

func (q *Queries) ListPayrollPeriods(ctx context.Context) ([]*ListPayrollPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPayrollPeriodsRow
	for rows.Next() {
		var i ListPayrollPeriodsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodMonth,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedBy,
			&i.ClosedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.TotalNet,
			&i.TotalGross,
			&i.LineCount,
			&i.ReviewedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPayrollPeriodPaid = `-- name: MarkPayrollPeriodPaid :one
UPDATE payroll_periods
SET status = 'paid', paid_at = now()
WHERE id = $1
RETURNING id, period_month, start_date, end_date, status, created_by, closed_at, paid_at, created_at
`

func (q *Queries) MarkPayrollPeriodPaid(ctx context.Context, id pgtype.UUID) (*PayrollPeriod, error) {
	row := q.db.QueryRow(ctx, markPayrollPeriodPaid, id)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodMonth,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.ClosedAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return &i, err
}

const unreviewPayrollLine = `-- name: UnreviewPayrollLine :one
UPDATE payroll_lines
SET reviewed = false, reviewed_by = NULL, reviewed_at = NULL
WHERE id = $1
RETURNING id, payroll_period_id, employee_id, wage_structure_id, base_salary, daily_rate,
          overtime_days, public_holiday_days, overtime_amount, public_holiday_amount,
          allowance_total, bonus_total, component_deduction_total, kasbon_deduction,
          unpaid_leave_days, unpaid_leave_deduction, gross_pay, net_pay,
          performance_score, reviewed, reviewed_by, reviewed_at, review_note,
          overtime_hours, overtime_hourly_rate, overtime_hourly_amount
`

func (q *Queries) UnreviewPayrollLine(ctx context.Context, id pgtype.UUID) (*PayrollLine, error) {
	row := q.db.QueryRow(ctx, unreviewPayrollLine, id)
	var i PayrollLine
	err := row.Scan(
		&i.ID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.WageStructureID,
		&i.BaseSalary,
		&i.DailyRate,
		&i.OvertimeDays,
		&i.PublicHolidayDays,
		&i.OvertimeAmount,
		&i.PublicHolidayAmount,
		&i.AllowanceTotal,
		&i.BonusTotal,
		&i.ComponentDeductionTotal,
		&i.KasbonDeduction,
		&i.UnpaidLeaveDays,
		&i.UnpaidLeaveDeduction,
		&i.GrossPay,
		&i.NetPay,
		&i.PerformanceScore,
		&i.Reviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.OvertimeHours,
		&i.OvertimeHourlyRate,
		&i.OvertimeHourlyAmount,
	)
	return &i, err
}

const getBonusEligibleLines = `-- name: GetBonusEligibleLines :many
SELECT
    l.id              AS line_id,
    plc.id            AS line_component_id,
    plc.name          AS component_name,
    plc.amount        AS current_amount,
    l.employee_id,
    e.full_name       AS employee_name,
    e.employee_code,
    l.performance_score,
    l.reviewed
FROM payroll_line_components plc
JOIN payroll_lines l  ON l.id  = plc.payroll_line_id
JOIN employees     e  ON e.id  = l.employee_id
WHERE l.payroll_period_id = $1
  AND plc.wage_component_id = $2
  AND plc.type = 'bonus'
ORDER BY e.full_name
`

type GetBonusEligibleLinesParams struct {
	PayrollPeriodID pgtype.UUID `json:"payroll_period_id"`
	WageComponentID pgtype.UUID `json:"wage_component_id"`
}

type GetBonusEligibleLinesRow struct {
	LineID           pgtype.UUID `json:"line_id"`
	LineComponentID  pgtype.UUID `json:"line_component_id"`
	ComponentName    string      `json:"component_name"`
	CurrentAmount    int64       `json:"current_amount"`
	EmployeeID       pgtype.UUID `json:"employee_id"`
	EmployeeName     string      `json:"employee_name"`
	EmployeeCode     string      `json:"employee_code"`
	PerformanceScore pgtype.Int4 `json:"performance_score"`
	Reviewed         bool        `json:"reviewed"`
}

func (q *Queries) GetBonusEligibleLines(ctx context.Context, arg *GetBonusEligibleLinesParams) ([]*GetBonusEligibleLinesRow, error) {
	rows, err := q.db.Query(ctx, getBonusEligibleLines, arg.PayrollPeriodID, arg.WageComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetBonusEligibleLinesRow
	for rows.Next() {
		var i GetBonusEligibleLinesRow
		if err := rows.Scan(
			&i.LineID,
			&i.LineComponentID,
			&i.ComponentName,
			&i.CurrentAmount,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.EmployeeCode,
			&i.PerformanceScore,
			&i.Reviewed,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayrollLineTotals = `-- name: UpdatePayrollLineTotals :exec
UPDATE payroll_lines
SET bonus_total = $1,
    gross_pay   = $2,
    net_pay     = $3
WHERE id = $4
`

type UpdatePayrollLineTotalsParams struct {
	BonusTotal int64       `json:"bonus_total"`
	GrossPay   int64       `json:"gross_pay"`
	NetPay     int64       `json:"net_pay"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePayrollLineTotals(ctx context.Context, arg *UpdatePayrollLineTotalsParams) error {
	_, err := q.db.Exec(ctx, updatePayrollLineTotals, arg.BonusTotal, arg.GrossPay, arg.NetPay, arg.ID)
	return err
}

const updatePayrollLineComponentAmount = `-- name: UpdatePayrollLineComponentAmount :exec
UPDATE payroll_line_components
SET amount = $1
WHERE id = $2
`

type UpdatePayrollLineComponentAmountParams struct {
	Amount int64       `json:"amount"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePayrollLineComponentAmount(ctx context.Context, arg *UpdatePayrollLineComponentAmountParams) error {
	_, err := q.db.Exec(ctx, updatePayrollLineComponentAmount, arg.Amount, arg.ID)
	return err
}

const updatePayrollLineReview = `-- name: UpdatePayrollLineReview :one
UPDATE payroll_lines
SET overtime_days = $1, public_holiday_days = $2,
    overtime_amount = $3, public_holiday_amount = $4,
    bonus_total = $5, gross_pay = $6, net_pay = $7,
    reviewed = true, reviewed_by = $8, reviewed_at = now(), review_note = $9,
    overtime_hours = $10, overtime_hourly_amount = $11, allowance_total = $12
WHERE id = $13
RETURNING id, payroll_period_id, employee_id, wage_structure_id, base_salary, daily_rate,
          overtime_days, public_holiday_days, overtime_amount, public_holiday_amount,
          allowance_total, bonus_total, component_deduction_total, kasbon_deduction,
          unpaid_leave_days, unpaid_leave_deduction, gross_pay, net_pay,
          performance_score, reviewed, reviewed_by, reviewed_at, review_note,
          overtime_hours, overtime_hourly_rate, overtime_hourly_amount
`

type UpdatePayrollLineReviewParams struct {
	OvertimeDays         pgtype.Numeric `json:"overtime_days"`
	PublicHolidayDays    pgtype.Numeric `json:"public_holiday_days"`
	OvertimeAmount       int64          `json:"overtime_amount"`
	PublicHolidayAmount  int64          `json:"public_holiday_amount"`
	BonusTotal           int64          `json:"bonus_total"`
	GrossPay             int64          `json:"gross_pay"`
	NetPay               int64          `json:"net_pay"`
	ReviewedBy           pgtype.UUID    `json:"reviewed_by"`
	ReviewNote           pgtype.Text    `json:"review_note"`
	OvertimeHours        pgtype.Numeric `json:"overtime_hours"`
	OvertimeHourlyAmount int64          `json:"overtime_hourly_amount"`
	AllowanceTotal       int64          `json:"allowance_total"`
	ID                   pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdatePayrollLineReview(ctx context.Context, arg *UpdatePayrollLineReviewParams) (*PayrollLine, error) {
	row := q.db.QueryRow(ctx, updatePayrollLineReview,
		arg.OvertimeDays,
		arg.PublicHolidayDays,
		arg.OvertimeAmount,
		arg.PublicHolidayAmount,
		arg.BonusTotal,
		arg.GrossPay,
		arg.NetPay,
		arg.ReviewedBy,
		arg.ReviewNote,
		arg.OvertimeHours,
		arg.OvertimeHourlyAmount,
		arg.AllowanceTotal,
		arg.ID,
	)
	var i PayrollLine
	err := row.Scan(
		&i.ID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.WageStructureID,
		&i.BaseSalary,
		&i.DailyRate,
		&i.OvertimeDays,
		&i.PublicHolidayDays,
		&i.OvertimeAmount,
		&i.PublicHolidayAmount,
		&i.AllowanceTotal,
		&i.BonusTotal,
		&i.ComponentDeductionTotal,
		&i.KasbonDeduction,
		&i.UnpaidLeaveDays,
		&i.UnpaidLeaveDeduction,
		&i.GrossPay,
		&i.NetPay,
		&i.PerformanceScore,
		&i.Reviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.OvertimeHours,
		&i.OvertimeHourlyRate,
		&i.OvertimeHourlyAmount,
	)
	return &i, err
}
