// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_performance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPolicyOccurrencesInMonth = `-- name: CountPolicyOccurrencesInMonth :one
SELECT COUNT(*)
FROM performance_violations
WHERE policy_id = $1
  AND employee_id = $2
  AND date >= $3
  AND date < ($3::date + INTERVAL '1 month')
`

type CountPolicyOccurrencesInMonthParams struct {
	PolicyID   pgtype.UUID `json:"policy_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) CountPolicyOccurrencesInMonth(ctx context.Context, arg *CountPolicyOccurrencesInMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicyOccurrencesInMonth, arg.PolicyID, arg.EmployeeID, arg.Date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAbsentDaysBeforeInMonth = `-- name: CountAbsentDaysBeforeInMonth :one
SELECT COUNT(*)
FROM attendance_records
WHERE employee_id = $1
  AND status = 'absent'
  AND date >= $2
  AND date < $3
`

type CountAbsentDaysBeforeInMonthParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	MonthStart pgtype.Date `json:"month_start"`
	BeforeDate pgtype.Date `json:"before_date"`
}

// Number of 'absent' attendance days the employee already has in the month,
// strictly before before_date. Used to apply the monthly absence grace: the
// first N absent days each month carry no performance violation.
func (q *Queries) CountAbsentDaysBeforeInMonth(ctx context.Context, arg *CountAbsentDaysBeforeInMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAbsentDaysBeforeInMonth, arg.EmployeeID, arg.MonthStart, arg.BeforeDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPolicyViolations = `-- name: CountPolicyViolations :one
SELECT COUNT(*) FROM performance_violations WHERE policy_id = $1
`

func (q *Queries) CountPolicyViolations(ctx context.Context, policyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicyViolations, policyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerformancePolicy = `-- name: CreatePerformancePolicy :one
INSERT INTO performance_policies (id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6)
RETURNING id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active, created_at
`

type CreatePerformancePolicyParams struct {
	Name                   string      `json:"name"`
	RuleType               string      `json:"rule_type"`
	ThresholdMinutes       pgtype.Int4 `json:"threshold_minutes"`
	Points                 int32       `json:"points"`
	MaxOccurrencesPerMonth pgtype.Int4 `json:"max_occurrences_per_month"`
	IsActive               bool        `json:"is_active"`
}

func (q *Queries) CreatePerformancePolicy(ctx context.Context, arg *CreatePerformancePolicyParams) (*PerformancePolicy, error) {
	row := q.db.QueryRow(ctx, createPerformancePolicy,
		arg.Name,
		arg.RuleType,
		arg.ThresholdMinutes,
		arg.Points,
		arg.MaxOccurrencesPerMonth,
		arg.IsActive,
	)
	var i PerformancePolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.ThresholdMinutes,
		&i.Points,
		&i.MaxOccurrencesPerMonth,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteAutoViolationsByRecord = `-- name: DeleteAutoViolationsByRecord :exec
DELETE FROM performance_violations
WHERE attendance_record_id = $1 AND source = 'auto'
`

func (q *Queries) DeleteAutoViolationsByRecord(ctx context.Context, attendanceRecordID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAutoViolationsByRecord, attendanceRecordID)
	return err
}

const deleteAutoViolationsForRange = `-- name: DeleteAutoViolationsForRange :exec
DELETE FROM performance_violations
WHERE source = 'auto'
  AND date >= $1
  AND date <= $2
`

type DeleteAutoViolationsForRangeParams struct {
	From pgtype.Date `json:"from"`
	To   pgtype.Date `json:"to"`
}

func (q *Queries) DeleteAutoViolationsForRange(ctx context.Context, arg *DeleteAutoViolationsForRangeParams) error {
	_, err := q.db.Exec(ctx, deleteAutoViolationsForRange, arg.From, arg.To)
	return err
}

const deletePerformancePolicy = `-- name: DeletePerformancePolicy :exec
DELETE FROM performance_policies WHERE id = $1
`

func (q *Queries) DeletePerformancePolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerformancePolicy, id)
	return err
}

const deleteViolation = `-- name: DeleteViolation :exec
DELETE FROM performance_violations WHERE id = $1
`

func (q *Queries) DeleteViolation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteViolation, id)
	return err
}

const getPerformancePolicyByID = `-- name: GetPerformancePolicyByID :one
SELECT id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active, created_at
FROM performance_policies
WHERE id = $1
`

func (q *Queries) GetPerformancePolicyByID(ctx context.Context, id pgtype.UUID) (*PerformancePolicy, error) {
	row := q.db.QueryRow(ctx, getPerformancePolicyByID, id)
	var i PerformancePolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.ThresholdMinutes,
		&i.Points,
		&i.MaxOccurrencesPerMonth,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const getPerformanceScore = `-- name: GetPerformanceScore :one
SELECT id, employee_id, period_month, score
FROM performance_scores
WHERE employee_id = $1 AND period_month = $2
`

type GetPerformanceScoreParams struct {
	EmployeeID  pgtype.UUID `json:"employee_id"`
	PeriodMonth pgtype.Date `json:"period_month"`
}

func (q *Queries) GetPerformanceScore(ctx context.Context, arg *GetPerformanceScoreParams) (*PerformanceScore, error) {
	row := q.db.QueryRow(ctx, getPerformanceScore, arg.EmployeeID, arg.PeriodMonth)
	var i PerformanceScore
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PeriodMonth,
		&i.Score,
	)
	return &i, err
}

const getViolationByID = `-- name: GetViolationByID :one
SELECT id, employee_id, policy_id, attendance_record_id, date, points, source, note, created_by, created_at
FROM performance_violations
WHERE id = $1
`

func (q *Queries) GetViolationByID(ctx context.Context, id pgtype.UUID) (*PerformanceViolation, error) {
	row := q.db.QueryRow(ctx, getViolationByID, id)
	var i PerformanceViolation
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PolicyID,
		&i.AttendanceRecordID,
		&i.Date,
		&i.Points,
		&i.Source,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const insertAutoViolation = `-- name: InsertAutoViolation :exec
INSERT INTO performance_violations (id, employee_id, policy_id, attendance_record_id, date, points, source, note)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, 'auto', $6)
ON CONFLICT (policy_id, attendance_record_id) DO NOTHING
`

type InsertAutoViolationParams struct {
	EmployeeID         pgtype.UUID `json:"employee_id"`
	PolicyID           pgtype.UUID `json:"policy_id"`
	AttendanceRecordID pgtype.UUID `json:"attendance_record_id"`
	Date               pgtype.Date `json:"date"`
	Points             int32       `json:"points"`
	Note               pgtype.Text `json:"note"`
}

func (q *Queries) InsertAutoViolation(ctx context.Context, arg *InsertAutoViolationParams) error {
	_, err := q.db.Exec(ctx, insertAutoViolation,
		arg.EmployeeID,
		arg.PolicyID,
		arg.AttendanceRecordID,
		arg.Date,
		arg.Points,
		arg.Note,
	)
	return err
}

const insertManualViolation = `-- name: InsertManualViolation :one
INSERT INTO performance_violations (id, employee_id, policy_id, attendance_record_id, date, points, source, note, created_by)
VALUES (gen_random_uuid(), $1, NULL, NULL, $2, $3, 'manual', $4, $5)
RETURNING id, employee_id, policy_id, attendance_record_id, date, points, source, note, created_by, created_at
`

type InsertManualViolationParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
	Points     int32       `json:"points"`
	Note       pgtype.Text `json:"note"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertManualViolation(ctx context.Context, arg *InsertManualViolationParams) (*PerformanceViolation, error) {
	row := q.db.QueryRow(ctx, insertManualViolation,
		arg.EmployeeID,
		arg.Date,
		arg.Points,
		arg.Note,
		arg.CreatedBy,
	)
	var i PerformanceViolation
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PolicyID,
		&i.AttendanceRecordID,
		&i.Date,
		&i.Points,
		&i.Source,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const listActivePerformancePoliciesByRule = `-- name: ListActivePerformancePoliciesByRule :many
SELECT id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active, created_at
FROM performance_policies
WHERE is_active = true AND rule_type = $1
ORDER BY threshold_minutes NULLS FIRST
`

func (q *Queries) ListActivePerformancePoliciesByRule(ctx context.Context, ruleType string) ([]*PerformancePolicy, error) {
	rows, err := q.db.Query(ctx, listActivePerformancePoliciesByRule, ruleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PerformancePolicy
	for rows.Next() {
		var i PerformancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuleType,
			&i.ThresholdMinutes,
			&i.Points,
			&i.MaxOccurrencesPerMonth,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceRecordsForDate = `-- name: ListAttendanceRecordsForDate :many
SELECT id, employee_id, date, check_in, check_out, check_in_source, check_out_source,
       check_in_photo_path, device_id, status, is_late, late_minutes,
       is_early_leave, early_leave_minutes, is_missing_checkout, note,
       is_half_day, half_day_lost_minutes
FROM attendance_records
WHERE date = $1
`

func (q *Queries) ListAttendanceRecordsForDate(ctx context.Context, date pgtype.Date) ([]*AttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listAttendanceRecordsForDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AttendanceRecord
	for rows.Next() {
		var i AttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Date,
			&i.CheckIn,
			&i.CheckOut,
			&i.CheckInSource,
			&i.CheckOutSource,
			&i.CheckInPhotoPath,
			&i.DeviceID,
			&i.Status,
			&i.IsLate,
			&i.LateMinutes,
			&i.IsEarlyLeave,
			&i.EarlyLeaveMinutes,
			&i.IsMissingCheckout,
			&i.Note,
			&i.IsHalfDay,
			&i.HalfDayLostMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformancePolicies = `-- name: ListPerformancePolicies :many
SELECT id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active, created_at
FROM performance_policies
ORDER BY rule_type, threshold_minutes NULLS FIRST, name
`

func (q *Queries) ListPerformancePolicies(ctx context.Context) ([]*PerformancePolicy, error) {
	rows, err := q.db.Query(ctx, listPerformancePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PerformancePolicy
	for rows.Next() {
		var i PerformancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuleType,
			&i.ThresholdMinutes,
			&i.Points,
			&i.MaxOccurrencesPerMonth,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationsForEmployeeMonth = `-- name: ListViolationsForEmployeeMonth :many
SELECT v.id, v.employee_id, v.policy_id, v.attendance_record_id, v.date, v.points,
       v.source, v.note, v.created_by, v.created_at,
       p.name AS policy_name, p.rule_type AS rule_type
FROM performance_violations v
LEFT JOIN performance_policies p ON p.id = v.policy_id
WHERE v.employee_id = $1
  AND v.date >= $2
  AND v.date < ($2::date + INTERVAL '1 month')
ORDER BY v.date, v.created_at
`

type ListViolationsForEmployeeMonthParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

type ListViolationsForEmployeeMonthRow struct {
	ID                 pgtype.UUID        `json:"id"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	PolicyID           pgtype.UUID        `json:"policy_id"`
	AttendanceRecordID pgtype.UUID        `json:"attendance_record_id"`
	Date               pgtype.Date        `json:"date"`
	Points             int32              `json:"points"`
	Source             string             `json:"source"`
	Note               pgtype.Text        `json:"note"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PolicyName         pgtype.Text        `json:"policy_name"`
	RuleType           pgtype.Text        `json:"rule_type"`
}

func (q *Queries) ListViolationsForEmployeeMonth(ctx context.Context, arg *ListViolationsForEmployeeMonthParams) ([]*ListViolationsForEmployeeMonthRow, error) {
	rows, err := q.db.Query(ctx, listViolationsForEmployeeMonth, arg.EmployeeID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListViolationsForEmployeeMonthRow
	for rows.Next() {
		var i ListViolationsForEmployeeMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.PolicyID,
			&i.AttendanceRecordID,
			&i.Date,
			&i.Points,
			&i.Source,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PolicyName,
			&i.RuleType,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPerformancePolicyActive = `-- name: SetPerformancePolicyActive :one
UPDATE performance_policies
SET is_active = $1
WHERE id = $2
RETURNING id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active, created_at
`

type SetPerformancePolicyActiveParams struct {
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetPerformancePolicyActive(ctx context.Context, arg *SetPerformancePolicyActiveParams) (*PerformancePolicy, error) {
	row := q.db.QueryRow(ctx, setPerformancePolicyActive, arg.IsActive, arg.ID)
	var i PerformancePolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.ThresholdMinutes,
		&i.Points,
		&i.MaxOccurrencesPerMonth,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const sumViolationPointsInMonth = `-- name: SumViolationPointsInMonth :one
SELECT COALESCE(SUM(points), 0)::int AS total
FROM performance_violations
WHERE employee_id = $1
  AND date >= $2
  AND date < ($2::date + INTERVAL '1 month')
`

type SumViolationPointsInMonthParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) SumViolationPointsInMonth(ctx context.Context, arg *SumViolationPointsInMonthParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumViolationPointsInMonth, arg.EmployeeID, arg.Date)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const updatePerformancePolicy = `-- name: UpdatePerformancePolicy :one
UPDATE performance_policies
SET name = $1, rule_type = $2, threshold_minutes = $3, points = $4,
    max_occurrences_per_month = $5, is_active = $6
WHERE id = $7
RETURNING id, name, rule_type, threshold_minutes, points, max_occurrences_per_month, is_active, created_at
`

type UpdatePerformancePolicyParams struct {
	Name                   string      `json:"name"`
	RuleType               string      `json:"rule_type"`
	ThresholdMinutes       pgtype.Int4 `json:"threshold_minutes"`
	Points                 int32       `json:"points"`
	MaxOccurrencesPerMonth pgtype.Int4 `json:"max_occurrences_per_month"`
	IsActive               bool        `json:"is_active"`
	ID                     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePerformancePolicy(ctx context.Context, arg *UpdatePerformancePolicyParams) (*PerformancePolicy, error) {
	row := q.db.QueryRow(ctx, updatePerformancePolicy,
		arg.Name,
		arg.RuleType,
		arg.ThresholdMinutes,
		arg.Points,
		arg.MaxOccurrencesPerMonth,
		arg.IsActive,
		arg.ID,
	)
	var i PerformancePolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.ThresholdMinutes,
		&i.Points,
		&i.MaxOccurrencesPerMonth,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertPerformanceScore = `-- name: UpsertPerformanceScore :one
INSERT INTO performance_scores (id, employee_id, period_month, score)
VALUES (gen_random_uuid(), $1, $2, $3)
ON CONFLICT (employee_id, period_month) DO UPDATE SET score = EXCLUDED.score
RETURNING id, employee_id, period_month, score
`

type UpsertPerformanceScoreParams struct {
	EmployeeID  pgtype.UUID `json:"employee_id"`
	PeriodMonth pgtype.Date `json:"period_month"`
	Score       int32       `json:"score"`
}

func (q *Queries) UpsertPerformanceScore(ctx context.Context, arg *UpsertPerformanceScoreParams) (*PerformanceScore, error) {
	row := q.db.QueryRow(ctx, upsertPerformanceScore, arg.EmployeeID, arg.PeriodMonth, arg.Score)
	var i PerformanceScore
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PeriodMonth,
		&i.Score,
	)
	return &i, err
}
