// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHRSettings = `-- name: GetHRSettings :one
SELECT id, company_name, address, logo_path, payslip_footer, absence_grace_days, updated_at
FROM hr_settings
WHERE id = 1
`

func (q *Queries) GetHRSettings(ctx context.Context) (*HrSetting, error) {
	row := q.db.QueryRow(ctx, getHRSettings)
	var i HrSetting
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.Address,
		&i.LogoPath,
		&i.PayslipFooter,
		&i.AbsenceGraceDays,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateHRSettings = `-- name: UpdateHRSettings :one
INSERT INTO hr_settings (id, company_name, address, payslip_footer, absence_grace_days, updated_at)
VALUES (1, $1, $2, $3, $4, now())
ON CONFLICT (id) DO UPDATE
SET company_name = $1, address = $2, payslip_footer = $3, absence_grace_days = $4, updated_at = now()
RETURNING id, company_name, address, logo_path, payslip_footer, absence_grace_days, updated_at
`

type UpdateHRSettingsParams struct {
	CompanyName      string `json:"company_name"`
	Address          string `json:"address"`
	PayslipFooter    string `json:"payslip_footer"`
	AbsenceGraceDays int32  `json:"absence_grace_days"`
}

func (q *Queries) UpdateHRSettings(ctx context.Context, arg *UpdateHRSettingsParams) (*HrSetting, error) {
	row := q.db.QueryRow(ctx, updateHRSettings,
		arg.CompanyName,
		arg.Address,
		arg.PayslipFooter,
		arg.AbsenceGraceDays,
	)
	var i HrSetting
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.Address,
		&i.LogoPath,
		&i.PayslipFooter,
		&i.AbsenceGraceDays,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateHRSettingsLogo = `-- name: UpdateHRSettingsLogo :one
UPDATE hr_settings
SET logo_path = $1, updated_at = now()
WHERE id = 1
RETURNING id, company_name, address, logo_path, payslip_footer, absence_grace_days, updated_at
`

func (q *Queries) UpdateHRSettingsLogo(ctx context.Context, logoPath pgtype.Text) (*HrSetting, error) {
	row := q.db.QueryRow(ctx, updateHRSettingsLogo, logoPath)
	var i HrSetting
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.Address,
		&i.LogoPath,
		&i.PayslipFooter,
		&i.AbsenceGraceDays,
		&i.UpdatedAt,
	)
	return &i, err
}
