// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_wages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOpenWageStructure = `-- name: CloseOpenWageStructure :exec
UPDATE wage_structures
SET end_date = $1
WHERE employee_id = $2 AND end_date IS NULL
`

type CloseOpenWageStructureParams struct {
	EndDate    pgtype.Date `json:"end_date"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) CloseOpenWageStructure(ctx context.Context, arg *CloseOpenWageStructureParams) error {
	_, err := q.db.Exec(ctx, closeOpenWageStructure, arg.EndDate, arg.EmployeeID)
	return err
}

const countWageComponentReferences = `-- name: CountWageComponentReferences :one
SELECT COUNT(*) FROM employee_wage_components WHERE wage_component_id = $1
`

func (q *Queries) CountWageComponentReferences(ctx context.Context, wageComponentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWageComponentReferences, wageComponentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployeeWageComponent = `-- name: CreateEmployeeWageComponent :one
INSERT INTO employee_wage_components (id, wage_structure_id, wage_component_id, amount)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, wage_structure_id, wage_component_id, amount
`

type CreateEmployeeWageComponentParams struct {
	WageStructureID pgtype.UUID `json:"wage_structure_id"`
	WageComponentID pgtype.UUID `json:"wage_component_id"`
	Amount          int64       `json:"amount"`
}

func (q *Queries) CreateEmployeeWageComponent(ctx context.Context, arg *CreateEmployeeWageComponentParams) (*EmployeeWageComponent, error) {
	row := q.db.QueryRow(ctx, createEmployeeWageComponent, arg.WageStructureID, arg.WageComponentID, arg.Amount)
	var i EmployeeWageComponent
	err := row.Scan(
		&i.ID,
		&i.WageStructureID,
		&i.WageComponentID,
		&i.Amount,
	)
	return &i, err
}

const createWageComponent = `-- name: CreateWageComponent :one
INSERT INTO wage_components (id, name, type, is_fixed, is_active)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, name, type, is_fixed, is_active, created_at
`

type CreateWageComponentParams struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	IsFixed  bool   `json:"is_fixed"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateWageComponent(ctx context.Context, arg *CreateWageComponentParams) (*WageComponent, error) {
	row := q.db.QueryRow(ctx, createWageComponent,
		arg.Name,
		arg.Type,
		arg.IsFixed,
		arg.IsActive,
	)
	var i WageComponent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsFixed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const createWageStructure = `-- name: CreateWageStructure :one
INSERT INTO wage_structures (
    id, employee_id, base_salary, working_days_per_month, daily_rate,
    effective_date, end_date, created_by
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, NULL, $6)
RETURNING id, employee_id, base_salary, working_days_per_month, daily_rate, effective_date, end_date, created_by, created_at
`

type CreateWageStructureParams struct {
	EmployeeID          pgtype.UUID `json:"employee_id"`
	BaseSalary          int64       `json:"base_salary"`
	WorkingDaysPerMonth int32       `json:"working_days_per_month"`
	DailyRate           int64       `json:"daily_rate"`
	EffectiveDate       pgtype.Date `json:"effective_date"`
	CreatedBy           pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWageStructure(ctx context.Context, arg *CreateWageStructureParams) (*WageStructure, error) {
	row := q.db.QueryRow(ctx, createWageStructure,
		arg.EmployeeID,
		arg.BaseSalary,
		arg.WorkingDaysPerMonth,
		arg.DailyRate,
		arg.EffectiveDate,
		arg.CreatedBy,
	)
	var i WageStructure
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.BaseSalary,
		&i.WorkingDaysPerMonth,
		&i.DailyRate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteWageComponent = `-- name: DeleteWageComponent :exec
DELETE FROM wage_components WHERE id = $1
`

func (q *Queries) DeleteWageComponent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWageComponent, id)
	return err
}

const getCurrentOpenWageStructure = `-- name: GetCurrentOpenWageStructure :one
SELECT id, employee_id, base_salary, working_days_per_month, daily_rate,
       effective_date, end_date, created_by, created_at
FROM wage_structures
WHERE employee_id = $1 AND end_date IS NULL
`

func (q *Queries) GetCurrentOpenWageStructure(ctx context.Context, employeeID pgtype.UUID) (*WageStructure, error) {
	row := q.db.QueryRow(ctx, getCurrentOpenWageStructure, employeeID)
	var i WageStructure
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.BaseSalary,
		&i.WorkingDaysPerMonth,
		&i.DailyRate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getWageComponentByID = `-- name: GetWageComponentByID :one
SELECT id, name, type, is_fixed, is_active, created_at
FROM wage_components
WHERE id = $1
`

func (q *Queries) GetWageComponentByID(ctx context.Context, id pgtype.UUID) (*WageComponent, error) {
	row := q.db.QueryRow(ctx, getWageComponentByID, id)
	var i WageComponent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsFixed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const getWageStructureAsOf = `-- name: GetWageStructureAsOf :one
SELECT id, employee_id, base_salary, working_days_per_month, daily_rate,
       effective_date, end_date, created_by, created_at
FROM wage_structures
WHERE employee_id = $1
  AND effective_date <= $2
  AND (end_date IS NULL OR end_date >= $2)
ORDER BY effective_date DESC
LIMIT 1
`

type GetWageStructureAsOfParams struct {
	EmployeeID    pgtype.UUID `json:"employee_id"`
	EffectiveDate pgtype.Date `json:"effective_date"`
}

func (q *Queries) GetWageStructureAsOf(ctx context.Context, arg *GetWageStructureAsOfParams) (*WageStructure, error) {
	row := q.db.QueryRow(ctx, getWageStructureAsOf, arg.EmployeeID, arg.EffectiveDate)
	var i WageStructure
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.BaseSalary,
		&i.WorkingDaysPerMonth,
		&i.DailyRate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const listActiveWageComponents = `-- name: ListActiveWageComponents :many
SELECT id, name, type, is_fixed, is_active, created_at
FROM wage_components
WHERE is_active = true
ORDER BY type, name
`

func (q *Queries) ListActiveWageComponents(ctx context.Context) ([]*WageComponent, error) {
	rows, err := q.db.Query(ctx, listActiveWageComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WageComponent
	for rows.Next() {
		var i WageComponent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IsFixed,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeWageComponents = `-- name: ListEmployeeWageComponents :many
SELECT ewc.id, ewc.wage_structure_id, ewc.wage_component_id, ewc.amount,
       wc.name AS component_name, wc.type AS component_type, wc.is_fixed AS component_is_fixed
FROM employee_wage_components ewc
JOIN wage_components wc ON wc.id = ewc.wage_component_id
WHERE ewc.wage_structure_id = $1
ORDER BY wc.type, wc.name
`

type ListEmployeeWageComponentsRow struct {
	ID               pgtype.UUID `json:"id"`
	WageStructureID  pgtype.UUID `json:"wage_structure_id"`
	WageComponentID  pgtype.UUID `json:"wage_component_id"`
	Amount           int64       `json:"amount"`
	ComponentName    string      `json:"component_name"`
	ComponentType    string      `json:"component_type"`
	ComponentIsFixed bool        `json:"component_is_fixed"`
}

func (q *Queries) ListEmployeeWageComponents(ctx context.Context, wageStructureID pgtype.UUID) ([]*ListEmployeeWageComponentsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeWageComponents, wageStructureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListEmployeeWageComponentsRow
	for rows.Next() {
		var i ListEmployeeWageComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WageStructureID,
			&i.WageComponentID,
			&i.Amount,
			&i.ComponentName,
			&i.ComponentType,
			&i.ComponentIsFixed,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWageComponents = `-- name: ListWageComponents :many
SELECT id, name, type, is_fixed, is_active, created_at
FROM wage_components
ORDER BY type, name
`

func (q *Queries) ListWageComponents(ctx context.Context) ([]*WageComponent, error) {
	rows, err := q.db.Query(ctx, listWageComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WageComponent
	for rows.Next() {
		var i WageComponent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IsFixed,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWageStructuresByEmployee = `-- name: ListWageStructuresByEmployee :many
SELECT id, employee_id, base_salary, working_days_per_month, daily_rate,
       effective_date, end_date, created_by, created_at
FROM wage_structures
WHERE employee_id = $1
ORDER BY effective_date DESC
`

func (q *Queries) ListWageStructuresByEmployee(ctx context.Context, employeeID pgtype.UUID) ([]*WageStructure, error) {
	rows, err := q.db.Query(ctx, listWageStructuresByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WageStructure
	for rows.Next() {
		var i WageStructure
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.BaseSalary,
			&i.WorkingDaysPerMonth,
			&i.DailyRate,
			&i.EffectiveDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWageComponentActive = `-- name: SetWageComponentActive :one
UPDATE wage_components
SET is_active = $1
WHERE id = $2
RETURNING id, name, type, is_fixed, is_active, created_at
`

type SetWageComponentActiveParams struct {
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetWageComponentActive(ctx context.Context, arg *SetWageComponentActiveParams) (*WageComponent, error) {
	row := q.db.QueryRow(ctx, setWageComponentActive, arg.IsActive, arg.ID)
	var i WageComponent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsFixed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const updateWageComponent = `-- name: UpdateWageComponent :one
UPDATE wage_components
SET name = $1, type = $2, is_fixed = $3, is_active = $4
WHERE id = $5
RETURNING id, name, type, is_fixed, is_active, created_at
`

type UpdateWageComponentParams struct {
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	IsFixed  bool        `json:"is_fixed"`
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWageComponent(ctx context.Context, arg *UpdateWageComponentParams) (*WageComponent, error) {
	row := q.db.QueryRow(ctx, updateWageComponent,
		arg.Name,
		arg.Type,
		arg.IsFixed,
		arg.IsActive,
		arg.ID,
	)
	var i WageComponent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsFixed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}
