// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const depleteInventoryLot = `-- name: DepleteInventoryLot :exec
UPDATE inventory
SET quantity = 0, value = 0, depleted_at = COALESCE(depleted_at, now())
WHERE id = $1
`

func (q *Queries) DepleteInventoryLot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, depleteInventoryLot, id)
	return err
}

const insertLotConsumption = `-- name: InsertLotConsumption :exec
INSERT INTO inventory_lot_consumptions (
    id, lot_id, item_id, warehouse_id, quantity, value,
    source_type, source_id, reference, date
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertLotConsumptionParams struct {
	LotID       pgtype.UUID    `json:"lot_id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	Value       int64          `json:"value"`
	SourceType  pgtype.Text    `json:"source_type"`
	SourceID    pgtype.UUID    `json:"source_id"`
	Reference   string         `json:"reference"`
	Date        pgtype.Date    `json:"date"`
}

func (q *Queries) InsertLotConsumption(ctx context.Context, arg *InsertLotConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertLotConsumption,
		arg.LotID,
		arg.ItemID,
		arg.WarehouseID,
		arg.Quantity,
		arg.Value,
		arg.SourceType,
		arg.SourceID,
		arg.Reference,
		arg.Date,
	)
	return err
}

const getLotConsumptions = `-- name: GetLotConsumptions :many
SELECT
    c.id, c.quantity, c.value, c.source_type, c.source_id, c.reference, c.date, c.created_at,
    COALESCE(b.name, dv.name, w.name, '')::text AS destination
FROM inventory_lot_consumptions c
LEFT JOIN dispatches d   ON c.source_type = 'dispatch' AND d.id = c.source_id
LEFT JOIN branches b     ON b.id = d.branch_id
LEFT JOIN divisions dv   ON dv.id = d.division_id
LEFT JOIN stock_transfers st ON c.source_type = 'stock_transfer' AND st.id = c.source_id
LEFT JOIN warehouses w   ON w.id = st.to_warehouse_id
WHERE c.lot_id = $1
ORDER BY c.date, c.created_at
`

type GetLotConsumptionsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	Value       int64              `json:"value"`
	SourceType  pgtype.Text        `json:"source_type"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Reference   string             `json:"reference"`
	Date        pgtype.Date        `json:"date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Destination string             `json:"destination"`
}

func (q *Queries) GetLotConsumptions(ctx context.Context, lotID pgtype.UUID) ([]*GetLotConsumptionsRow, error) {
	rows, err := q.db.Query(ctx, getLotConsumptions, lotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetLotConsumptionsRow
	for rows.Next() {
		var i GetLotConsumptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Value,
			&i.SourceType,
			&i.SourceID,
			&i.Reference,
			&i.Date,
			&i.CreatedAt,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryLotDetail = `-- name: GetInventoryLotDetail :one
SELECT
    inv.id, inv.item_id, inv.warehouse_id, inv.quantity, inv.unit_index,
    inv.value, inv.date, inv.created_at, inv.depleted_at,
    i.name AS item_name, i.code AS item_code, i.units AS item_units, i.is_stock,
    w.name AS warehouse_name,
    (SELECT sh.reference FROM stock_history sh
      WHERE sh.item_id = inv.item_id AND sh.warehouse_id = inv.warehouse_id
        AND sh.quantity_change > 0 AND sh.date = inv.date
      ORDER BY sh.created_at LIMIT 1)::text AS opening_reference,
    (SELECT sh.vendor FROM stock_history sh
      WHERE sh.item_id = inv.item_id AND sh.warehouse_id = inv.warehouse_id
        AND sh.quantity_change > 0 AND sh.date = inv.date
      ORDER BY sh.created_at LIMIT 1)::text AS opening_vendor,
    COALESCE((SELECT SUM(c.quantity) FROM inventory_lot_consumptions c WHERE c.lot_id = inv.id), 0)::numeric AS consumed_quantity,
    COALESCE((SELECT SUM(c.value)    FROM inventory_lot_consumptions c WHERE c.lot_id = inv.id), 0)::bigint  AS consumed_value
FROM inventory inv
JOIN items i ON i.id = inv.item_id
JOIN warehouses w ON w.id = inv.warehouse_id
WHERE inv.id = $1
`

type GetInventoryLotDetailRow struct {
	ID               pgtype.UUID        `json:"id"`
	ItemID           pgtype.UUID        `json:"item_id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitIndex        int32              `json:"unit_index"`
	Value            int64              `json:"value"`
	Date             pgtype.Date        `json:"date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DepletedAt       pgtype.Timestamptz `json:"depleted_at"`
	ItemName         string             `json:"item_name"`
	ItemCode         string             `json:"item_code"`
	ItemUnits        []byte             `json:"item_units"`
	IsStock          bool               `json:"is_stock"`
	WarehouseName    string             `json:"warehouse_name"`
	OpeningReference string             `json:"opening_reference"`
	OpeningVendor    string             `json:"opening_vendor"`
	ConsumedQuantity pgtype.Numeric     `json:"consumed_quantity"`
	ConsumedValue    int64              `json:"consumed_value"`
}

func (q *Queries) GetInventoryLotDetail(ctx context.Context, id pgtype.UUID) (*GetInventoryLotDetailRow, error) {
	row := q.db.QueryRow(ctx, getInventoryLotDetail, id)
	var i GetInventoryLotDetailRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WarehouseID,
		&i.Quantity,
		&i.UnitIndex,
		&i.Value,
		&i.Date,
		&i.CreatedAt,
		&i.DepletedAt,
		&i.ItemName,
		&i.ItemCode,
		&i.ItemUnits,
		&i.IsStock,
		&i.WarehouseName,
		&i.OpeningReference,
		&i.OpeningVendor,
		&i.ConsumedQuantity,
		&i.ConsumedValue,
	)
	return &i, err
}
