// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInventory = `-- name: CountInventory :one
SELECT COUNT(*)
FROM inventory inv
JOIN items i ON i.id = inv.item_id
WHERE ($1::uuid IS NULL OR inv.warehouse_id = $1)
  AND ($2::uuid IS NULL OR inv.item_id = $2)
  AND ($3::text IS NULL OR i.name ILIKE '%' || $3 || '%' OR i.code ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR inv.date >= $4)
  AND ($5::date IS NULL OR inv.date <= $5)
`

type CountInventoryParams struct {
	WarehouseID pgtype.UUID `json:"warehouse_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Search      pgtype.Text `json:"search"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
}

func (q *Queries) CountInventory(ctx context.Context, arg *CountInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventory,
		arg.WarehouseID,
		arg.ItemID,
		arg.Search,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryLot = `-- name: CreateInventoryLot :one
INSERT INTO inventory (id, item_id, warehouse_id, quantity, unit_index, value, date)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6)
RETURNING id, item_id, warehouse_id, quantity, unit_index, value, date
`

type CreateInventoryLotParams struct {
	ItemID      pgtype.UUID    `json:"item_id"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   int32          `json:"unit_index"`
	Value       int64          `json:"value"`
	Date        pgtype.Date    `json:"date"`
}

type CreateInventoryLotRow struct {
	ID          pgtype.UUID    `json:"id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   int32          `json:"unit_index"`
	Value       int64          `json:"value"`
	Date        pgtype.Date    `json:"date"`
}

func (q *Queries) CreateInventoryLot(ctx context.Context, arg *CreateInventoryLotParams) (*CreateInventoryLotRow, error) {
	row := q.db.QueryRow(ctx, createInventoryLot,
		arg.ItemID,
		arg.WarehouseID,
		arg.Quantity,
		arg.UnitIndex,
		arg.Value,
		arg.Date,
	)
	var i CreateInventoryLotRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WarehouseID,
		&i.Quantity,
		&i.UnitIndex,
		&i.Value,
		&i.Date,
	)
	return &i, err
}

const deleteInventoryLot = `-- name: DeleteInventoryLot :exec
DELETE FROM inventory WHERE id = $1
`

func (q *Queries) DeleteInventoryLot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryLot, id)
	return err
}

const getInventoryByID = `-- name: GetInventoryByID :one
SELECT
    inv.id, inv.item_id, inv.warehouse_id, inv.quantity,
    inv.unit_index, inv.value, inv.date,
    i.name AS item_name, i.code AS item_code, i.units AS item_units,
    w.name AS warehouse_name
FROM inventory inv
JOIN items i ON i.id = inv.item_id
JOIN warehouses w ON w.id = inv.warehouse_id
WHERE inv.id = $1
`

type GetInventoryByIDRow struct {
	ID            pgtype.UUID    `json:"id"`
	ItemID        pgtype.UUID    `json:"item_id"`
	WarehouseID   pgtype.UUID    `json:"warehouse_id"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitIndex     int32          `json:"unit_index"`
	Value         int64          `json:"value"`
	Date          pgtype.Date    `json:"date"`
	ItemName      string         `json:"item_name"`
	ItemCode      string         `json:"item_code"`
	ItemUnits     []byte         `json:"item_units"`
	WarehouseName string         `json:"warehouse_name"`
}

func (q *Queries) GetInventoryByID(ctx context.Context, id pgtype.UUID) (*GetInventoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getInventoryByID, id)
	var i GetInventoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WarehouseID,
		&i.Quantity,
		&i.UnitIndex,
		&i.Value,
		&i.Date,
		&i.ItemName,
		&i.ItemCode,
		&i.ItemUnits,
		&i.WarehouseName,
	)
	return &i, err
}

const getInventoryLotValue = `-- name: GetInventoryLotValue :one
SELECT value FROM inventory WHERE id = $1
`

func (q *Queries) GetInventoryLotValue(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getInventoryLotValue, id)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const getInventoryLotsForFIFO = `-- name: GetInventoryLotsForFIFO :many
SELECT id, quantity, value, date, unit_index
FROM inventory
WHERE item_id = $1 AND warehouse_id = $2 AND quantity > 0
ORDER BY date ASC, created_at ASC, id ASC
`

type GetInventoryLotsForFIFOParams struct {
	ItemID      pgtype.UUID `json:"item_id"`
	WarehouseID pgtype.UUID `json:"warehouse_id"`
}

type GetInventoryLotsForFIFORow struct {
	ID        pgtype.UUID    `json:"id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	Value     int64          `json:"value"`
	Date      pgtype.Date    `json:"date"`
	UnitIndex int32          `json:"unit_index"`
}

func (q *Queries) GetInventoryLotsForFIFO(ctx context.Context, arg *GetInventoryLotsForFIFOParams) ([]*GetInventoryLotsForFIFORow, error) {
	rows, err := q.db.Query(ctx, getInventoryLotsForFIFO, arg.ItemID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetInventoryLotsForFIFORow
	for rows.Next() {
		var i GetInventoryLotsForFIFORow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Value,
			&i.Date,
			&i.UnitIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemInventorySummary = `-- name: GetItemInventorySummary :many
SELECT
    item_id, warehouse_id,
    SUM(quantity) AS total_quantity,
    SUM(value) AS total_value
FROM inventory
WHERE item_id = $1
GROUP BY item_id, warehouse_id
`

type GetItemInventorySummaryRow struct {
	ItemID        pgtype.UUID `json:"item_id"`
	WarehouseID   pgtype.UUID `json:"warehouse_id"`
	TotalQuantity int64       `json:"total_quantity"`
	TotalValue    int64       `json:"total_value"`
}

func (q *Queries) GetItemInventorySummary(ctx context.Context, itemID pgtype.UUID) ([]*GetItemInventorySummaryRow, error) {
	rows, err := q.db.Query(ctx, getItemInventorySummary, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetItemInventorySummaryRow
	for rows.Next() {
		var i GetItemInventorySummaryRow
		if err := rows.Scan(
			&i.ItemID,
			&i.WarehouseID,
			&i.TotalQuantity,
			&i.TotalValue,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventory = `-- name: ListInventory :many
SELECT
    inv.id, inv.item_id, inv.warehouse_id, inv.quantity,
    inv.unit_index, inv.value, inv.date,
    i.name AS item_name, i.code AS item_code, i.units AS item_units,
    w.name AS warehouse_name
FROM inventory inv
JOIN items i ON i.id = inv.item_id
JOIN warehouses w ON w.id = inv.warehouse_id
WHERE ($1::uuid IS NULL OR inv.warehouse_id = $1)
  AND ($2::uuid IS NULL OR inv.item_id = $2)
ORDER BY i.name, w.name, inv.date ASC
`

type ListInventoryParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

type ListInventoryRow struct {
	ID            pgtype.UUID    `json:"id"`
	ItemID        pgtype.UUID    `json:"item_id"`
	WarehouseID   pgtype.UUID    `json:"warehouse_id"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitIndex     int32          `json:"unit_index"`
	Value         int64          `json:"value"`
	Date          pgtype.Date    `json:"date"`
	ItemName      string         `json:"item_name"`
	ItemCode      string         `json:"item_code"`
	ItemUnits     []byte         `json:"item_units"`
	WarehouseName string         `json:"warehouse_name"`
}

func (q *Queries) ListInventory(ctx context.Context, arg *ListInventoryParams) ([]*ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListInventoryRow
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WarehouseID,
			&i.Quantity,
			&i.UnitIndex,
			&i.Value,
			&i.Date,
			&i.ItemName,
			&i.ItemCode,
			&i.ItemUnits,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryPage = `-- name: ListInventoryPage :many
SELECT
    inv.id, inv.item_id, inv.warehouse_id, inv.quantity,
    inv.unit_index, inv.date,
    i.name AS item_name, i.code AS item_code, i.units AS item_units,
    w.name AS warehouse_name
FROM inventory inv
JOIN items i ON i.id = inv.item_id
JOIN warehouses w ON w.id = inv.warehouse_id
WHERE ($1::uuid IS NULL OR inv.warehouse_id = $1)
  AND ($2::uuid IS NULL OR inv.item_id = $2)
  AND ($3::text IS NULL OR i.name ILIKE '%' || $3 || '%' OR i.code ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR inv.date >= $4)
  AND ($5::date IS NULL OR inv.date <= $5)
ORDER BY i.name, w.name, inv.date ASC
LIMIT $7 OFFSET $6
`

type ListInventoryPageParams struct {
	WarehouseID pgtype.UUID `json:"warehouse_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Search      pgtype.Text `json:"search"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

type ListInventoryPageRow struct {
	ID            pgtype.UUID    `json:"id"`
	ItemID        pgtype.UUID    `json:"item_id"`
	WarehouseID   pgtype.UUID    `json:"warehouse_id"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitIndex     int32          `json:"unit_index"`
	Date          pgtype.Date    `json:"date"`
	ItemName      string         `json:"item_name"`
	ItemCode      string         `json:"item_code"`
	ItemUnits     []byte         `json:"item_units"`
	WarehouseName string         `json:"warehouse_name"`
}

func (q *Queries) ListInventoryPage(ctx context.Context, arg *ListInventoryPageParams) ([]*ListInventoryPageRow, error) {
	rows, err := q.db.Query(ctx, listInventoryPage,
		arg.WarehouseID,
		arg.ItemID,
		arg.Search,
		arg.DateFrom,
		arg.DateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListInventoryPageRow
	for rows.Next() {
		var i ListInventoryPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WarehouseID,
			&i.Quantity,
			&i.UnitIndex,
			&i.Date,
			&i.ItemName,
			&i.ItemCode,
			&i.ItemUnits,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryLot = `-- name: UpdateInventoryLot :exec
UPDATE inventory SET quantity = $1, value = $2, date = $3 WHERE id = $4
`

type UpdateInventoryLotParams struct {
	Quantity pgtype.Numeric `json:"quantity"`
	Value    int64          `json:"value"`
	Date     pgtype.Date    `json:"date"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateInventoryLot(ctx context.Context, arg *UpdateInventoryLotParams) error {
	_, err := q.db.Exec(ctx, updateInventoryLot,
		arg.Quantity,
		arg.Value,
		arg.Date,
		arg.ID,
	)
	return err
}

const updateInventoryLotQuantity = `-- name: UpdateInventoryLotQuantity :exec
UPDATE inventory SET quantity = $1, value = $2 WHERE id = $3
`

type UpdateInventoryLotQuantityParams struct {
	Quantity pgtype.Numeric `json:"quantity"`
	Value    int64          `json:"value"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateInventoryLotQuantity(ctx context.Context, arg *UpdateInventoryLotQuantityParams) error {
	_, err := q.db.Exec(ctx, updateInventoryLotQuantity, arg.Quantity, arg.Value, arg.ID)
	return err
}
