// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    id, invoice_number, date, due_date, invoice_type, payment_method,
    payment_status, amount_paid, account_id, warehouse_id, branch_id,
    division_id, vendor_id, reference_number
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, 0, $7, $8, $9, $10, $11, $12
)
RETURNING id, invoice_number, date, due_date, invoice_type, payment_status, created_at
`

type CreateInvoiceParams struct {
	InvoiceNumber   string      `json:"invoice_number"`
	Date            pgtype.Date `json:"date"`
	DueDate         pgtype.Date `json:"due_date"`
	InvoiceType     string      `json:"invoice_type"`
	PaymentMethod   pgtype.Text `json:"payment_method"`
	PaymentStatus   string      `json:"payment_status"`
	AccountID       pgtype.UUID `json:"account_id"`
	WarehouseID     pgtype.UUID `json:"warehouse_id"`
	BranchID        pgtype.UUID `json:"branch_id"`
	DivisionID      pgtype.UUID `json:"division_id"`
	VendorID        pgtype.UUID `json:"vendor_id"`
	ReferenceNumber pgtype.Text `json:"reference_number"`
}

type CreateInvoiceRow struct {
	ID            pgtype.UUID        `json:"id"`
	InvoiceNumber string             `json:"invoice_number"`
	Date          pgtype.Date        `json:"date"`
	DueDate       pgtype.Date        `json:"due_date"`
	InvoiceType   string             `json:"invoice_type"`
	PaymentStatus string             `json:"payment_status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg *CreateInvoiceParams) (*CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.Date,
		arg.DueDate,
		arg.InvoiceType,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.AccountID,
		arg.WarehouseID,
		arg.BranchID,
		arg.DivisionID,
		arg.VendorID,
		arg.ReferenceNumber,
	)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.Date,
		&i.DueDate,
		&i.InvoiceType,
		&i.PaymentStatus,
		&i.CreatedAt,
	)
	return &i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (id, invoice_id, item_id, vendor_id, quantity, unit_index, price, description)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateInvoiceItemParams struct {
	InvoiceID   pgtype.UUID    `json:"invoice_id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	VendorID    pgtype.UUID    `json:"vendor_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   pgtype.Int4    `json:"unit_index"`
	Price       int64          `json:"price"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg *CreateInvoiceItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.ItemID,
		arg.VendorID,
		arg.Quantity,
		arg.UnitIndex,
		arg.Price,
		arg.Description,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const deleteInvoiceItems = `-- name: DeleteInvoiceItems :exec
DELETE FROM invoice_items WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceItems(ctx context.Context, invoiceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItems, invoiceID)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT
    i.id, i.invoice_number, i.date, i.due_date, i.invoice_type,
    i.payment_method, i.payment_status, i.amount_paid, i.reference_number,
    i.photo_path, i.created_at, i.account_id,
    i.vendor_id, v.name AS vendor_name,
    i.warehouse_id, w.name AS warehouse_name,
    i.branch_id, b.name AS branch_name,
    i.division_id, d.name AS division_name,
    i.dispatch_id
FROM invoices i
LEFT JOIN vendors v ON v.id = i.vendor_id
LEFT JOIN warehouses w ON w.id = i.warehouse_id
LEFT JOIN branches b ON b.id = i.branch_id
LEFT JOIN divisions d ON d.id = i.division_id
WHERE i.id = $1
`

type GetInvoiceByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	InvoiceNumber   string             `json:"invoice_number"`
	Date            pgtype.Date        `json:"date"`
	DueDate         pgtype.Date        `json:"due_date"`
	InvoiceType     string             `json:"invoice_type"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	PaymentStatus   string             `json:"payment_status"`
	AmountPaid      int64              `json:"amount_paid"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	PhotoPath       pgtype.Text        `json:"photo_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AccountID       pgtype.UUID        `json:"account_id"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	VendorName      pgtype.Text        `json:"vendor_name"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	WarehouseName   pgtype.Text        `json:"warehouse_name"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	BranchName      pgtype.Text        `json:"branch_name"`
	DivisionID      pgtype.UUID        `json:"division_id"`
	DivisionName    pgtype.Text        `json:"division_name"`
	DispatchID      pgtype.UUID        `json:"dispatch_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (*GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.Date,
		&i.DueDate,
		&i.InvoiceType,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.AmountPaid,
		&i.ReferenceNumber,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.AccountID,
		&i.VendorID,
		&i.VendorName,
		&i.WarehouseID,
		&i.WarehouseName,
		&i.BranchID,
		&i.BranchName,
		&i.DivisionID,
		&i.DivisionName,
		&i.DispatchID,
	)
	return &i, err
}

const getInvoiceItems = `-- name: GetInvoiceItems :many
SELECT
    ii.id, ii.invoice_id, ii.item_id, ii.vendor_id,
    ii.quantity, ii.unit_index, ii.price, ii.description,
    it.name AS item_name, it.units AS item_units,
    v.name AS vendor_name
FROM invoice_items ii
LEFT JOIN items it ON it.id = ii.item_id
LEFT JOIN vendors v ON v.id = ii.vendor_id
WHERE ii.invoice_id = $1
ORDER BY ii.id
`

type GetInvoiceItemsRow struct {
	ID          pgtype.UUID    `json:"id"`
	InvoiceID   pgtype.UUID    `json:"invoice_id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	VendorID    pgtype.UUID    `json:"vendor_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   pgtype.Int4    `json:"unit_index"`
	Price       int64          `json:"price"`
	Description pgtype.Text    `json:"description"`
	ItemName    pgtype.Text    `json:"item_name"`
	ItemUnits   []byte         `json:"item_units"`
	VendorName  pgtype.Text    `json:"vendor_name"`
}

func (q *Queries) GetInvoiceItems(ctx context.Context, invoiceID pgtype.UUID) ([]*GetInvoiceItemsRow, error) {
	rows, err := q.db.Query(ctx, getInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetInvoiceItemsRow
	for rows.Next() {
		var i GetInvoiceItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ItemID,
			&i.VendorID,
			&i.Quantity,
			&i.UnitIndex,
			&i.Price,
			&i.Description,
			&i.ItemName,
			&i.ItemUnits,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceWithTotal = `-- name: GetInvoiceWithTotal :one
SELECT
    i.id, i.invoice_number, i.invoice_type, i.payment_status,
    i.amount_paid, i.account_id, i.warehouse_id, i.branch_id, i.division_id, i.dispatch_id,
    COALESCE(SUM(ii.price * ii.quantity), 0)::BIGINT AS total_amount
FROM invoices i
LEFT JOIN invoice_items ii ON ii.invoice_id = i.id
WHERE i.id = $1
GROUP BY i.id
`

type GetInvoiceWithTotalRow struct {
	ID            pgtype.UUID `json:"id"`
	InvoiceNumber string      `json:"invoice_number"`
	InvoiceType   string      `json:"invoice_type"`
	PaymentStatus string      `json:"payment_status"`
	AmountPaid    int64       `json:"amount_paid"`
	AccountID     pgtype.UUID `json:"account_id"`
	WarehouseID   pgtype.UUID `json:"warehouse_id"`
	BranchID      pgtype.UUID `json:"branch_id"`
	DivisionID    pgtype.UUID `json:"division_id"`
	DispatchID    pgtype.UUID `json:"dispatch_id"`
	TotalAmount   int64       `json:"total_amount"`
}

func (q *Queries) GetInvoiceWithTotal(ctx context.Context, id pgtype.UUID) (*GetInvoiceWithTotalRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceWithTotal, id)
	var i GetInvoiceWithTotalRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.InvoiceType,
		&i.PaymentStatus,
		&i.AmountPaid,
		&i.AccountID,
		&i.WarehouseID,
		&i.BranchID,
		&i.DivisionID,
		&i.DispatchID,
		&i.TotalAmount,
	)
	return &i, err
}

const getNextInvoiceNumber = `-- name: GetNextInvoiceNumber :one
SELECT 'INV-' || LPAD(nextval('invoice_seq')::text, 5, '0') AS invoice_number
`

func (q *Queries) GetNextInvoiceNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getNextInvoiceNumber)
	var invoice_number interface{}
	err := row.Scan(&invoice_number)
	return invoice_number, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT
    i.id, i.invoice_number, i.date, i.due_date, i.invoice_type,
    i.payment_method, i.payment_status, i.amount_paid, i.reference_number,
    i.photo_path, i.created_at,
    i.vendor_id, v.name AS vendor_name,
    i.warehouse_id, w.name AS warehouse_name,
    i.branch_id, b.name AS branch_name,
    i.account_id, a.name AS account_name,
    i.dispatch_id,
    COALESCE(SUM(ii.price * ii.quantity), 0)::BIGINT AS total_amount
FROM invoices i
LEFT JOIN vendors v ON v.id = i.vendor_id
LEFT JOIN warehouses w ON w.id = i.warehouse_id
LEFT JOIN branches b ON b.id = i.branch_id
LEFT JOIN accounts a ON a.id = i.account_id
LEFT JOIN invoice_items ii ON ii.invoice_id = i.id
WHERE (NULLIF($1, '')::text IS NULL OR i.invoice_type = $1)
  AND (NULLIF($2, '')::text IS NULL OR i.payment_status = $2)
  AND ($3::date IS NULL OR i.date >= $3)
  AND ($4::date IS NULL OR i.date <= $4)
  AND ($5::uuid IS NULL OR i.vendor_id = $5)
GROUP BY i.id, v.name, w.name, b.name, a.name
ORDER BY i.date DESC, i.created_at DESC
`

type ListInvoicesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Column4 pgtype.Date `json:"column_4"`
	Column5 pgtype.UUID `json:"column_5"`
}

type ListInvoicesRow struct {
	ID              pgtype.UUID        `json:"id"`
	InvoiceNumber   string             `json:"invoice_number"`
	Date            pgtype.Date        `json:"date"`
	DueDate         pgtype.Date        `json:"due_date"`
	InvoiceType     string             `json:"invoice_type"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	PaymentStatus   string             `json:"payment_status"`
	AmountPaid      int64              `json:"amount_paid"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	PhotoPath       pgtype.Text        `json:"photo_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	VendorName      pgtype.Text        `json:"vendor_name"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	WarehouseName   pgtype.Text        `json:"warehouse_name"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	BranchName      pgtype.Text        `json:"branch_name"`
	AccountID       pgtype.UUID        `json:"account_id"`
	AccountName     pgtype.Text        `json:"account_name"`
	DispatchID      pgtype.UUID        `json:"dispatch_id"`
	TotalAmount     int64              `json:"total_amount"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg *ListInvoicesParams) ([]*ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.Date,
			&i.DueDate,
			&i.InvoiceType,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.AmountPaid,
			&i.ReferenceNumber,
			&i.PhotoPath,
			&i.CreatedAt,
			&i.VendorID,
			&i.VendorName,
			&i.WarehouseID,
			&i.WarehouseName,
			&i.BranchID,
			&i.BranchName,
			&i.AccountID,
			&i.AccountName,
			&i.DispatchID,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvoiceDispatchID = `-- name: SetInvoiceDispatchID :exec
UPDATE invoices SET dispatch_id = $1 WHERE id = $2
`

type SetInvoiceDispatchIDParams struct {
	DispatchID pgtype.UUID `json:"dispatch_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) SetInvoiceDispatchID(ctx context.Context, arg *SetInvoiceDispatchIDParams) error {
	_, err := q.db.Exec(ctx, setInvoiceDispatchID, arg.DispatchID, arg.ID)
	return err
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices
SET date = $1, due_date = $2, payment_method = $3, account_id = $4,
    vendor_id = $5, reference_number = $6, warehouse_id = $7, branch_id = $8, division_id = $9
WHERE id = $10
RETURNING id
`

type UpdateInvoiceParams struct {
	Date            pgtype.Date `json:"date"`
	DueDate         pgtype.Date `json:"due_date"`
	PaymentMethod   pgtype.Text `json:"payment_method"`
	AccountID       pgtype.UUID `json:"account_id"`
	VendorID        pgtype.UUID `json:"vendor_id"`
	ReferenceNumber pgtype.Text `json:"reference_number"`
	WarehouseID     pgtype.UUID `json:"warehouse_id"`
	BranchID        pgtype.UUID `json:"branch_id"`
	DivisionID      pgtype.UUID `json:"division_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg *UpdateInvoiceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.Date,
		arg.DueDate,
		arg.PaymentMethod,
		arg.AccountID,
		arg.VendorID,
		arg.ReferenceNumber,
		arg.WarehouseID,
		arg.BranchID,
		arg.DivisionID,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateInvoicePayment = `-- name: UpdateInvoicePayment :one
UPDATE invoices
SET amount_paid = $1, payment_status = $2, account_id = $3
WHERE id = $4
RETURNING id, invoice_number, amount_paid, payment_status
`

type UpdateInvoicePaymentParams struct {
	AmountPaid    int64       `json:"amount_paid"`
	PaymentStatus string      `json:"payment_status"`
	AccountID     pgtype.UUID `json:"account_id"`
	ID            pgtype.UUID `json:"id"`
}

type UpdateInvoicePaymentRow struct {
	ID            pgtype.UUID `json:"id"`
	InvoiceNumber string      `json:"invoice_number"`
	AmountPaid    int64       `json:"amount_paid"`
	PaymentStatus string      `json:"payment_status"`
}

func (q *Queries) UpdateInvoicePayment(ctx context.Context, arg *UpdateInvoicePaymentParams) (*UpdateInvoicePaymentRow, error) {
	row := q.db.QueryRow(ctx, updateInvoicePayment,
		arg.AmountPaid,
		arg.PaymentStatus,
		arg.AccountID,
		arg.ID,
	)
	var i UpdateInvoicePaymentRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.AmountPaid,
		&i.PaymentStatus,
	)
	return &i, err
}

const updateInvoicePhotoPath = `-- name: UpdateInvoicePhotoPath :exec
UPDATE invoices SET photo_path = $1 WHERE id = $2
`

type UpdateInvoicePhotoPathParams struct {
	PhotoPath pgtype.Text `json:"photo_path"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateInvoicePhotoPath(ctx context.Context, arg *UpdateInvoicePhotoPathParams) error {
	_, err := q.db.Exec(ctx, updateInvoicePhotoPath, arg.PhotoPath, arg.ID)
	return err
}
