// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceTemplate = `-- name: CreateInvoiceTemplate :one
INSERT INTO invoice_templates (id, name, invoice_type, vendor_id, warehouse_id)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, name, invoice_type, vendor_id, warehouse_id, created_at
`

type CreateInvoiceTemplateParams struct {
	Name        string      `json:"name"`
	InvoiceType string      `json:"invoice_type"`
	VendorID    pgtype.UUID `json:"vendor_id"`
	WarehouseID pgtype.UUID `json:"warehouse_id"`
}

func (q *Queries) CreateInvoiceTemplate(ctx context.Context, arg *CreateInvoiceTemplateParams) (*InvoiceTemplate, error) {
	row := q.db.QueryRow(ctx, createInvoiceTemplate,
		arg.Name,
		arg.InvoiceType,
		arg.VendorID,
		arg.WarehouseID,
	)
	var i InvoiceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvoiceType,
		&i.VendorID,
		&i.WarehouseID,
		&i.CreatedAt,
	)
	return &i, err
}

const createInvoiceTemplateItem = `-- name: CreateInvoiceTemplateItem :one
INSERT INTO invoice_template_items (id, template_id, item_id, description, unit_index, sort_order)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, template_id, item_id, description, unit_index, sort_order
`

type CreateInvoiceTemplateItemParams struct {
	TemplateID  pgtype.UUID `json:"template_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Description pgtype.Text `json:"description"`
	UnitIndex   int32       `json:"unit_index"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) CreateInvoiceTemplateItem(ctx context.Context, arg *CreateInvoiceTemplateItemParams) (*InvoiceTemplateItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceTemplateItem,
		arg.TemplateID,
		arg.ItemID,
		arg.Description,
		arg.UnitIndex,
		arg.SortOrder,
	)
	var i InvoiceTemplateItem
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ItemID,
		&i.Description,
		&i.UnitIndex,
		&i.SortOrder,
	)
	return &i, err
}

const deleteInvoiceTemplate = `-- name: DeleteInvoiceTemplate :exec
DELETE FROM invoice_templates WHERE id = $1
`

func (q *Queries) DeleteInvoiceTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceTemplate, id)
	return err
}

const deleteInvoiceTemplateItems = `-- name: DeleteInvoiceTemplateItems :exec
DELETE FROM invoice_template_items WHERE template_id = $1
`

func (q *Queries) DeleteInvoiceTemplateItems(ctx context.Context, templateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceTemplateItems, templateID)
	return err
}

const getInvoiceTemplateByID = `-- name: GetInvoiceTemplateByID :one
SELECT
    t.id, t.name, t.invoice_type, t.vendor_id, t.warehouse_id, t.created_at,
    v.name AS vendor_name, w.name AS warehouse_name
FROM invoice_templates t
LEFT JOIN vendors v ON v.id = t.vendor_id
LEFT JOIN warehouses w ON w.id = t.warehouse_id
WHERE t.id = $1
`

type GetInvoiceTemplateByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	InvoiceType   string             `json:"invoice_type"`
	VendorID      pgtype.UUID        `json:"vendor_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	VendorName    pgtype.Text        `json:"vendor_name"`
	WarehouseName pgtype.Text        `json:"warehouse_name"`
}

func (q *Queries) GetInvoiceTemplateByID(ctx context.Context, id pgtype.UUID) (*GetInvoiceTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceTemplateByID, id)
	var i GetInvoiceTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvoiceType,
		&i.VendorID,
		&i.WarehouseID,
		&i.CreatedAt,
		&i.VendorName,
		&i.WarehouseName,
	)
	return &i, err
}

const getInvoiceTemplateItems = `-- name: GetInvoiceTemplateItems :many
SELECT
    ti.id, ti.template_id, ti.item_id, ti.description, ti.unit_index, ti.sort_order,
    i.name AS item_name, i.units AS item_units
FROM invoice_template_items ti
LEFT JOIN items i ON i.id = ti.item_id
WHERE ti.template_id = $1
ORDER BY ti.sort_order
`

type GetInvoiceTemplateItemsRow struct {
	ID          pgtype.UUID `json:"id"`
	TemplateID  pgtype.UUID `json:"template_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Description pgtype.Text `json:"description"`
	UnitIndex   int32       `json:"unit_index"`
	SortOrder   int32       `json:"sort_order"`
	ItemName    pgtype.Text `json:"item_name"`
	ItemUnits   []byte      `json:"item_units"`
}

func (q *Queries) GetInvoiceTemplateItems(ctx context.Context, templateID pgtype.UUID) ([]*GetInvoiceTemplateItemsRow, error) {
	rows, err := q.db.Query(ctx, getInvoiceTemplateItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetInvoiceTemplateItemsRow
	for rows.Next() {
		var i GetInvoiceTemplateItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ItemID,
			&i.Description,
			&i.UnitIndex,
			&i.SortOrder,
			&i.ItemName,
			&i.ItemUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceTemplates = `-- name: ListInvoiceTemplates :many
SELECT
    t.id, t.name, t.invoice_type, t.vendor_id, t.warehouse_id, t.created_at,
    v.name AS vendor_name, w.name AS warehouse_name
FROM invoice_templates t
LEFT JOIN vendors v ON v.id = t.vendor_id
LEFT JOIN warehouses w ON w.id = t.warehouse_id
ORDER BY t.name
`

type ListInvoiceTemplatesRow struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	InvoiceType   string             `json:"invoice_type"`
	VendorID      pgtype.UUID        `json:"vendor_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	VendorName    pgtype.Text        `json:"vendor_name"`
	WarehouseName pgtype.Text        `json:"warehouse_name"`
}

func (q *Queries) ListInvoiceTemplates(ctx context.Context) ([]*ListInvoiceTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListInvoiceTemplatesRow
	for rows.Next() {
		var i ListInvoiceTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InvoiceType,
			&i.VendorID,
			&i.WarehouseID,
			&i.CreatedAt,
			&i.VendorName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceTemplate = `-- name: UpdateInvoiceTemplate :one
UPDATE invoice_templates
SET name = $1, invoice_type = $2, vendor_id = $3, warehouse_id = $4
WHERE id = $5
RETURNING id, name, invoice_type, vendor_id, warehouse_id, created_at
`

type UpdateInvoiceTemplateParams struct {
	Name        string      `json:"name"`
	InvoiceType string      `json:"invoice_type"`
	VendorID    pgtype.UUID `json:"vendor_id"`
	WarehouseID pgtype.UUID `json:"warehouse_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateInvoiceTemplate(ctx context.Context, arg *UpdateInvoiceTemplateParams) (*InvoiceTemplate, error) {
	row := q.db.QueryRow(ctx, updateInvoiceTemplate,
		arg.Name,
		arg.InvoiceType,
		arg.VendorID,
		arg.WarehouseID,
		arg.ID,
	)
	var i InvoiceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvoiceType,
		&i.VendorID,
		&i.WarehouseID,
		&i.CreatedAt,
	)
	return &i, err
}
