// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Balance       int64       `json:"balance"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	AccountType   string      `json:"account_type"`
	ParentID      pgtype.UUID `json:"parent_id"`
	IsSystem      bool        `json:"is_system"`
}

type AccountAdjustment struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Amount        int64              `json:"amount"`
	Description   string             `json:"description"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TransferID    pgtype.UUID        `json:"transfer_id"`
}

type ActivityLog struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Username    string             `json:"username"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AttendanceDevice struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	BranchID   pgtype.UUID        `json:"branch_id"`
	ApiKeyHash string             `json:"api_key_hash"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID                pgtype.UUID        `json:"id"`
	EmployeeID        pgtype.UUID        `json:"employee_id"`
	Date              pgtype.Date        `json:"date"`
	CheckIn           pgtype.Timestamptz `json:"check_in"`
	CheckOut          pgtype.Timestamptz `json:"check_out"`
	CheckInSource     pgtype.Text        `json:"check_in_source"`
	CheckOutSource    pgtype.Text        `json:"check_out_source"`
	CheckInPhotoPath  pgtype.Text        `json:"check_in_photo_path"`
	DeviceID          pgtype.UUID        `json:"device_id"`
	Status            string             `json:"status"`
	IsLate            bool               `json:"is_late"`
	LateMinutes       int32              `json:"late_minutes"`
	IsEarlyLeave      bool               `json:"is_early_leave"`
	EarlyLeaveMinutes int32              `json:"early_leave_minutes"`
	IsMissingCheckout bool               `json:"is_missing_checkout"`
	Note              pgtype.Text        `json:"note"`
	IsHalfDay         bool               `json:"is_half_day"`
	HalfDayLostMinutes int32             `json:"half_day_lost_minutes"`
	HalfDayType        pgtype.Text        `json:"half_day_type"`
	IsMissingCheckin   bool               `json:"is_missing_checkin"`
	IsNoPunch          bool               `json:"is_no_punch"`
}

type Branch struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	RevenueAccountID pgtype.UUID        `json:"revenue_account_id"`
	ExpenseAccountID pgtype.UUID        `json:"expense_account_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Dispatch struct {
	ID           pgtype.UUID        `json:"id"`
	BranchID     pgtype.UUID        `json:"branch_id"`
	DivisionID   pgtype.UUID        `json:"division_id"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	Notes        pgtype.Text        `json:"notes"`
	DispatchedBy pgtype.UUID        `json:"dispatched_by"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

type DispatchItem struct {
	ID         pgtype.UUID    `json:"id"`
	DispatchID pgtype.UUID    `json:"dispatch_id"`
	ItemID     pgtype.UUID    `json:"item_id"`
	Quantity   pgtype.Numeric `json:"quantity"`
	UnitIndex  int32          `json:"unit_index"`
	UnitName   string         `json:"unit_name"`
}

type Division struct {
	ID                pgtype.UUID        `json:"id"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	Name              string             `json:"name"`
	RevenueAccountID  pgtype.UUID        `json:"revenue_account_id"`
	ExpenseAccountID  pgtype.UUID        `json:"expense_account_id"`
	DiscountAccountID pgtype.UUID        `json:"discount_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type DivisionCategory struct {
	ID         pgtype.UUID `json:"id"`
	DivisionID pgtype.UUID `json:"division_id"`
	Name       string      `json:"name"`
}

type Employee struct {
	ID                pgtype.UUID        `json:"id"`
	EmployeeCode      string             `json:"employee_code"`
	FullName          string             `json:"full_name"`
	Dob               pgtype.Date        `json:"dob"`
	JoinDate          pgtype.Date        `json:"join_date"`
	PositionID        pgtype.UUID        `json:"position_id"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	Phone             pgtype.Text        `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	Address           pgtype.Text        `json:"address"`
	NationalID        pgtype.Text        `json:"national_id"`
	BankName          pgtype.Text        `json:"bank_name"`
	BankAccountNumber pgtype.Text        `json:"bank_account_number"`
	BankAccountHolder pgtype.Text        `json:"bank_account_holder"`
	PhotoPath         pgtype.Text        `json:"photo_path"`
	UserID            pgtype.UUID        `json:"user_id"`
	Status            string             `json:"status"`
	EmploymentType    string             `json:"employment_type"`
	ContractEndDate   pgtype.Date        `json:"contract_end_date"`
	PermanentSince    pgtype.Date        `json:"permanent_since"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeWageComponent struct {
	ID              pgtype.UUID `json:"id"`
	WageStructureID pgtype.UUID `json:"wage_structure_id"`
	WageComponentID pgtype.UUID `json:"wage_component_id"`
	Amount          int64       `json:"amount"`
}

type Enumeration struct {
	ID               pgtype.UUID        `json:"id"`
	SourceItemID     pgtype.UUID        `json:"source_item_id"`
	OutputItemID     pgtype.UUID        `json:"output_item_id"`
	SourceQty        pgtype.Numeric     `json:"source_qty"`
	OutputQty        pgtype.Numeric     `json:"output_qty"`
	SourceUnitIdx    int32              `json:"source_unit_idx"`
	OutputUnitIdx    int32              `json:"output_unit_idx"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TransferredValue int64              `json:"transferred_value"`
	Date             pgtype.Date        `json:"date"`
}

type FingerprintImport struct {
	ID           pgtype.UUID        `json:"id"`
	Filename     pgtype.Text        `json:"filename"`
	ImportedBy   pgtype.UUID        `json:"imported_by"`
	RowCount     pgtype.Int4        `json:"row_count"`
	MatchedCount pgtype.Int4        `json:"matched_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type HrImportBatch struct {
	ID         pgtype.UUID        `json:"id"`
	UploadedBy pgtype.UUID        `json:"uploaded_by"`
	Filename   string             `json:"filename"`
	Payload    []byte             `json:"payload"`
	RowCount   int32              `json:"row_count"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type HrSetting struct {
	ID               int32              `json:"id"`
	CompanyName      string             `json:"company_name"`
	Address          string             `json:"address"`
	LogoPath         pgtype.Text        `json:"logo_path"`
	PayslipFooter    string             `json:"payslip_footer"`
	AbsenceGraceDays int32              `json:"absence_grace_days"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ID          pgtype.UUID    `json:"id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   int32          `json:"unit_index"`
	Value       int64          `json:"value"`
	Date        pgtype.Date    `json:"date"`
}

type Invoice struct {
	ID              pgtype.UUID        `json:"id"`
	InvoiceNumber   string             `json:"invoice_number"`
	Date            pgtype.Date        `json:"date"`
	DueDate         pgtype.Date        `json:"due_date"`
	InvoiceType     string             `json:"invoice_type"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	PaymentStatus   string             `json:"payment_status"`
	AmountPaid      int64              `json:"amount_paid"`
	AccountID       pgtype.UUID        `json:"account_id"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	DivisionID      pgtype.UUID        `json:"division_id"`
	DispatchID      pgtype.UUID        `json:"dispatch_id"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	PhotoPath       pgtype.Text        `json:"photo_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InvoiceItem struct {
	ID          pgtype.UUID    `json:"id"`
	InvoiceID   pgtype.UUID    `json:"invoice_id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	VendorID    pgtype.UUID    `json:"vendor_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   pgtype.Int4    `json:"unit_index"`
	Price       int64          `json:"price"`
	Description pgtype.Text    `json:"description"`
}

type InvoiceTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	InvoiceType string             `json:"invoice_type"`
	VendorID    pgtype.UUID        `json:"vendor_id"`
	WarehouseID pgtype.UUID        `json:"warehouse_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InvoiceTemplateItem struct {
	ID          pgtype.UUID `json:"id"`
	TemplateID  pgtype.UUID `json:"template_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Description pgtype.Text `json:"description"`
	UnitIndex   int32       `json:"unit_index"`
	SortOrder   int32       `json:"sort_order"`
}

type Item struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Code    string      `json:"code"`
	Units   []byte      `json:"units"`
	IsStock bool        `json:"is_stock"`
}

type Kasbon struct {
	ID                  pgtype.UUID        `json:"id"`
	KasbonNumber        string             `json:"kasbon_number"`
	EmployeeID          pgtype.UUID        `json:"employee_id"`
	Amount              int64              `json:"amount"`
	Details             string             `json:"details"`
	SendingMethod       string             `json:"sending_method"`
	FundSourceAccountID pgtype.UUID        `json:"fund_source_account_id"`
	RequestDate         pgtype.Date        `json:"request_date"`
	ResolutionMonth     pgtype.Date        `json:"resolution_month"`
	Status              string             `json:"status"`
	ApprovedBy          pgtype.UUID        `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	ApprovalNote        pgtype.Text        `json:"approval_note"`
	ProcessedBy         pgtype.UUID        `json:"processed_by"`
	ProcessedAt         pgtype.Timestamptz `json:"processed_at"`
	EvidencePhotoPath   pgtype.Text        `json:"evidence_photo_path"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type KasbonInstallment struct {
	ID            pgtype.UUID `json:"id"`
	KasbonID      pgtype.UUID `json:"kasbon_id"`
	DueMonth      pgtype.Date `json:"due_month"`
	Amount        int64       `json:"amount"`
	PayrollLineID pgtype.UUID `json:"payroll_line_id"`
	Status        string      `json:"status"`
}

type LeaveBalance struct {
	ID         pgtype.UUID `json:"id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Year       int32       `json:"year"`
	QuotaDays  int32       `json:"quota_days"`
	UsedDays   int32       `json:"used_days"`
}

type LeaveRequest struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	LeaveTypeID  pgtype.UUID        `json:"leave_type_id"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	DayCount     int32              `json:"day_count"`
	Reason       pgtype.Text        `json:"reason"`
	Status       string             `json:"status"`
	DecidedBy    pgtype.UUID        `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote pgtype.Text        `json:"decision_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LeaveType struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	IsPaid    bool        `json:"is_paid"`
	UsesQuota bool        `json:"uses_quota"`
	IsActive  bool        `json:"is_active"`
}

type PayrollLine struct {
	ID                      pgtype.UUID        `json:"id"`
	PayrollPeriodID         pgtype.UUID        `json:"payroll_period_id"`
	EmployeeID              pgtype.UUID        `json:"employee_id"`
	WageStructureID         pgtype.UUID        `json:"wage_structure_id"`
	BaseSalary              int64              `json:"base_salary"`
	DailyRate               int64              `json:"daily_rate"`
	OvertimeDays            pgtype.Numeric     `json:"overtime_days"`
	PublicHolidayDays       pgtype.Numeric     `json:"public_holiday_days"`
	OvertimeAmount          int64              `json:"overtime_amount"`
	PublicHolidayAmount     int64              `json:"public_holiday_amount"`
	AllowanceTotal          int64              `json:"allowance_total"`
	BonusTotal              int64              `json:"bonus_total"`
	ComponentDeductionTotal int64              `json:"component_deduction_total"`
	KasbonDeduction         int64              `json:"kasbon_deduction"`
	UnpaidLeaveDays         int32              `json:"unpaid_leave_days"`
	UnpaidLeaveDeduction    int64              `json:"unpaid_leave_deduction"`
	GrossPay                int64              `json:"gross_pay"`
	NetPay                  int64              `json:"net_pay"`
	PerformanceScore        pgtype.Int4        `json:"performance_score"`
	Reviewed                bool               `json:"reviewed"`
	ReviewedBy              pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNote              pgtype.Text        `json:"review_note"`
	OvertimeHours           pgtype.Numeric     `json:"overtime_hours"`
	OvertimeHourlyRate      int64              `json:"overtime_hourly_rate"`
	OvertimeHourlyAmount    int64              `json:"overtime_hourly_amount"`
	HalfDayHours            pgtype.Numeric     `json:"half_day_hours"`
	HalfDayDeduction        int64              `json:"half_day_deduction"`
}

type PayrollLineComponent struct {
	ID              pgtype.UUID `json:"id"`
	PayrollLineID   pgtype.UUID `json:"payroll_line_id"`
	WageComponentID pgtype.UUID `json:"wage_component_id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Amount          int64       `json:"amount"`
}

type PayrollPeriod struct {
	ID          pgtype.UUID        `json:"id"`
	PeriodMonth pgtype.Date        `json:"period_month"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Status      string             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PayrollSetting struct {
	ID                 int32          `json:"id"`
	OvertimeMultiplier pgtype.Numeric `json:"overtime_multiplier"`
	HolidayMultiplier  pgtype.Numeric `json:"holiday_multiplier"`
}

type ThrRun struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	PaymentDate pgtype.Date        `json:"payment_date"`
	Status      string             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ThrLine struct {
	ID              pgtype.UUID        `json:"id"`
	ThrRunID        pgtype.UUID        `json:"thr_run_id"`
	EmployeeID      pgtype.UUID        `json:"employee_id"`
	WageStructureID pgtype.UUID        `json:"wage_structure_id"`
	BaseSalary      int64              `json:"base_salary"`
	JoinDate        pgtype.Date        `json:"join_date"`
	MonthsWorked    int32              `json:"months_worked"`
	ThrRatio        pgtype.Numeric     `json:"thr_ratio"`
	ComputedAmount  int64              `json:"computed_amount"`
	ThrAmount       int64              `json:"thr_amount"`
	Reviewed        bool               `json:"reviewed"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNote      pgtype.Text        `json:"review_note"`
}

type PerformancePolicy struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	RuleType               string             `json:"rule_type"`
	ThresholdMinutes       pgtype.Int4        `json:"threshold_minutes"`
	Points                 int32              `json:"points"`
	MaxOccurrencesPerMonth pgtype.Int4        `json:"max_occurrences_per_month"`
	IsActive               bool               `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type PerformanceScore struct {
	ID          pgtype.UUID `json:"id"`
	EmployeeID  pgtype.UUID `json:"employee_id"`
	PeriodMonth pgtype.Date `json:"period_month"`
	Score       int32       `json:"score"`
}

type PerformanceViolation struct {
	ID                 pgtype.UUID        `json:"id"`
	EmployeeID         pgtype.UUID        `json:"employee_id"`
	PolicyID           pgtype.UUID        `json:"policy_id"`
	AttendanceRecordID pgtype.UUID        `json:"attendance_record_id"`
	Date               pgtype.Date        `json:"date"`
	Points             int32              `json:"points"`
	Source             string             `json:"source"`
	Note               pgtype.Text        `json:"note"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PosImport struct {
	ID          pgtype.UUID        `json:"id"`
	Description pgtype.Text        `json:"description"`
	Date        pgtype.Date        `json:"date"`
	SourceFile  pgtype.Text        `json:"source_file"`
	TotalAmount int64              `json:"total_amount"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PosImportLine struct {
	ID        pgtype.UUID `json:"id"`
	ImportID  pgtype.UUID `json:"import_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Label     string      `json:"label"`
	Amount    int64       `json:"amount"`
	LineType  string      `json:"line_type"`
}

type Position struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Production struct {
	ID             pgtype.UUID        `json:"id"`
	RecipeID       pgtype.UUID        `json:"recipe_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	Batches        pgtype.Numeric     `json:"batches"`
	OutputQuantity pgtype.Numeric     `json:"output_quantity"`
	Date           pgtype.Date        `json:"date"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PublicHoliday struct {
	ID   pgtype.UUID `json:"id"`
	Date pgtype.Date `json:"date"`
	Name string      `json:"name"`
}

type Recipe struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OutputItemID   pgtype.UUID        `json:"output_item_id"`
	BatchSize      pgtype.Numeric     `json:"batch_size"`
	BatchUnitIndex int32              `json:"batch_unit_index"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RecipeIngredient struct {
	ID        pgtype.UUID    `json:"id"`
	RecipeID  pgtype.UUID    `json:"recipe_id"`
	ItemID    pgtype.UUID    `json:"item_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	UnitIndex int32          `json:"unit_index"`
}

type Sale struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	Amount      int64              `json:"amount"`
	Description pgtype.Text        `json:"description"`
	Date        pgtype.Date        `json:"date"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	DivisionID  pgtype.UUID        `json:"division_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type StockHistory struct {
	ID             pgtype.UUID        `json:"id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	QuantityChange pgtype.Numeric     `json:"quantity_change"`
	UnitName       string             `json:"unit_name"`
	Vendor         pgtype.Text        `json:"vendor"`
	Type           string             `json:"type"`
	Reference      pgtype.Text        `json:"reference"`
	Date           pgtype.Date        `json:"date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceType     pgtype.Text        `json:"source_type"`
	Value          pgtype.Int8        `json:"value"`
}

type StockOpname struct {
	ID           pgtype.UUID        `json:"id"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	Notes        pgtype.Text        `json:"notes"`
	PerformedBy  pgtype.UUID        `json:"performed_by"`
	PerformedAt  pgtype.Timestamptz `json:"performed_at"`
	OperatorName pgtype.Text        `json:"operator_name"`
	PicName      pgtype.Text        `json:"pic_name"`
}

type StockOpnameDraft struct {
	ID           pgtype.UUID        `json:"id"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	PicName      pgtype.Text        `json:"pic_name"`
	OperatorName pgtype.Text        `json:"operator_name"`
	Notes        pgtype.Text        `json:"notes"`
	Items        []byte             `json:"items"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type StockOpnameItem struct {
	ID               pgtype.UUID    `json:"id"`
	OpnameID         pgtype.UUID    `json:"opname_id"`
	ItemID           pgtype.UUID    `json:"item_id"`
	UnitIndex        int32          `json:"unit_index"`
	UnitName         string         `json:"unit_name"`
	RecordedQuantity pgtype.Numeric `json:"recorded_quantity"`
	ActualQuantity   pgtype.Numeric `json:"actual_quantity"`
	Difference       pgtype.Numeric `json:"difference"`
	WasteValue       int64          `json:"waste_value"`
}

type StockTransfer struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	FromWarehouseID pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID        `json:"to_warehouse_id"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitIndex       int32              `json:"unit_index"`
	UnitName        string             `json:"unit_name"`
	Notes           pgtype.Text        `json:"notes"`
	TransferredBy   pgtype.UUID        `json:"transferred_by"`
	TransferredAt   pgtype.Timestamptz `json:"transferred_at"`
	GroupID         pgtype.UUID        `json:"group_id"`
}

type TokenBlocklist struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Vendor struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type WageComponent struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	IsFixed    bool               `json:"is_fixed"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CalcMethod string             `json:"calc_method"`
	MinScore   pgtype.Int4        `json:"min_score"`
}

type WageStructure struct {
	ID                  pgtype.UUID        `json:"id"`
	EmployeeID          pgtype.UUID        `json:"employee_id"`
	BaseSalary          int64              `json:"base_salary"`
	WorkingDaysPerMonth int32              `json:"working_days_per_month"`
	DailyRate           int64              `json:"daily_rate"`
	EffectiveDate       pgtype.Date        `json:"effective_date"`
	EndDate             pgtype.Date        `json:"end_date"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Warehouse struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	InventoryAccountID pgtype.UUID `json:"inventory_account_id"`
}

type WorkSchedule struct {
	ID                pgtype.UUID `json:"id"`
	BranchID          pgtype.UUID `json:"branch_id"`
	WorkStart         pgtype.Time `json:"work_start"`
	WorkEnd           pgtype.Time `json:"work_end"`
	GraceMinutes      int32       `json:"grace_minutes"`
	EarlyLeaveMinutes int32       `json:"early_leave_minutes"`
	WorkDays          []int32     `json:"work_days"`
}
