// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Balance       int64       `json:"balance"`
	AccountNumber pgtype.Int4 `json:"account_number"`
	AccountType   string      `json:"account_type"`
	ParentID      pgtype.UUID `json:"parent_id"`
	IsSystem      bool        `json:"is_system"`
}

type AccountAdjustment struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Amount        int64              `json:"amount"`
	Description   string             `json:"description"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TransferID    pgtype.UUID        `json:"transfer_id"`
}

type ActivityLog struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Username    string             `json:"username"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	RevenueAccountID pgtype.UUID        `json:"revenue_account_id"`
	ExpenseAccountID pgtype.UUID        `json:"expense_account_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Dispatch struct {
	ID           pgtype.UUID        `json:"id"`
	BranchID     pgtype.UUID        `json:"branch_id"`
	DivisionID   pgtype.UUID        `json:"division_id"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	Notes        pgtype.Text        `json:"notes"`
	DispatchedBy pgtype.UUID        `json:"dispatched_by"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

type DispatchItem struct {
	ID         pgtype.UUID    `json:"id"`
	DispatchID pgtype.UUID    `json:"dispatch_id"`
	ItemID     pgtype.UUID    `json:"item_id"`
	Quantity   pgtype.Numeric `json:"quantity"`
	UnitIndex  int32          `json:"unit_index"`
	UnitName   string         `json:"unit_name"`
}

type Division struct {
	ID                pgtype.UUID        `json:"id"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	Name              string             `json:"name"`
	RevenueAccountID  pgtype.UUID        `json:"revenue_account_id"`
	ExpenseAccountID  pgtype.UUID        `json:"expense_account_id"`
	DiscountAccountID pgtype.UUID        `json:"discount_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type DivisionCategory struct {
	ID         pgtype.UUID `json:"id"`
	DivisionID pgtype.UUID `json:"division_id"`
	Name       string      `json:"name"`
}

type Enumeration struct {
	ID               pgtype.UUID        `json:"id"`
	SourceItemID     pgtype.UUID        `json:"source_item_id"`
	OutputItemID     pgtype.UUID        `json:"output_item_id"`
	SourceQty        pgtype.Numeric     `json:"source_qty"`
	OutputQty        pgtype.Numeric     `json:"output_qty"`
	SourceUnitIdx    int32              `json:"source_unit_idx"`
	OutputUnitIdx    int32              `json:"output_unit_idx"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TransferredValue int64              `json:"transferred_value"`
	Date             pgtype.Date        `json:"date"`
}

type Inventory struct {
	ID          pgtype.UUID    `json:"id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   int32          `json:"unit_index"`
	Value       int64          `json:"value"`
	Date        pgtype.Date    `json:"date"`
}

type Invoice struct {
	ID              pgtype.UUID        `json:"id"`
	InvoiceNumber   string             `json:"invoice_number"`
	Date            pgtype.Date        `json:"date"`
	DueDate         pgtype.Date        `json:"due_date"`
	InvoiceType     string             `json:"invoice_type"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	PaymentStatus   string             `json:"payment_status"`
	AmountPaid      int64              `json:"amount_paid"`
	AccountID       pgtype.UUID        `json:"account_id"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	DivisionID      pgtype.UUID        `json:"division_id"`
	DispatchID      pgtype.UUID        `json:"dispatch_id"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	PhotoPath       pgtype.Text        `json:"photo_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InvoiceItem struct {
	ID          pgtype.UUID    `json:"id"`
	InvoiceID   pgtype.UUID    `json:"invoice_id"`
	ItemID      pgtype.UUID    `json:"item_id"`
	VendorID    pgtype.UUID    `json:"vendor_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitIndex   pgtype.Int4    `json:"unit_index"`
	Price       int64          `json:"price"`
	Description pgtype.Text    `json:"description"`
}

type InvoiceTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	InvoiceType string             `json:"invoice_type"`
	VendorID    pgtype.UUID        `json:"vendor_id"`
	WarehouseID pgtype.UUID        `json:"warehouse_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InvoiceTemplateItem struct {
	ID          pgtype.UUID `json:"id"`
	TemplateID  pgtype.UUID `json:"template_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Description pgtype.Text `json:"description"`
	UnitIndex   int32       `json:"unit_index"`
	SortOrder   int32       `json:"sort_order"`
}

type Item struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Code    string      `json:"code"`
	Units   []byte      `json:"units"`
	IsStock bool        `json:"is_stock"`
}

type PosImport struct {
	ID          pgtype.UUID        `json:"id"`
	Description pgtype.Text        `json:"description"`
	Date        pgtype.Date        `json:"date"`
	SourceFile  pgtype.Text        `json:"source_file"`
	TotalAmount int64              `json:"total_amount"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PosImportLine struct {
	ID        pgtype.UUID `json:"id"`
	ImportID  pgtype.UUID `json:"import_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Label     string      `json:"label"`
	Amount    int64       `json:"amount"`
	LineType  string      `json:"line_type"`
}

type Production struct {
	ID             pgtype.UUID        `json:"id"`
	RecipeID       pgtype.UUID        `json:"recipe_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	Batches        pgtype.Numeric     `json:"batches"`
	OutputQuantity pgtype.Numeric     `json:"output_quantity"`
	Date           pgtype.Date        `json:"date"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Recipe struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OutputItemID   pgtype.UUID        `json:"output_item_id"`
	BatchSize      pgtype.Numeric     `json:"batch_size"`
	BatchUnitIndex int32              `json:"batch_unit_index"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RecipeIngredient struct {
	ID        pgtype.UUID    `json:"id"`
	RecipeID  pgtype.UUID    `json:"recipe_id"`
	ItemID    pgtype.UUID    `json:"item_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	UnitIndex int32          `json:"unit_index"`
}

type Sale struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	Amount      int64              `json:"amount"`
	Description pgtype.Text        `json:"description"`
	Date        pgtype.Date        `json:"date"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	DivisionID  pgtype.UUID        `json:"division_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type StockHistory struct {
	ID             pgtype.UUID        `json:"id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	QuantityChange pgtype.Numeric     `json:"quantity_change"`
	UnitName       string             `json:"unit_name"`
	Vendor         pgtype.Text        `json:"vendor"`
	Type           string             `json:"type"`
	Reference      pgtype.Text        `json:"reference"`
	Date           pgtype.Date        `json:"date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceType     pgtype.Text        `json:"source_type"`
	Value          pgtype.Int8        `json:"value"`
}

type StockOpname struct {
	ID           pgtype.UUID        `json:"id"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	Notes        pgtype.Text        `json:"notes"`
	PerformedBy  pgtype.UUID        `json:"performed_by"`
	PerformedAt  pgtype.Timestamptz `json:"performed_at"`
	OperatorName pgtype.Text        `json:"operator_name"`
	PicName      pgtype.Text        `json:"pic_name"`
}

type StockOpnameItem struct {
	ID               pgtype.UUID    `json:"id"`
	OpnameID         pgtype.UUID    `json:"opname_id"`
	ItemID           pgtype.UUID    `json:"item_id"`
	UnitIndex        int32          `json:"unit_index"`
	UnitName         string         `json:"unit_name"`
	RecordedQuantity pgtype.Numeric `json:"recorded_quantity"`
	ActualQuantity   pgtype.Numeric `json:"actual_quantity"`
	Difference       pgtype.Numeric `json:"difference"`
	WasteValue       int64          `json:"waste_value"`
}

type StockTransfer struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	FromWarehouseID pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID        `json:"to_warehouse_id"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitIndex       int32              `json:"unit_index"`
	UnitName        string             `json:"unit_name"`
	Notes           pgtype.Text        `json:"notes"`
	TransferredBy   pgtype.UUID        `json:"transferred_by"`
	TransferredAt   pgtype.Timestamptz `json:"transferred_at"`
	GroupID         pgtype.UUID        `json:"group_id"`
}

type TokenBlocklist struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Vendor struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type Warehouse struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	InventoryAccountID pgtype.UUID `json:"inventory_account_id"`
}
