// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: petty_cash.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPettyCashCount = `-- name: GetPettyCashCount :one
SELECT id, branch_id, count_date, opening_amount, opening_by, opening_at,
       closing_amount, closing_by, closing_at, expected_closing, variance,
       variance_note, created_at
FROM petty_cash_counts
WHERE branch_id = $1 AND count_date = $2
`

type GetPettyCashCountParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	CountDate pgtype.Date `json:"count_date"`
}

func (q *Queries) GetPettyCashCount(ctx context.Context, arg *GetPettyCashCountParams) (*PettyCashCount, error) {
	row := q.db.QueryRow(ctx, getPettyCashCount, arg.BranchID, arg.CountDate)
	var i PettyCashCount
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CountDate,
		&i.OpeningAmount,
		&i.OpeningBy,
		&i.OpeningAt,
		&i.ClosingAmount,
		&i.ClosingBy,
		&i.ClosingAt,
		&i.ExpectedClosing,
		&i.Variance,
		&i.VarianceNote,
		&i.CreatedAt,
	)
	return &i, err
}

const getPreviousPettyCashClosing = `-- name: GetPreviousPettyCashClosing :one
SELECT count_date, closing_amount
FROM petty_cash_counts
WHERE branch_id = $1 AND count_date < $2 AND closing_amount IS NOT NULL
ORDER BY count_date DESC
LIMIT 1
`

type GetPreviousPettyCashClosingParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	CountDate pgtype.Date `json:"count_date"`
}

type GetPreviousPettyCashClosingRow struct {
	CountDate     pgtype.Date `json:"count_date"`
	ClosingAmount pgtype.Int8 `json:"closing_amount"`
}

func (q *Queries) GetPreviousPettyCashClosing(ctx context.Context, arg *GetPreviousPettyCashClosingParams) (*GetPreviousPettyCashClosingRow, error) {
	row := q.db.QueryRow(ctx, getPreviousPettyCashClosing, arg.BranchID, arg.CountDate)
	var i GetPreviousPettyCashClosingRow
	err := row.Scan(&i.CountDate, &i.ClosingAmount)
	return &i, err
}

const listPettyCashCounts = `-- name: ListPettyCashCounts :many
SELECT
    c.id, c.branch_id, b.name AS branch_name, c.count_date,
    c.opening_amount, ou.username AS opening_by_name, c.opening_at,
    c.closing_amount, cu.username AS closing_by_name, c.closing_at,
    c.expected_closing, c.variance, c.variance_note
FROM petty_cash_counts c
JOIN branches b   ON b.id = c.branch_id
LEFT JOIN users ou ON ou.id = c.opening_by
LEFT JOIN users cu ON cu.id = c.closing_by
WHERE ($1::uuid IS NULL OR c.branch_id = $1)
  AND ($2::date IS NULL OR c.count_date >= $2)
  AND ($3::date IS NULL OR c.count_date <= $3)
ORDER BY c.count_date DESC, b.name
`

type ListPettyCashCountsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

type ListPettyCashCountsRow struct {
	ID              pgtype.UUID        `json:"id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	BranchName      string             `json:"branch_name"`
	CountDate       pgtype.Date        `json:"count_date"`
	OpeningAmount   int64              `json:"opening_amount"`
	OpeningByName   pgtype.Text        `json:"opening_by_name"`
	OpeningAt       pgtype.Timestamptz `json:"opening_at"`
	ClosingAmount   pgtype.Int8        `json:"closing_amount"`
	ClosingByName   pgtype.Text        `json:"closing_by_name"`
	ClosingAt       pgtype.Timestamptz `json:"closing_at"`
	ExpectedClosing pgtype.Int8        `json:"expected_closing"`
	Variance        pgtype.Int8        `json:"variance"`
	VarianceNote    string             `json:"variance_note"`
}

func (q *Queries) ListPettyCashCounts(ctx context.Context, arg *ListPettyCashCountsParams) ([]*ListPettyCashCountsRow, error) {
	rows, err := q.db.Query(ctx, listPettyCashCounts, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPettyCashCountsRow
	for rows.Next() {
		var i ListPettyCashCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.BranchName,
			&i.CountDate,
			&i.OpeningAmount,
			&i.OpeningByName,
			&i.OpeningAt,
			&i.ClosingAmount,
			&i.ClosingByName,
			&i.ClosingAt,
			&i.ExpectedClosing,
			&i.Variance,
			&i.VarianceNote,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPettyCashDayStatus = `-- name: ListPettyCashDayStatus :many
SELECT
    b.id AS branch_id, b.name AS branch_name,
    b.petty_cash_account_id,
    COALESCE(pa.balance, 0)::bigint AS ledger_balance,
    c.opening_amount, c.closing_amount, c.expected_closing, c.variance, c.variance_note
FROM branches b
LEFT JOIN accounts pa ON pa.id = b.petty_cash_account_id
LEFT JOIN petty_cash_counts c ON c.branch_id = b.id AND c.count_date = $1
ORDER BY b.name
`

type ListPettyCashDayStatusRow struct {
	BranchID           pgtype.UUID `json:"branch_id"`
	BranchName         string      `json:"branch_name"`
	PettyCashAccountID pgtype.UUID `json:"petty_cash_account_id"`
	LedgerBalance      int64       `json:"ledger_balance"`
	OpeningAmount      pgtype.Int8 `json:"opening_amount"`
	ClosingAmount      pgtype.Int8 `json:"closing_amount"`
	ExpectedClosing    pgtype.Int8 `json:"expected_closing"`
	Variance           pgtype.Int8 `json:"variance"`
	VarianceNote       pgtype.Text `json:"variance_note"`
}

func (q *Queries) ListPettyCashDayStatus(ctx context.Context, countDate pgtype.Date) ([]*ListPettyCashDayStatusRow, error) {
	rows, err := q.db.Query(ctx, listPettyCashDayStatus, countDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPettyCashDayStatusRow
	for rows.Next() {
		var i ListPettyCashDayStatusRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BranchName,
			&i.PettyCashAccountID,
			&i.LedgerBalance,
			&i.OpeningAmount,
			&i.ClosingAmount,
			&i.ExpectedClosing,
			&i.Variance,
			&i.VarianceNote,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPettyCashClosing = `-- name: SetPettyCashClosing :one
UPDATE petty_cash_counts
SET closing_amount = $1, closing_by = $2, closing_at = now(),
    expected_closing = $3, variance = $4, variance_note = $5
WHERE branch_id = $6 AND count_date = $7
RETURNING id, branch_id, count_date, opening_amount, opening_by, opening_at,
          closing_amount, closing_by, closing_at, expected_closing, variance,
          variance_note, created_at
`

type SetPettyCashClosingParams struct {
	ClosingAmount   pgtype.Int8 `json:"closing_amount"`
	ClosingBy       pgtype.UUID `json:"closing_by"`
	ExpectedClosing pgtype.Int8 `json:"expected_closing"`
	Variance        pgtype.Int8 `json:"variance"`
	VarianceNote    string      `json:"variance_note"`
	BranchID        pgtype.UUID `json:"branch_id"`
	CountDate       pgtype.Date `json:"count_date"`
}

func (q *Queries) SetPettyCashClosing(ctx context.Context, arg *SetPettyCashClosingParams) (*PettyCashCount, error) {
	row := q.db.QueryRow(ctx, setPettyCashClosing,
		arg.ClosingAmount,
		arg.ClosingBy,
		arg.ExpectedClosing,
		arg.Variance,
		arg.VarianceNote,
		arg.BranchID,
		arg.CountDate,
	)
	var i PettyCashCount
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CountDate,
		&i.OpeningAmount,
		&i.OpeningBy,
		&i.OpeningAt,
		&i.ClosingAmount,
		&i.ClosingBy,
		&i.ClosingAt,
		&i.ExpectedClosing,
		&i.Variance,
		&i.VarianceNote,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertPettyCashOpening = `-- name: UpsertPettyCashOpening :one
INSERT INTO petty_cash_counts (id, branch_id, count_date, opening_amount, opening_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (branch_id, count_date) DO UPDATE
SET opening_amount = EXCLUDED.opening_amount,
    opening_by     = EXCLUDED.opening_by,
    opening_at     = now(),
    closing_amount = NULL,
    closing_by     = NULL,
    closing_at     = NULL,
    expected_closing = NULL,
    variance         = NULL,
    variance_note    = ''
RETURNING id, branch_id, count_date, opening_amount, opening_by, opening_at,
          closing_amount, closing_by, closing_at, expected_closing, variance,
          variance_note, created_at
`

type UpsertPettyCashOpeningParams struct {
	BranchID      pgtype.UUID `json:"branch_id"`
	CountDate     pgtype.Date `json:"count_date"`
	OpeningAmount int64       `json:"opening_amount"`
	OpeningBy     pgtype.UUID `json:"opening_by"`
}

func (q *Queries) UpsertPettyCashOpening(ctx context.Context, arg *UpsertPettyCashOpeningParams) (*PettyCashCount, error) {
	row := q.db.QueryRow(ctx, upsertPettyCashOpening,
		arg.BranchID,
		arg.CountDate,
		arg.OpeningAmount,
		arg.OpeningBy,
	)
	var i PettyCashCount
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CountDate,
		&i.OpeningAmount,
		&i.OpeningBy,
		&i.OpeningAt,
		&i.ClosingAmount,
		&i.ClosingBy,
		&i.ClosingAt,
		&i.ExpectedClosing,
		&i.Variance,
		&i.VarianceNote,
		&i.CreatedAt,
	)
	return &i, err
}
