// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pos_import.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePOSImport = `-- name: DeletePOSImport :exec
DELETE FROM pos_imports WHERE id = $1
`

func (q *Queries) DeletePOSImport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePOSImport, id)
	return err
}

const deletePOSImportLines = `-- name: DeletePOSImportLines :exec
DELETE FROM pos_import_lines WHERE import_id = $1
`

func (q *Queries) DeletePOSImportLines(ctx context.Context, importID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePOSImportLines, importID)
	return err
}

const getPOSImportByID = `-- name: GetPOSImportByID :one
SELECT id, description, date, source_file, total_amount, created_by, created_at
FROM pos_imports WHERE id = $1
`

func (q *Queries) GetPOSImportByID(ctx context.Context, id pgtype.UUID) (*PosImport, error) {
	row := q.db.QueryRow(ctx, getPOSImportByID, id)
	var i PosImport
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Date,
		&i.SourceFile,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getPOSImportLines = `-- name: GetPOSImportLines :many
SELECT
    pil.id, pil.import_id, pil.account_id, pil.label, pil.amount, pil.line_type,
    a.name AS account_name
FROM pos_import_lines pil
LEFT JOIN accounts a ON a.id = pil.account_id
WHERE pil.import_id = $1
ORDER BY pil.line_type, pil.label
`

type GetPOSImportLinesRow struct {
	ID          pgtype.UUID `json:"id"`
	ImportID    pgtype.UUID `json:"import_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	Label       string      `json:"label"`
	Amount      int64       `json:"amount"`
	LineType    string      `json:"line_type"`
	AccountName pgtype.Text `json:"account_name"`
}

func (q *Queries) GetPOSImportLines(ctx context.Context, importID pgtype.UUID) ([]*GetPOSImportLinesRow, error) {
	rows, err := q.db.Query(ctx, getPOSImportLines, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPOSImportLinesRow
	for rows.Next() {
		var i GetPOSImportLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.AccountID,
			&i.Label,
			&i.Amount,
			&i.LineType,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPOSImportLinesForReversal = `-- name: GetPOSImportLinesForReversal :many
SELECT account_id, amount, line_type FROM pos_import_lines WHERE import_id = $1
`

type GetPOSImportLinesForReversalRow struct {
	AccountID pgtype.UUID `json:"account_id"`
	Amount    int64       `json:"amount"`
	LineType  string      `json:"line_type"`
}

func (q *Queries) GetPOSImportLinesForReversal(ctx context.Context, importID pgtype.UUID) ([]*GetPOSImportLinesForReversalRow, error) {
	rows, err := q.db.Query(ctx, getPOSImportLinesForReversal, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPOSImportLinesForReversalRow
	for rows.Next() {
		var i GetPOSImportLinesForReversalRow
		if err := rows.Scan(&i.AccountID, &i.Amount, &i.LineType); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPOSImport = `-- name: InsertPOSImport :one
INSERT INTO pos_imports (description, date, source_file, total_amount, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertPOSImportParams struct {
	Description pgtype.Text `json:"description"`
	Date        pgtype.Date `json:"date"`
	SourceFile  pgtype.Text `json:"source_file"`
	TotalAmount int64       `json:"total_amount"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

type InsertPOSImportRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPOSImport(ctx context.Context, arg *InsertPOSImportParams) (*InsertPOSImportRow, error) {
	row := q.db.QueryRow(ctx, insertPOSImport,
		arg.Description,
		arg.Date,
		arg.SourceFile,
		arg.TotalAmount,
		arg.CreatedBy,
	)
	var i InsertPOSImportRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const insertPOSImportLine = `-- name: InsertPOSImportLine :exec
INSERT INTO pos_import_lines (import_id, account_id, label, amount, line_type)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPOSImportLineParams struct {
	ImportID  pgtype.UUID `json:"import_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Label     string      `json:"label"`
	Amount    int64       `json:"amount"`
	LineType  string      `json:"line_type"`
}

func (q *Queries) InsertPOSImportLine(ctx context.Context, arg *InsertPOSImportLineParams) error {
	_, err := q.db.Exec(ctx, insertPOSImportLine,
		arg.ImportID,
		arg.AccountID,
		arg.Label,
		arg.Amount,
		arg.LineType,
	)
	return err
}

const listAllPOSImportLines = `-- name: ListAllPOSImportLines :many
SELECT
    pil.id, pil.import_id, pil.account_id, pil.label, pil.amount, pil.line_type,
    a.name AS account_name
FROM pos_import_lines pil
LEFT JOIN accounts a ON a.id = pil.account_id
ORDER BY pil.import_id, pil.line_type DESC, pil.amount DESC
`

type ListAllPOSImportLinesRow struct {
	ID          pgtype.UUID `json:"id"`
	ImportID    pgtype.UUID `json:"import_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	Label       string      `json:"label"`
	Amount      int64       `json:"amount"`
	LineType    string      `json:"line_type"`
	AccountName pgtype.Text `json:"account_name"`
}

func (q *Queries) ListAllPOSImportLines(ctx context.Context) ([]*ListAllPOSImportLinesRow, error) {
	rows, err := q.db.Query(ctx, listAllPOSImportLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllPOSImportLinesRow
	for rows.Next() {
		var i ListAllPOSImportLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.AccountID,
			&i.Label,
			&i.Amount,
			&i.LineType,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPOSImports = `-- name: ListPOSImports :many
SELECT
    pi.id, pi.description, pi.date, pi.source_file, pi.total_amount, pi.created_at,
    u.username AS created_by_name
FROM pos_imports pi
LEFT JOIN users u ON u.id = pi.created_by
WHERE ($1::date IS NULL OR pi.date >= $1)
  AND ($2::date IS NULL OR pi.date <= $2)
ORDER BY pi.date DESC, pi.created_at DESC
`

type ListPOSImportsParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListPOSImportsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Description   pgtype.Text        `json:"description"`
	Date          pgtype.Date        `json:"date"`
	SourceFile    pgtype.Text        `json:"source_file"`
	TotalAmount   int64              `json:"total_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListPOSImports(ctx context.Context, arg *ListPOSImportsParams) ([]*ListPOSImportsRow, error) {
	rows, err := q.db.Query(ctx, listPOSImports, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPOSImportsRow
	for rows.Next() {
		var i ListPOSImportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Date,
			&i.SourceFile,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
