// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: productions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProduction = `-- name: InsertProduction :one
INSERT INTO productions (id, recipe_id, warehouse_id, batches, output_quantity, date, notes, created_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertProductionParams struct {
	RecipeID       pgtype.UUID    `json:"recipe_id"`
	WarehouseID    pgtype.UUID    `json:"warehouse_id"`
	Batches        pgtype.Numeric `json:"batches"`
	OutputQuantity pgtype.Numeric `json:"output_quantity"`
	Date           pgtype.Date    `json:"date"`
	Notes          pgtype.Text    `json:"notes"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

type InsertProductionRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertProduction(ctx context.Context, arg *InsertProductionParams) (*InsertProductionRow, error) {
	row := q.db.QueryRow(ctx, insertProduction,
		arg.RecipeID,
		arg.WarehouseID,
		arg.Batches,
		arg.OutputQuantity,
		arg.Date,
		arg.Notes,
		arg.CreatedBy,
	)
	var i InsertProductionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const listProductions = `-- name: ListProductions :many
SELECT
    p.id, p.recipe_id, p.warehouse_id, p.batches, p.output_quantity,
    p.date, p.notes, p.created_at,
    r.name AS recipe_name,
    r.output_item_id,
    i.name AS output_item_name,
    w.name AS warehouse_name,
    u.username AS created_by_name
FROM productions p
JOIN recipes r ON r.id = p.recipe_id
JOIN items i ON i.id = r.output_item_id
JOIN warehouses w ON w.id = p.warehouse_id
LEFT JOIN users u ON u.id = p.created_by
WHERE ($1::date IS NULL OR p.date >= $1)
  AND ($2::date IS NULL OR p.date <= $2)
ORDER BY p.date DESC, p.created_at DESC
`

type ListProductionsParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListProductionsRow struct {
	ID             pgtype.UUID        `json:"id"`
	RecipeID       pgtype.UUID        `json:"recipe_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	Batches        pgtype.Numeric     `json:"batches"`
	OutputQuantity pgtype.Numeric     `json:"output_quantity"`
	Date           pgtype.Date        `json:"date"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RecipeName     string             `json:"recipe_name"`
	OutputItemID   pgtype.UUID        `json:"output_item_id"`
	OutputItemName string             `json:"output_item_name"`
	WarehouseName  string             `json:"warehouse_name"`
	CreatedByName  pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListProductions(ctx context.Context, arg *ListProductionsParams) ([]*ListProductionsRow, error) {
	rows, err := q.db.Query(ctx, listProductions, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListProductionsRow
	for rows.Next() {
		var i ListProductionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.WarehouseID,
			&i.Batches,
			&i.OutputQuantity,
			&i.Date,
			&i.Notes,
			&i.CreatedAt,
			&i.RecipeName,
			&i.OutputItemID,
			&i.OutputItemName,
			&i.WarehouseName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
