// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryValueReport = `-- name: GetInventoryValueReport :many
SELECT
    i.id AS item_id, i.name AS item_name, i.code AS item_code, i.units,
    w.id AS warehouse_id, w.name AS warehouse_name,
    SUM(inv.quantity) AS total_quantity,
    SUM(inv.value) AS total_value,
    MIN(inv.unit_index) AS unit_index
FROM inventory inv
JOIN items i ON i.id = inv.item_id
JOIN warehouses w ON w.id = inv.warehouse_id
GROUP BY i.id, i.name, i.code, i.units, w.id, w.name
ORDER BY i.name, w.name
`

type GetInventoryValueReportRow struct {
	ItemID        pgtype.UUID `json:"item_id"`
	ItemName      string      `json:"item_name"`
	ItemCode      string      `json:"item_code"`
	Units         []byte      `json:"units"`
	WarehouseID   pgtype.UUID `json:"warehouse_id"`
	WarehouseName string      `json:"warehouse_name"`
	TotalQuantity int64       `json:"total_quantity"`
	TotalValue    int64       `json:"total_value"`
	UnitIndex     interface{} `json:"unit_index"`
}

func (q *Queries) GetInventoryValueReport(ctx context.Context) ([]*GetInventoryValueReportRow, error) {
	rows, err := q.db.Query(ctx, getInventoryValueReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetInventoryValueReportRow
	for rows.Next() {
		var i GetInventoryValueReportRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.ItemCode,
			&i.Units,
			&i.WarehouseID,
			&i.WarehouseName,
			&i.TotalQuantity,
			&i.TotalValue,
			&i.UnitIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
