// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSale = `-- name: DeleteSale :exec
DELETE FROM sales WHERE id = $1
`

func (q *Queries) DeleteSale(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSale, id)
	return err
}

const getSaleByID = `-- name: GetSaleByID :one
SELECT id, account_id, amount, description, date, branch_id, division_id, created_by, created_at
FROM sales WHERE id = $1
`

func (q *Queries) GetSaleByID(ctx context.Context, id pgtype.UUID) (*Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByID, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.BranchID,
		&i.DivisionID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const insertSale = `-- name: InsertSale :one
INSERT INTO sales (id, account_id, amount, description, date, branch_id, division_id, created_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertSaleParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	Amount      int64       `json:"amount"`
	Description pgtype.Text `json:"description"`
	Date        pgtype.Date `json:"date"`
	BranchID    pgtype.UUID `json:"branch_id"`
	DivisionID  pgtype.UUID `json:"division_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

type InsertSaleRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSale(ctx context.Context, arg *InsertSaleParams) (*InsertSaleRow, error) {
	row := q.db.QueryRow(ctx, insertSale,
		arg.AccountID,
		arg.Amount,
		arg.Description,
		arg.Date,
		arg.BranchID,
		arg.DivisionID,
		arg.CreatedBy,
	)
	var i InsertSaleRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const listSales = `-- name: ListSales :many
SELECT
    s.id, s.account_id, s.amount, s.description, s.date, s.created_at,
    s.branch_id, s.division_id,
    a.name AS account_name,
    b.name AS branch_name,
    d.name AS division_name,
    u.username AS created_by_name
FROM sales s
LEFT JOIN accounts a ON a.id = s.account_id
LEFT JOIN branches b ON b.id = s.branch_id
LEFT JOIN divisions d ON d.id = s.division_id
LEFT JOIN users u ON u.id = s.created_by
WHERE ($1::date IS NULL OR s.date >= $1)
  AND ($2::date IS NULL OR s.date <= $2)
  AND ($3::uuid IS NULL OR s.branch_id = $3)
ORDER BY s.date DESC, s.created_at DESC
`

type ListSalesParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

type ListSalesRow struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Amount        int64              `json:"amount"`
	Description   pgtype.Text        `json:"description"`
	Date          pgtype.Date        `json:"date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	BranchID      pgtype.UUID        `json:"branch_id"`
	DivisionID    pgtype.UUID        `json:"division_id"`
	AccountName   pgtype.Text        `json:"account_name"`
	BranchName    pgtype.Text        `json:"branch_name"`
	DivisionName  pgtype.Text        `json:"division_name"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListSales(ctx context.Context, arg *ListSalesParams) ([]*ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListSalesRow
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.BranchID,
			&i.DivisionID,
			&i.AccountName,
			&i.BranchName,
			&i.DivisionName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
