// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStockHistoryBySource = `-- name: DeleteStockHistoryBySource :exec
DELETE FROM stock_history WHERE source_id = $1 AND source_type = $2
`

type DeleteStockHistoryBySourceParams struct {
	SourceID   pgtype.UUID `json:"source_id"`
	SourceType pgtype.Text `json:"source_type"`
}

func (q *Queries) DeleteStockHistoryBySource(ctx context.Context, arg *DeleteStockHistoryBySourceParams) error {
	_, err := q.db.Exec(ctx, deleteStockHistoryBySource, arg.SourceID, arg.SourceType)
	return err
}

const insertStockHistory = `-- name: InsertStockHistory :one
INSERT INTO stock_history (
    id, item_id, warehouse_id, quantity_change, unit_name,
    vendor, type, reference, date, value, source_id, source_type
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id
`

type InsertStockHistoryParams struct {
	ItemID         pgtype.UUID    `json:"item_id"`
	WarehouseID    pgtype.UUID    `json:"warehouse_id"`
	QuantityChange pgtype.Numeric `json:"quantity_change"`
	UnitName       string         `json:"unit_name"`
	Vendor         pgtype.Text    `json:"vendor"`
	Type           string         `json:"type"`
	Reference      pgtype.Text    `json:"reference"`
	Date           pgtype.Date    `json:"date"`
	Value          pgtype.Int8    `json:"value"`
	SourceID       pgtype.UUID    `json:"source_id"`
	SourceType     pgtype.Text    `json:"source_type"`
}

func (q *Queries) InsertStockHistory(ctx context.Context, arg *InsertStockHistoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertStockHistory,
		arg.ItemID,
		arg.WarehouseID,
		arg.QuantityChange,
		arg.UnitName,
		arg.Vendor,
		arg.Type,
		arg.Reference,
		arg.Date,
		arg.Value,
		arg.SourceID,
		arg.SourceType,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listStockHistoryByItem = `-- name: ListStockHistoryByItem :many
WITH h AS (
    SELECT
        sh.id, sh.item_id, sh.warehouse_id, sh.quantity_change,
        sh.unit_name, sh.vendor, sh.type, sh.reference,
        sh.date, sh.created_at, sh.value,
        sh.source_id, sh.source_type,
        SUM(sh.quantity_change) OVER (
            ORDER BY sh.date, sh.created_at, sh.id
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS balance_after
    FROM stock_history sh
    WHERE sh.item_id = $1
)
SELECT
    h.id, h.item_id, h.warehouse_id, h.quantity_change,
    h.unit_name, h.vendor, h.type, h.reference,
    h.date, h.created_at, h.value,
    h.source_id, h.source_type,
    w.name AS warehouse_name,
    h.balance_after::numeric AS balance_after,
    CASE
        WHEN h.source_type = 'dispatch' THEN NULLIF(CONCAT_WS(' / ', b.name, dv.name), '')
        WHEN h.source_type = 'transfer' AND h.quantity_change < 0 THEN tw.name
    END AS destination
FROM h
LEFT JOIN warehouses w ON w.id = h.warehouse_id
LEFT JOIN dispatches d ON h.source_type = 'dispatch' AND d.id = h.source_id
LEFT JOIN branches b   ON b.id  = d.branch_id
LEFT JOIN divisions dv ON dv.id = d.division_id
LEFT JOIN LATERAL (
    SELECT tw2.name
    FROM stock_transfers st
    JOIN warehouses tw2 ON tw2.id = st.to_warehouse_id
    WHERE h.source_type = 'transfer'
      AND st.group_id = h.source_id
      AND st.item_id  = h.item_id
    LIMIT 1
) tw ON TRUE
WHERE ($2::date IS NULL OR h.date >= $2)
  AND ($3::date IS NULL OR h.date <= $3)
ORDER BY h.date DESC, h.created_at DESC
`

type ListStockHistoryByItemParams struct {
	ItemID  pgtype.UUID `json:"item_id"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

type ListStockHistoryByItemRow struct {
	ID             pgtype.UUID        `json:"id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	QuantityChange pgtype.Numeric     `json:"quantity_change"`
	UnitName       string             `json:"unit_name"`
	Vendor         pgtype.Text        `json:"vendor"`
	Type           string             `json:"type"`
	Reference      pgtype.Text        `json:"reference"`
	Date           pgtype.Date        `json:"date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Value          pgtype.Int8        `json:"value"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceType     pgtype.Text        `json:"source_type"`
	WarehouseName  pgtype.Text        `json:"warehouse_name"`
	BalanceAfter   pgtype.Numeric     `json:"balance_after"`
	Destination    pgtype.Text        `json:"destination"`
}

func (q *Queries) ListStockHistoryByItem(ctx context.Context, arg *ListStockHistoryByItemParams) ([]*ListStockHistoryByItemRow, error) {
	rows, err := q.db.Query(ctx, listStockHistoryByItem, arg.ItemID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStockHistoryByItemRow
	for rows.Next() {
		var i ListStockHistoryByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WarehouseID,
			&i.QuantityChange,
			&i.UnitName,
			&i.Vendor,
			&i.Type,
			&i.Reference,
			&i.Date,
			&i.CreatedAt,
			&i.Value,
			&i.SourceID,
			&i.SourceType,
			&i.WarehouseName,
			&i.BalanceAfter,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
