// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStockHistoryBySource = `-- name: DeleteStockHistoryBySource :exec
DELETE FROM stock_history WHERE source_id = $1 AND source_type = $2
`

type DeleteStockHistoryBySourceParams struct {
	SourceID   pgtype.UUID `json:"source_id"`
	SourceType pgtype.Text `json:"source_type"`
}

func (q *Queries) DeleteStockHistoryBySource(ctx context.Context, arg *DeleteStockHistoryBySourceParams) error {
	_, err := q.db.Exec(ctx, deleteStockHistoryBySource, arg.SourceID, arg.SourceType)
	return err
}

const insertStockHistory = `-- name: InsertStockHistory :one
INSERT INTO stock_history (
    id, item_id, warehouse_id, quantity_change, unit_name,
    vendor, type, reference, date, value, source_id, source_type
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id
`

type InsertStockHistoryParams struct {
	ItemID         pgtype.UUID    `json:"item_id"`
	WarehouseID    pgtype.UUID    `json:"warehouse_id"`
	QuantityChange pgtype.Numeric `json:"quantity_change"`
	UnitName       string         `json:"unit_name"`
	Vendor         pgtype.Text    `json:"vendor"`
	Type           string         `json:"type"`
	Reference      pgtype.Text    `json:"reference"`
	Date           pgtype.Date    `json:"date"`
	Value          pgtype.Int8    `json:"value"`
	SourceID       pgtype.UUID    `json:"source_id"`
	SourceType     pgtype.Text    `json:"source_type"`
}

func (q *Queries) InsertStockHistory(ctx context.Context, arg *InsertStockHistoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertStockHistory,
		arg.ItemID,
		arg.WarehouseID,
		arg.QuantityChange,
		arg.UnitName,
		arg.Vendor,
		arg.Type,
		arg.Reference,
		arg.Date,
		arg.Value,
		arg.SourceID,
		arg.SourceType,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listStockHistoryByItem = `-- name: ListStockHistoryByItem :many
SELECT
    sh.id, sh.item_id, sh.warehouse_id, sh.quantity_change,
    sh.unit_name, sh.vendor, sh.type, sh.reference,
    sh.date, sh.created_at, sh.value,
    w.name AS warehouse_name
FROM stock_history sh
LEFT JOIN warehouses w ON w.id = sh.warehouse_id
WHERE sh.item_id = $1
  AND ($2::date IS NULL OR sh.date >= $2)
  AND ($3::date IS NULL OR sh.date <= $3)
ORDER BY sh.date DESC, sh.created_at DESC
`

type ListStockHistoryByItemParams struct {
	ItemID  pgtype.UUID `json:"item_id"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

type ListStockHistoryByItemRow struct {
	ID             pgtype.UUID        `json:"id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	QuantityChange pgtype.Numeric     `json:"quantity_change"`
	UnitName       string             `json:"unit_name"`
	Vendor         pgtype.Text        `json:"vendor"`
	Type           string             `json:"type"`
	Reference      pgtype.Text        `json:"reference"`
	Date           pgtype.Date        `json:"date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Value          pgtype.Int8        `json:"value"`
	WarehouseName  pgtype.Text        `json:"warehouse_name"`
}

func (q *Queries) ListStockHistoryByItem(ctx context.Context, arg *ListStockHistoryByItemParams) ([]*ListStockHistoryByItemRow, error) {
	rows, err := q.db.Query(ctx, listStockHistoryByItem, arg.ItemID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStockHistoryByItemRow
	for rows.Next() {
		var i ListStockHistoryByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WarehouseID,
			&i.QuantityChange,
			&i.UnitName,
			&i.Vendor,
			&i.Type,
			&i.Reference,
			&i.Date,
			&i.CreatedAt,
			&i.Value,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
