// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_transfers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStockTransfer = `-- name: InsertStockTransfer :one
INSERT INTO stock_transfers (
    id, item_id, from_warehouse_id, to_warehouse_id,
    quantity, unit_index, unit_name, notes, transferred_by, group_id
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, transferred_at
`

type InsertStockTransferParams struct {
	ItemID          pgtype.UUID    `json:"item_id"`
	FromWarehouseID pgtype.UUID    `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID    `json:"to_warehouse_id"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitIndex       int32          `json:"unit_index"`
	UnitName        string         `json:"unit_name"`
	Notes           pgtype.Text    `json:"notes"`
	TransferredBy   pgtype.UUID    `json:"transferred_by"`
	GroupID         pgtype.UUID    `json:"group_id"`
}

type InsertStockTransferRow struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	TransferredAt pgtype.Timestamptz `json:"transferred_at"`
}

func (q *Queries) InsertStockTransfer(ctx context.Context, arg *InsertStockTransferParams) (*InsertStockTransferRow, error) {
	row := q.db.QueryRow(ctx, insertStockTransfer,
		arg.ItemID,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.Quantity,
		arg.UnitIndex,
		arg.UnitName,
		arg.Notes,
		arg.TransferredBy,
		arg.GroupID,
	)
	var i InsertStockTransferRow
	err := row.Scan(&i.ID, &i.GroupID, &i.TransferredAt)
	return &i, err
}

const listStockTransfers = `-- name: ListStockTransfers :many
SELECT
    st.id, st.item_id, st.from_warehouse_id, st.to_warehouse_id,
    st.quantity, st.unit_index, st.unit_name, st.notes,
    st.transferred_by, st.transferred_at, st.group_id,
    i.name AS item_name,
    fw.name AS from_warehouse_name,
    tw.name AS to_warehouse_name,
    u.username AS transferred_by_name
FROM stock_transfers st
JOIN items i ON i.id = st.item_id
JOIN warehouses fw ON fw.id = st.from_warehouse_id
JOIN warehouses tw ON tw.id = st.to_warehouse_id
LEFT JOIN users u ON u.id = st.transferred_by
WHERE ($1::date IS NULL OR st.transferred_at::date >= $1)
  AND ($2::date IS NULL OR st.transferred_at::date <= $2)
ORDER BY st.transferred_at DESC
`

type ListStockTransfersParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListStockTransfersRow struct {
	ID                pgtype.UUID        `json:"id"`
	ItemID            pgtype.UUID        `json:"item_id"`
	FromWarehouseID   pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID     pgtype.UUID        `json:"to_warehouse_id"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	UnitIndex         int32              `json:"unit_index"`
	UnitName          string             `json:"unit_name"`
	Notes             pgtype.Text        `json:"notes"`
	TransferredBy     pgtype.UUID        `json:"transferred_by"`
	TransferredAt     pgtype.Timestamptz `json:"transferred_at"`
	GroupID           pgtype.UUID        `json:"group_id"`
	ItemName          string             `json:"item_name"`
	FromWarehouseName string             `json:"from_warehouse_name"`
	ToWarehouseName   string             `json:"to_warehouse_name"`
	TransferredByName pgtype.Text        `json:"transferred_by_name"`
}

func (q *Queries) ListStockTransfers(ctx context.Context, arg *ListStockTransfersParams) ([]*ListStockTransfersRow, error) {
	rows, err := q.db.Query(ctx, listStockTransfers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStockTransfersRow
	for rows.Next() {
		var i ListStockTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.Quantity,
			&i.UnitIndex,
			&i.UnitName,
			&i.Notes,
			&i.TransferredBy,
			&i.TransferredAt,
			&i.GroupID,
			&i.ItemName,
			&i.FromWarehouseName,
			&i.ToWarehouseName,
			&i.TransferredByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransfersByGroup = `-- name: ListStockTransfersByGroup :many
SELECT
    st.id, st.item_id, st.from_warehouse_id, st.to_warehouse_id,
    st.quantity, st.unit_index, st.unit_name, st.notes,
    st.transferred_by, st.transferred_at, st.group_id,
    i.name AS item_name,
    fw.name AS from_warehouse_name,
    tw.name AS to_warehouse_name
FROM stock_transfers st
JOIN items i ON i.id = st.item_id
JOIN warehouses fw ON fw.id = st.from_warehouse_id
JOIN warehouses tw ON tw.id = st.to_warehouse_id
WHERE st.group_id = $1
ORDER BY i.name
`

type ListStockTransfersByGroupRow struct {
	ID                pgtype.UUID        `json:"id"`
	ItemID            pgtype.UUID        `json:"item_id"`
	FromWarehouseID   pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID     pgtype.UUID        `json:"to_warehouse_id"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	UnitIndex         int32              `json:"unit_index"`
	UnitName          string             `json:"unit_name"`
	Notes             pgtype.Text        `json:"notes"`
	TransferredBy     pgtype.UUID        `json:"transferred_by"`
	TransferredAt     pgtype.Timestamptz `json:"transferred_at"`
	GroupID           pgtype.UUID        `json:"group_id"`
	ItemName          string             `json:"item_name"`
	FromWarehouseName string             `json:"from_warehouse_name"`
	ToWarehouseName   string             `json:"to_warehouse_name"`
}

func (q *Queries) ListStockTransfersByGroup(ctx context.Context, groupID pgtype.UUID) ([]*ListStockTransfersByGroupRow, error) {
	rows, err := q.db.Query(ctx, listStockTransfersByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStockTransfersByGroupRow
	for rows.Next() {
		var i ListStockTransfersByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.Quantity,
			&i.UnitIndex,
			&i.UnitName,
			&i.Notes,
			&i.TransferredBy,
			&i.TransferredAt,
			&i.GroupID,
			&i.ItemName,
			&i.FromWarehouseName,
			&i.ToWarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
