// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (id, name)
VALUES (gen_random_uuid(), $1)
RETURNING id, name
`

func (q *Queries) CreateVendor(ctx context.Context, name string) (*Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor, name)
	var i Vendor
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVendor, id)
	return err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, name FROM vendors WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id pgtype.UUID) (*Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const getVendorHistory = `-- name: GetVendorHistory :many
SELECT
    i.id,
    i.invoice_number,
    i.date,
    i.invoice_type,
    i.payment_status,
    COALESCE(SUM(ii.price * ii.quantity), 0)::BIGINT AS total_amount,
    i.amount_paid
FROM invoices i
LEFT JOIN invoice_items ii ON ii.invoice_id = i.id
WHERE i.vendor_id = $1
GROUP BY i.id, i.invoice_number, i.date, i.invoice_type, i.payment_status, i.amount_paid
ORDER BY i.date DESC
`

type GetVendorHistoryRow struct {
	ID            pgtype.UUID `json:"id"`
	InvoiceNumber string      `json:"invoice_number"`
	Date          pgtype.Date `json:"date"`
	InvoiceType   string      `json:"invoice_type"`
	PaymentStatus string      `json:"payment_status"`
	TotalAmount   int64       `json:"total_amount"`
	AmountPaid    int64       `json:"amount_paid"`
}

func (q *Queries) GetVendorHistory(ctx context.Context, vendorID pgtype.UUID) ([]*GetVendorHistoryRow, error) {
	rows, err := q.db.Query(ctx, getVendorHistory, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetVendorHistoryRow
	for rows.Next() {
		var i GetVendorHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.Date,
			&i.InvoiceType,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.AmountPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendors = `-- name: ListVendors :many
SELECT id, name FROM vendors ORDER BY name
`

func (q *Queries) ListVendors(ctx context.Context) ([]*Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors SET name = $1 WHERE id = $2
RETURNING id, name
`

type UpdateVendorParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg *UpdateVendorParams) (*Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor, arg.Name, arg.ID)
	var i Vendor
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}
