// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountForWarehouse = `-- name: CreateAccountForWarehouse :one
INSERT INTO accounts (id, name, account_number, account_type, balance, is_system)
VALUES (gen_random_uuid(), $1, $2, 'asset', 0, false)
RETURNING id
`

type CreateAccountForWarehouseParams struct {
	Name          string      `json:"name"`
	AccountNumber pgtype.Int4 `json:"account_number"`
}

func (q *Queries) CreateAccountForWarehouse(ctx context.Context, arg *CreateAccountForWarehouseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccountForWarehouse, arg.Name, arg.AccountNumber)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (id, name, inventory_account_id)
VALUES (gen_random_uuid(), $1, $2)
RETURNING id, name, inventory_account_id
`

type CreateWarehouseParams struct {
	Name               string      `json:"name"`
	InventoryAccountID pgtype.UUID `json:"inventory_account_id"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg *CreateWarehouseParams) (*Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse, arg.Name, arg.InventoryAccountID)
	var i Warehouse
	err := row.Scan(&i.ID, &i.Name, &i.InventoryAccountID)
	return &i, err
}

const deleteWarehouse = `-- name: DeleteWarehouse :exec
DELETE FROM warehouses WHERE id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWarehouse, id)
	return err
}

const getNextInventoryAccountNumber = `-- name: GetNextInventoryAccountNumber :one
SELECT COALESCE(MAX(account_number), 10999) + 1 AS next_number
FROM accounts
WHERE account_number BETWEEN 11000 AND 19999
`

func (q *Queries) GetNextInventoryAccountNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextInventoryAccountNumber)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getWarehouseByID = `-- name: GetWarehouseByID :one
SELECT w.id, w.name, w.inventory_account_id, a.name AS account_name
FROM warehouses w
LEFT JOIN accounts a ON a.id = w.inventory_account_id
WHERE w.id = $1
`

type GetWarehouseByIDRow struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	InventoryAccountID pgtype.UUID `json:"inventory_account_id"`
	AccountName        pgtype.Text `json:"account_name"`
}

func (q *Queries) GetWarehouseByID(ctx context.Context, id pgtype.UUID) (*GetWarehouseByIDRow, error) {
	row := q.db.QueryRow(ctx, getWarehouseByID, id)
	var i GetWarehouseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InventoryAccountID,
		&i.AccountName,
	)
	return &i, err
}

const getWarehouseInventoryAccountID = `-- name: GetWarehouseInventoryAccountID :one
SELECT inventory_account_id FROM warehouses WHERE id = $1
`

func (q *Queries) GetWarehouseInventoryAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getWarehouseInventoryAccountID, id)
	var inventory_account_id pgtype.UUID
	err := row.Scan(&inventory_account_id)
	return inventory_account_id, err
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT w.id, w.name, w.inventory_account_id, a.name AS account_name
FROM warehouses w
LEFT JOIN accounts a ON a.id = w.inventory_account_id
ORDER BY w.name
`

type ListWarehousesRow struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	InventoryAccountID pgtype.UUID `json:"inventory_account_id"`
	AccountName        pgtype.Text `json:"account_name"`
}

func (q *Queries) ListWarehouses(ctx context.Context) ([]*ListWarehousesRow, error) {
	rows, err := q.db.Query(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListWarehousesRow
	for rows.Next() {
		var i ListWarehousesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InventoryAccountID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouses SET name = $1 WHERE id = $2
RETURNING id, name, inventory_account_id
`

type UpdateWarehouseParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg *UpdateWarehouseParams) (*Warehouse, error) {
	row := q.db.QueryRow(ctx, updateWarehouse, arg.Name, arg.ID)
	var i Warehouse
	err := row.Scan(&i.ID, &i.Name, &i.InventoryAccountID)
	return &i, err
}
